/**
 * Kitchen Blog Registry
 * Describes all kitchen blog articles. Content lives in src/lib/content/kitchen-blogs/.
 * This file is metadata-only — no article body content stored here.
 */

export type KitchenBlogEntry = {
  /** URL slug — appended to /blog/ */
  slug: string;
  /** Browser <title> */
  title: string;
  /** Meta description (150–160 chars) */
  metaDescription: string;
  /** H1 heading */
  h1: string;
  /** Short excerpt for index cards */
  excerpt: string;
  /** Category slug — must match a KitchenBlogCategory.slug */
  category: "layouts" | "materials" | "cost" | "city" | "planning";
  /** Content file ID — corresponds to src/lib/content/kitchen-blogs/{contentId}.ts */
  contentId: string;
  /** ISO-8601 date */
  publishedAt: string;
  /** ISO-8601 date */
  updatedAt: string;
  /** Estimated read time */
  readTime: string;
  /** Internal links shown in sidebar / related service pages */
  relatedServiceLinks: { label: string; href: string }[];
  /** 3–4 slugs of related blog articles (from this registry) */
  relatedArticleSlugs: string[];
  /** published = live; draft = excluded from routes */
  status: "published" | "draft";
  /** Featured image URL (CDN) */
  featuredImage: string;
};

export const KITCHEN_BLOG_REGISTRY: readonly KitchenBlogEntry[] = [
  // ─── LAYOUT GUIDES (6) ─────────────────────────────────────────────────────
  {
    slug: "modular-kitchen-l-shape-design-guide",
    title: "L-Shape Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "Everything about L-shape modular kitchens — dimensions, advantages, layout tips, and cost in Delhi NCR. Free 3D design consultation.",
    h1: "L-Shape Modular Kitchen: Complete Design Guide",
    excerpt: "The most popular kitchen layout in India — learn dimensions, advantages, and how to get the most from your L-shape kitchen.",
    category: "layouts",
    contentId: "l-shape-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "L-Shape Kitchen Page", href: "/modular-kitchen-l-shape" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Kitchen Cost Guide", href: "/modular-kitchen-cost-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-u-shape-design-guide",
      "choosing-kitchen-layout-guide",
      "modular-kitchen-cost-delhi-guide",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_kcWs3I3r503Bb8cEHdfBB8fo",
  },
  {
    slug: "modular-kitchen-u-shape-design-guide",
    title: "U-Shape Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "U-shape modular kitchen guide — best for large kitchens, tri-wall storage, and efficient workflow. Dimensions, costs, and design tips.",
    h1: "U-Shape Modular Kitchen: Complete Design Guide",
    excerpt: "Maximum storage, maximum workspace — the U-shape kitchen is ideal for serious home cooks and large kitchens.",
    category: "layouts",
    contentId: "u-shape-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "U-Shape Kitchen Page", href: "/modular-kitchen-u-shape" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Kitchen Cost Guide", href: "/modular-kitchen-cost-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-l-shape-design-guide",
      "modular-kitchen-island-design-guide",
      "choosing-kitchen-layout-guide",
      "modular-kitchen-cost-delhi-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_lhlCPHMXg1s5C4UjHD8he0sV",
  },
  {
    slug: "modular-kitchen-parallel-design-guide",
    title: "Parallel Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "Parallel modular kitchen — galley-style layout ideal for narrow kitchens. Design tips, dimensions, and cost in Delhi NCR.",
    h1: "Parallel Modular Kitchen: Complete Design Guide",
    excerpt: "Parallel kitchens maximise efficiency in narrow spaces. Learn how to design one that feels spacious and works well.",
    category: "layouts",
    contentId: "parallel-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Parallel Kitchen Page", href: "/modular-kitchen-parallel" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-straight-design-guide",
      "modular-kitchen-l-shape-design-guide",
      "choosing-kitchen-layout-guide",
      "small-apartment-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_VGfRXBlsXw8FD7Hc1uzlZEwp",
  },
  {
    slug: "modular-kitchen-straight-design-guide",
    title: "Straight Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "Straight (single-wall) modular kitchen — best for studio apartments and compact homes. Design tips, dimensions, and cost.",
    h1: "Straight Modular Kitchen: Complete Design Guide",
    excerpt: "Simple, clean, and space-efficient — the straight kitchen is perfect for compact homes and studio apartments.",
    category: "layouts",
    contentId: "straight-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "5 min read",
    relatedServiceLinks: [
      { label: "Straight Kitchen Page", href: "/modular-kitchen-straight" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-parallel-design-guide",
      "modular-kitchen-l-shape-design-guide",
      "small-apartment-modular-kitchen",
      "measuring-kitchen-for-modular",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_v8Irf28DaqCTDBPwFkcEA3YW",
  },
  {
    slug: "modular-kitchen-island-design-guide",
    title: "Island Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "Island modular kitchen — the ultimate open kitchen for large homes. Design, dimensions, cost, and tips for Delhi NCR homes.",
    h1: "Island Modular Kitchen: Complete Design Guide",
    excerpt: "A kitchen island transforms cooking into a social experience. Learn when it works, how to size it, and what it costs.",
    category: "layouts",
    contentId: "island-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Island Kitchen Page", href: "/modular-kitchen-island" },
      { label: "Luxury Kitchen Cost", href: "/blog/luxury-kitchen-cost-guide" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-u-shape-design-guide",
      "modular-kitchen-peninsula-design-guide",
      "luxury-kitchen-cost-guide",
      "choosing-kitchen-layout-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_djsOu8mcj70UG6FryEc21TlC",
  },
  {
    slug: "modular-kitchen-peninsula-design-guide",
    title: "Peninsula Modular Kitchen Design Guide 2026 | FurniRevive",
    metaDescription: "Peninsula modular kitchen — a connected island for medium kitchens. Design tips, space requirements, and cost in Delhi NCR.",
    h1: "Peninsula Modular Kitchen: Complete Design Guide",
    excerpt: "The peninsula gives you the social feel of an island without needing as much floor space.",
    category: "layouts",
    contentId: "peninsula-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Peninsula Kitchen Page", href: "/modular-kitchen-peninsula" },
      { label: "Island Kitchen Guide", href: "/blog/modular-kitchen-island-design-guide" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-island-design-guide",
      "modular-kitchen-u-shape-design-guide",
      "choosing-kitchen-layout-guide",
      "modular-kitchen-cost-delhi-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_D9FGFjhsA6mz93B2pf0pQic0",
  },

  // ─── MATERIAL GUIDES (8) ───────────────────────────────────────────────────
  {
    slug: "acrylic-modular-kitchen-guide",
    title: "Acrylic Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "Acrylic modular kitchen guide — glossy finish, durability, cost, and comparison with laminate. Is acrylic right for your home?",
    h1: "Acrylic Modular Kitchen: Complete Guide",
    excerpt: "High-gloss, easy to clean, and striking — acrylic is one of the most popular finishes. Here's everything you need to know.",
    category: "materials",
    contentId: "acrylic-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Acrylic Kitchen Page", href: "/modular-kitchen-acrylic" },
      { label: "Acrylic Kitchen Cost", href: "/blog/acrylic-kitchen-cost-guide" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
    ],
    relatedArticleSlugs: [
      "laminate-modular-kitchen-guide",
      "pu-modular-kitchen-guide",
      "acrylic-kitchen-cost-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_IloMTm7xkcZJkWwsCCR0OfUs",
  },
  {
    slug: "laminate-modular-kitchen-guide",
    title: "Laminate Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "Laminate modular kitchen guide — affordable, durable, and available in hundreds of designs. Cost, care tips, and comparison with acrylic.",
    h1: "Laminate Modular Kitchen: Complete Guide",
    excerpt: "Laminate is the most budget-friendly kitchen finish that still looks premium. Learn the types, costs, and care tips.",
    category: "materials",
    contentId: "laminate-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Laminate Kitchen Page", href: "/modular-kitchen-laminate" },
      { label: "Laminate Kitchen Cost", href: "/blog/laminate-kitchen-cost-guide" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
    ],
    relatedArticleSlugs: [
      "acrylic-modular-kitchen-guide",
      "membrane-modular-kitchen-guide",
      "laminate-kitchen-cost-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vtmk6xG3eXfLqwBp6sAeflWr",
  },
  {
    slug: "membrane-modular-kitchen-guide",
    title: "Membrane Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "Membrane modular kitchen guide — seamless finish, moisture resistance, and cost. How membrane compares to acrylic and PU.",
    h1: "Membrane Modular Kitchen: Complete Guide",
    excerpt: "Membrane finish offers a smooth, seamless look with good moisture resistance — ideal for humid Indian kitchens.",
    category: "materials",
    contentId: "membrane-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Membrane Kitchen Page", href: "/modular-kitchen-membrane" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Choosing Materials Guide", href: "/blog/choosing-kitchen-materials-guide" },
    ],
    relatedArticleSlugs: [
      "pvc-modular-kitchen-guide",
      "acrylic-modular-kitchen-guide",
      "laminate-modular-kitchen-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_KbLdVBRE4LYFiPamNqexMnxl",
  },
  {
    slug: "pvc-modular-kitchen-guide",
    title: "PVC Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "PVC modular kitchen — waterproof, termite-proof, and cost-effective. Full guide to PVC cabinet finishes for Indian kitchens.",
    h1: "PVC Modular Kitchen: Complete Guide",
    excerpt: "PVC is the most water-resistant kitchen material — ideal for humid climates and budget-conscious homeowners.",
    category: "materials",
    contentId: "pvc-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "PVC Kitchen Page", href: "/modular-kitchen-pvc" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
    ],
    relatedArticleSlugs: [
      "membrane-modular-kitchen-guide",
      "laminate-modular-kitchen-guide",
      "small-apartment-modular-kitchen",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_58yHQTGmGFfzAhHc9lCctyE5",
  },
  {
    slug: "pu-modular-kitchen-guide",
    title: "PU Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "PU (polyurethane) modular kitchen guide — ultra-smooth matte and gloss finish, durability, and cost. Is PU right for your kitchen?",
    h1: "PU Modular Kitchen: Complete Guide",
    excerpt: "PU finish delivers a sophisticated, paint-like surface that other materials can't match. Here's what you need to know.",
    category: "materials",
    contentId: "pu-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "PU Kitchen Page", href: "/modular-kitchen-pu" },
      { label: "Luxury Kitchen Cost", href: "/blog/luxury-kitchen-cost-guide" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
    ],
    relatedArticleSlugs: [
      "acrylic-modular-kitchen-guide",
      "veneer-modular-kitchen-guide",
      "luxury-kitchen-cost-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_igHnChlrLBP8QHjiD50g6l7b",
  },
  {
    slug: "veneer-modular-kitchen-guide",
    title: "Veneer Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "Veneer modular kitchen — natural wood look, warmth, and premium finish. Cost, care, and comparison with laminate in Delhi NCR.",
    h1: "Veneer Modular Kitchen: Complete Guide",
    excerpt: "Veneer brings real wood warmth to a modular kitchen. Learn about types, costs, maintenance, and when to choose it.",
    category: "materials",
    contentId: "veneer-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Veneer Kitchen Page", href: "/modular-kitchen-veneer" },
      { label: "Luxury Kitchen Cost", href: "/blog/luxury-kitchen-cost-guide" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
    ],
    relatedArticleSlugs: [
      "pu-modular-kitchen-guide",
      "acrylic-modular-kitchen-guide",
      "luxury-kitchen-cost-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_bJ8OfIcFlNvSc6fWcfYMlxld",
  },
  {
    slug: "glass-modular-kitchen-guide",
    title: "Glass Modular Kitchen: Complete Guide 2026 | FurniRevive",
    metaDescription: "Glass modular kitchen — reflective, modern, and striking. Types of glass finishes, cost, and care tips for Indian homes.",
    h1: "Glass Modular Kitchen: Complete Guide",
    excerpt: "Glass finishes make a kitchen look twice as large and add a boutique hotel quality to everyday cooking.",
    category: "materials",
    contentId: "glass-modular-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Glass Kitchen Page", href: "/modular-kitchen-glass" },
      { label: "Luxury Kitchen Cost", href: "/blog/luxury-kitchen-cost-guide" },
      { label: "Island Kitchen Guide", href: "/blog/modular-kitchen-island-design-guide" },
    ],
    relatedArticleSlugs: [
      "acrylic-modular-kitchen-guide",
      "pu-modular-kitchen-guide",
      "luxury-kitchen-cost-guide",
      "modular-kitchen-island-design-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_zPPi8vvUMRn2uha1ODXLdXUq",
  },
  {
    slug: "stainless-steel-modular-kitchen-guide",
    title: "Stainless Steel Modular Kitchen Guide 2026 | FurniRevive",
    metaDescription: "Stainless steel modular kitchen — hygienic, durable, and commercial-grade. Full guide for residential and professional kitchens.",
    h1: "Stainless Steel Modular Kitchen: Complete Guide",
    excerpt: "Stainless steel is the choice of professional chefs and hygiene-conscious homeowners. Here's everything you need to know.",
    category: "materials",
    contentId: "stainless-steel-kitchen-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Stainless Steel Kitchen Page", href: "/modular-kitchen-stainless-steel" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Kitchen Maintenance Guide", href: "/blog/kitchen-maintenance-guide" },
    ],
    relatedArticleSlugs: [
      "glass-modular-kitchen-guide",
      "laminate-modular-kitchen-guide",
      "kitchen-maintenance-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_gl5ZGkrN9xOrIYcF6JNq7AOT",
  },

  // ─── COST GUIDES (8) ──────────────────────────────────────────────────────
  {
    slug: "modular-kitchen-cost-delhi-guide",
    title: "Modular Kitchen Cost in Delhi 2026: Full Price Breakdown | FurniRevive",
    metaDescription: "Modular kitchen cost in Delhi — detailed 2026 pricing by finish, size, and brand. Know exactly what ₹1L, ₹2L, and ₹5L buys you.",
    h1: "Modular Kitchen Cost in Delhi 2026: Full Price Breakdown",
    excerpt: "A transparent, no-nonsense breakdown of what a modular kitchen actually costs in Delhi — by material, size, and quality tier.",
    category: "cost",
    contentId: "modular-kitchen-cost-delhi-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Cost Page", href: "/modular-kitchen-cost-delhi" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Get Free Quote", href: "/book" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-gurgaon",
      "small-kitchen-cost-guide",
      "luxury-kitchen-cost-guide",
      "modular-vs-carpenter-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_KMOy57N0vDd7uAhUDb78XKmT",
  },
  {
    slug: "modular-kitchen-cost-gurgaon",
    title: "Modular Kitchen Cost in Gurgaon 2026: Price Guide | FurniRevive",
    metaDescription: "Modular kitchen cost in Gurgaon — 2026 pricing for DLF phases, Golf Course Road, Sohna Road and all major areas. Free consultation.",
    h1: "Modular Kitchen Cost in Gurgaon 2026: Complete Price Guide",
    excerpt: "Gurgaon kitchen costs vary by sector and finish. Here's a complete breakdown with area-specific pricing insights.",
    category: "cost",
    contentId: "modular-kitchen-cost-gurgaon",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "DLF Phase Kitchens", href: "/modular-kitchen-dlf-phase-gurgaon" },
      { label: "Golf Course Road Kitchens", href: "/modular-kitchen-golf-course-road-gurgaon" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-delhi-guide",
      "luxury-kitchen-cost-guide",
      "modular-kitchen-gurgaon-guide",
      "modular-kitchen-island-design-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_377PCNdLNGIek6MzCyjCt9ck",
  },
  {
    slug: "small-kitchen-cost-guide",
    title: "Small Modular Kitchen Cost 2026: Budget Guide Under ₹2 Lakh | FurniRevive",
    metaDescription: "Small modular kitchen cost guide — what you can get under ₹1L, ₹1.5L, and ₹2L in Delhi NCR. Tips for maximising a compact kitchen.",
    h1: "Small Modular Kitchen Cost 2026: Budget Guide",
    excerpt: "A small kitchen doesn't have to feel small. Here's how to maximise quality and storage on a tight budget.",
    category: "cost",
    contentId: "small-kitchen-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Straight Kitchen", href: "/modular-kitchen-straight" },
      { label: "Parallel Kitchen", href: "/modular-kitchen-parallel" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-delhi-guide",
      "small-apartment-modular-kitchen",
      "modular-kitchen-straight-design-guide",
      "modular-kitchen-parallel-design-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_GoyMqLfjKEiS94UoQgcuAzlj",
  },
  {
    slug: "10x10-kitchen-cost-guide",
    title: "10×10 Modular Kitchen Cost 2026: Complete Price Guide | FurniRevive",
    metaDescription: "10×10 modular kitchen cost in Delhi NCR — 2026 pricing for 100 sq ft kitchens across all materials and quality tiers.",
    h1: "10×10 Modular Kitchen Cost 2026: Complete Price Guide",
    excerpt: "100 sq ft is the most common kitchen size in Delhi NCR apartments. Here's exactly what it costs across every budget tier.",
    category: "cost",
    contentId: "10x10-kitchen-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "L-Shape Kitchen", href: "/modular-kitchen-l-shape" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-delhi-guide",
      "small-kitchen-cost-guide",
      "modular-kitchen-l-shape-design-guide",
      "kitchen-installation-cost-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_w2FSVjzzp2yO9Kw92NvttlzL",
  },
  {
    slug: "luxury-kitchen-cost-guide",
    title: "Luxury Modular Kitchen Cost 2026: Premium Design Guide | FurniRevive",
    metaDescription: "Luxury modular kitchen cost in Delhi NCR — what ₹5L, ₹10L, and ₹20L+ buys you. Premium materials, Blum hardware, and custom design.",
    h1: "Luxury Modular Kitchen Cost 2026: What Premium Really Costs",
    excerpt: "What separates a ₹5L kitchen from a ₹20L kitchen? A complete guide to luxury kitchen upgrades and where money is best spent.",
    category: "cost",
    contentId: "luxury-kitchen-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Luxury Kitchen Cost Page", href: "/modular-kitchen-luxury" },
      { label: "Island Kitchen", href: "/modular-kitchen-island" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-island-design-guide",
      "glass-modular-kitchen-guide",
      "veneer-modular-kitchen-guide",
      "modular-kitchen-cost-delhi-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_djsOu8mcj70UG6FryEc21TlC",
  },
  {
    slug: "acrylic-kitchen-cost-guide",
    title: "Acrylic Modular Kitchen Cost 2026: Pricing Guide | FurniRevive",
    metaDescription: "Acrylic modular kitchen cost in Delhi NCR — 2026 pricing by size and quality. Is acrylic worth the premium over laminate?",
    h1: "Acrylic Modular Kitchen Cost 2026: Complete Pricing Guide",
    excerpt: "Acrylic costs more than laminate — but is it worth it? A detailed cost breakdown with honest comparisons.",
    category: "cost",
    contentId: "acrylic-kitchen-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Acrylic Kitchen Page", href: "/modular-kitchen-acrylic" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Acrylic Guide", href: "/blog/acrylic-modular-kitchen-guide" },
    ],
    relatedArticleSlugs: [
      "acrylic-modular-kitchen-guide",
      "laminate-kitchen-cost-guide",
      "modular-kitchen-cost-delhi-guide",
      "choosing-kitchen-materials-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_IloMTm7xkcZJkWwsCCR0OfUs",
  },
  {
    slug: "laminate-kitchen-cost-guide",
    title: "Laminate Modular Kitchen Cost 2026: Budget Pricing Guide | FurniRevive",
    metaDescription: "Laminate modular kitchen cost in Delhi NCR — 2026 pricing for economy, standard, and premium laminates. Best value for money.",
    h1: "Laminate Modular Kitchen Cost 2026: Budget Pricing Guide",
    excerpt: "Laminate is the best value kitchen finish in India. Here's a complete cost guide so you know what to budget.",
    category: "cost",
    contentId: "laminate-kitchen-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Laminate Kitchen Page", href: "/modular-kitchen-laminate" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Laminate Guide", href: "/blog/laminate-modular-kitchen-guide" },
    ],
    relatedArticleSlugs: [
      "laminate-modular-kitchen-guide",
      "acrylic-kitchen-cost-guide",
      "small-kitchen-cost-guide",
      "modular-kitchen-cost-delhi-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vtmk6xG3eXfLqwBp6sAeflWr",
  },
  {
    slug: "kitchen-installation-cost-guide",
    title: "Modular Kitchen Installation Cost 2026: What to Expect | FurniRevive",
    metaDescription: "Modular kitchen installation cost in Delhi NCR — labour charges, timeline, and what's included. No hidden costs.",
    h1: "Modular Kitchen Installation Cost 2026: What to Expect",
    excerpt: "Installation accounts for 15–25% of a kitchen project. Here's a transparent breakdown of every cost involved.",
    category: "cost",
    contentId: "kitchen-installation-cost-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "How to Plan Kitchen", href: "/blog/how-to-plan-modular-kitchen" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-delhi-guide",
      "how-to-plan-modular-kitchen",
      "modular-kitchen-checklist",
      "common-kitchen-renovation-mistakes",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_rAsfdNyOjPSfpeWcQQ0zj6Fr",
  },

  // ─── CITY GUIDES (5) ──────────────────────────────────────────────────────
  {
    slug: "modular-kitchen-delhi-guide",
    title: "Modular Kitchen in Delhi 2026: Best Areas, Prices & Trends | FurniRevive",
    metaDescription: "Modular kitchen in Delhi — best localities, 2026 pricing, popular layouts, and how to find a reliable installer. Free 3D design.",
    h1: "Modular Kitchen in Delhi: 2026 Complete Guide",
    excerpt: "From South Delhi luxury kitchens to mid-range Dwarka and Rohini projects — everything you need to know about kitchens in Delhi.",
    category: "city",
    contentId: "modular-kitchen-delhi-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "South Delhi Kitchens", href: "/modular-kitchen-south-delhi" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-delhi-guide",
      "modular-kitchen-gurgaon-guide",
      "modular-vs-carpenter-kitchen",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_KMOy57N0vDd7uAhUDb78XKmT",
  },
  {
    slug: "modular-kitchen-gurgaon-guide",
    title: "Modular Kitchen in Gurgaon 2026: Best Areas & Pricing | FurniRevive",
    metaDescription: "Modular kitchen in Gurgaon — 2026 guide covering DLF phases, Golf Course Road, Sohna Road and all premium sectors. Free 3D design.",
    h1: "Modular Kitchen in Gurgaon: 2026 Complete Guide",
    excerpt: "Gurgaon's premium localities demand premium kitchens. A complete guide to modular kitchen options across all major sectors.",
    category: "city",
    contentId: "modular-kitchen-gurgaon-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "DLF Phase Kitchens", href: "/modular-kitchen-dlf-phase-gurgaon" },
      { label: "Kitchen Cost Gurgaon", href: "/blog/modular-kitchen-cost-gurgaon" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-cost-gurgaon",
      "modular-kitchen-delhi-guide",
      "luxury-kitchen-cost-guide",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_377PCNdLNGIek6MzCyjCt9ck",
  },
  {
    slug: "modular-kitchen-noida-guide",
    title: "Modular Kitchen in Noida 2026: Price Guide & Top Areas | FurniRevive",
    metaDescription: "Modular kitchen in Noida — 2026 pricing across Sector 62, Sector 150, Indirapuram and major expressway sectors. Free consultation.",
    h1: "Modular Kitchen in Noida: 2026 Complete Guide",
    excerpt: "Noida's planned sectors offer excellent value for modular kitchens. Here's everything you need to know about the market.",
    category: "city",
    contentId: "modular-kitchen-noida-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchens Delhi NCR", href: "/modular-kitchen" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "How to Plan Kitchen", href: "/blog/how-to-plan-modular-kitchen" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-delhi-guide",
      "modular-kitchen-gurgaon-guide",
      "modular-kitchen-cost-delhi-guide",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_bEyqt1YZGAd7E6AHMzz915BC",
  },
  {
    slug: "modular-kitchen-faridabad-guide",
    title: "Modular Kitchen in Faridabad 2026: Price Guide | FurniRevive",
    metaDescription: "Modular kitchen in Faridabad — 2026 pricing, popular areas, and design options. Professional installation across all Faridabad sectors.",
    h1: "Modular Kitchen in Faridabad: 2026 Complete Guide",
    excerpt: "Faridabad's housing market is growing. Here's a complete guide to getting a quality modular kitchen at competitive prices.",
    category: "city",
    contentId: "modular-kitchen-faridabad-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchens Delhi NCR", href: "/modular-kitchen" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-noida-guide",
      "modular-kitchen-ghaziabad-guide",
      "modular-kitchen-cost-delhi-guide",
      "small-kitchen-cost-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_GoyMqLfjKEiS94UoQgcuAzlj",
  },
  {
    slug: "modular-kitchen-ghaziabad-guide",
    title: "Modular Kitchen in Ghaziabad 2026: Price Guide | FurniRevive",
    metaDescription: "Modular kitchen in Ghaziabad — 2026 pricing across Indirapuram, Vaishali, Kaushambi, and Raj Nagar. Free 3D design consultation.",
    h1: "Modular Kitchen in Ghaziabad: 2026 Complete Guide",
    excerpt: "Ghaziabad is one of Delhi NCR's fastest-growing markets for modular kitchens. Here's a complete guide to pricing and areas.",
    category: "city",
    contentId: "modular-kitchen-ghaziabad-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchens Delhi NCR", href: "/modular-kitchen" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-noida-guide",
      "modular-kitchen-faridabad-guide",
      "modular-kitchen-cost-delhi-guide",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_w2FSVjzzp2yO9Kw92NvttlzL",
  },

  // ─── PLANNING GUIDES (11) ────────────────────────────────────────────────
  {
    slug: "modular-vs-carpenter-kitchen",
    title: "Modular Kitchen vs Carpenter-Made: Which is Better in 2026? | FurniRevive",
    metaDescription: "Modular kitchen vs carpenter-made kitchen — honest comparison of cost, quality, warranty, and timeline. Which should you choose?",
    h1: "Modular Kitchen vs Carpenter-Made: Which is Better?",
    excerpt: "The biggest decision in any kitchen renovation. An honest side-by-side comparison with no brand bias.",
    category: "planning",
    contentId: "modular-vs-carpenter-kitchen",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "9 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
    ],
    relatedArticleSlugs: [
      "how-to-plan-modular-kitchen",
      "modular-kitchen-cost-delhi-guide",
      "modular-kitchen-warranty-guide",
      "common-kitchen-renovation-mistakes",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vHwBQgnl3KLJL1Yzu4ujy33h",
  },
  {
    slug: "how-to-plan-modular-kitchen",
    title: "How to Plan a Modular Kitchen in 2026: Step-by-Step Guide | FurniRevive",
    metaDescription: "Step-by-step guide to planning a modular kitchen — from measuring your space to choosing materials, layouts, and hardware.",
    h1: "How to Plan a Modular Kitchen: Step-by-Step Guide",
    excerpt: "Planning a kitchen without a clear process leads to costly mistakes. Follow this proven step-by-step guide to get it right.",
    category: "planning",
    contentId: "how-to-plan-modular-kitchen",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "10 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Cost Delhi", href: "/modular-kitchen-cost-delhi" },
      { label: "Free 3D Design", href: "/book" },
    ],
    relatedArticleSlugs: [
      "measuring-kitchen-for-modular",
      "choosing-kitchen-layout-guide",
      "choosing-kitchen-materials-guide",
      "modular-kitchen-checklist",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vHwBQgnl3KLJL1Yzu4ujy33h",
  },
  {
    slug: "measuring-kitchen-for-modular",
    title: "How to Measure Your Kitchen for a Modular Kitchen | FurniRevive",
    metaDescription: "How to measure your kitchen correctly before ordering modular cabinets. Step-by-step guide with diagrams and common mistakes to avoid.",
    h1: "How to Measure Your Kitchen for a Modular Kitchen",
    excerpt: "Wrong measurements are the most common cause of kitchen renovation failures. Here's how to measure correctly.",
    category: "planning",
    contentId: "measuring-kitchen-for-modular",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "6 min read",
    relatedServiceLinks: [
      { label: "Free 3D Design Consultation", href: "/book" },
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "How to Plan Kitchen", href: "/blog/how-to-plan-modular-kitchen" },
    ],
    relatedArticleSlugs: [
      "how-to-plan-modular-kitchen",
      "choosing-kitchen-layout-guide",
      "modular-kitchen-checklist",
      "common-kitchen-renovation-mistakes",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_GoyMqLfjKEiS94UoQgcuAzlj",
  },
  {
    slug: "choosing-kitchen-layout-guide",
    title: "How to Choose a Modular Kitchen Layout: Complete Guide | FurniRevive",
    metaDescription: "How to choose the right modular kitchen layout for your home — L-shape, U-shape, parallel, straight, island, or peninsula?",
    h1: "How to Choose the Right Modular Kitchen Layout",
    excerpt: "Kitchen layout is the most important design decision. This guide helps you match layout to your space, habits, and budget.",
    category: "planning",
    contentId: "choosing-kitchen-layout-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "L-Shape Kitchen", href: "/modular-kitchen-l-shape" },
      { label: "U-Shape Kitchen", href: "/modular-kitchen-u-shape" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-l-shape-design-guide",
      "modular-kitchen-u-shape-design-guide",
      "modular-kitchen-island-design-guide",
      "how-to-plan-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_kcWs3I3r503Bb8cEHdfBB8fo",
  },
  {
    slug: "choosing-kitchen-materials-guide",
    title: "How to Choose Modular Kitchen Materials: Complete Guide | FurniRevive",
    metaDescription: "How to choose kitchen cabinet materials — acrylic, laminate, PU, membrane, veneer, glass, or stainless steel? Honest comparison.",
    h1: "How to Choose Modular Kitchen Materials: Complete Guide",
    excerpt: "The right material depends on your budget, lifestyle, and aesthetic. An honest comparison of every major kitchen finish.",
    category: "planning",
    contentId: "choosing-kitchen-materials-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "9 min read",
    relatedServiceLinks: [
      { label: "Acrylic Kitchen", href: "/modular-kitchen-acrylic" },
      { label: "Laminate Kitchen", href: "/modular-kitchen-laminate" },
      { label: "PU Kitchen", href: "/modular-kitchen-pu" },
    ],
    relatedArticleSlugs: [
      "acrylic-modular-kitchen-guide",
      "laminate-modular-kitchen-guide",
      "veneer-modular-kitchen-guide",
      "choosing-kitchen-layout-guide",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_IloMTm7xkcZJkWwsCCR0OfUs",
  },
  {
    slug: "common-kitchen-renovation-mistakes",
    title: "10 Common Modular Kitchen Renovation Mistakes to Avoid | FurniRevive",
    metaDescription: "The 10 most expensive modular kitchen renovation mistakes — and how to avoid them. Learn from common errors before you commit.",
    h1: "10 Common Modular Kitchen Renovation Mistakes to Avoid",
    excerpt: "Most kitchen renovation regrets come from the same ten mistakes. Here's how to avoid every one of them.",
    category: "planning",
    contentId: "common-kitchen-renovation-mistakes",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Free 3D Design", href: "/book" },
      { label: "How to Plan Kitchen", href: "/blog/how-to-plan-modular-kitchen" },
    ],
    relatedArticleSlugs: [
      "how-to-plan-modular-kitchen",
      "measuring-kitchen-for-modular",
      "modular-kitchen-checklist",
      "modular-vs-carpenter-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_rAsfdNyOjPSfpeWcQQ0zj6Fr",
  },
  {
    slug: "kitchen-maintenance-guide",
    title: "Modular Kitchen Maintenance Guide 2026 | FurniRevive",
    metaDescription: "How to maintain a modular kitchen — cleaning tips, hardware care, and annual maintenance schedule to keep your kitchen looking new.",
    h1: "Modular Kitchen Maintenance Guide: Keep It New for Years",
    excerpt: "A modular kitchen that's well-maintained lasts 20+ years. Here's a practical care guide for every material and component.",
    category: "planning",
    contentId: "kitchen-maintenance-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "Warranty Guide", href: "/blog/modular-kitchen-warranty-guide" },
    ],
    relatedArticleSlugs: [
      "modular-kitchen-warranty-guide",
      "stainless-steel-modular-kitchen-guide",
      "laminate-modular-kitchen-guide",
      "common-kitchen-renovation-mistakes",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_bEyqt1YZGAd7E6AHMzz915BC",
  },
  {
    slug: "modular-kitchen-warranty-guide",
    title: "Modular Kitchen Warranty Guide 2026: What's Covered? | FurniRevive",
    metaDescription: "Modular kitchen warranty in India — what's covered, for how long, and what to check before signing. FurniRevive's 10-year warranty explained.",
    h1: "Modular Kitchen Warranty Guide: What's Covered and for How Long",
    excerpt: "Warranty terms vary wildly between suppliers. Here's what to demand, what to avoid, and what FurniRevive's 10-year warranty actually covers.",
    category: "planning",
    contentId: "modular-kitchen-warranty-guide",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "Get Free Quote", href: "/book" },
    ],
    relatedArticleSlugs: [
      "modular-vs-carpenter-kitchen",
      "kitchen-maintenance-guide",
      "how-to-plan-modular-kitchen",
      "modular-kitchen-checklist",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vHwBQgnl3KLJL1Yzu4ujy33h",
  },
  {
    slug: "modular-kitchen-design-ideas",
    title: "30 Modular Kitchen Design Ideas for Indian Homes 2026 | FurniRevive",
    metaDescription: "30 modular kitchen design ideas for Indian homes — from small apartments to luxury villas. Inspiration across all layouts and budgets.",
    h1: "30 Modular Kitchen Design Ideas for Indian Homes",
    excerpt: "Visual inspiration for every style and budget — 30 design ideas covering layouts, colours, materials, and storage solutions.",
    category: "planning",
    contentId: "modular-kitchen-design-ideas",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "10 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Modular Kitchen Gurgaon", href: "/modular-kitchen-gurgaon" },
      { label: "Free 3D Design", href: "/book" },
    ],
    relatedArticleSlugs: [
      "choosing-kitchen-layout-guide",
      "choosing-kitchen-materials-guide",
      "modular-kitchen-island-design-guide",
      "small-apartment-modular-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_vHwBQgnl3KLJL1Yzu4ujy33h",
  },
  {
    slug: "small-apartment-modular-kitchen",
    title: "Small Apartment Modular Kitchen: Design & Cost Guide 2026 | FurniRevive",
    metaDescription: "Small apartment modular kitchen design ideas — how to maximise storage, light, and workflow in a compact Indian kitchen.",
    h1: "Small Apartment Modular Kitchen: Design & Cost Guide",
    excerpt: "A compact kitchen can feel just as premium as a large one if designed correctly. Here's how to do it on any budget.",
    category: "planning",
    contentId: "small-apartment-modular-kitchen",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "7 min read",
    relatedServiceLinks: [
      { label: "Straight Kitchen", href: "/modular-kitchen-straight" },
      { label: "Parallel Kitchen", href: "/modular-kitchen-parallel" },
      { label: "Small Kitchen Cost", href: "/blog/small-kitchen-cost-guide" },
    ],
    relatedArticleSlugs: [
      "small-kitchen-cost-guide",
      "modular-kitchen-straight-design-guide",
      "modular-kitchen-parallel-design-guide",
      "measuring-kitchen-for-modular",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_GoyMqLfjKEiS94UoQgcuAzlj",
  },
  {
    slug: "modular-kitchen-checklist",
    title: "Modular Kitchen Checklist 2026: Everything Before You Sign | FurniRevive",
    metaDescription: "Complete modular kitchen checklist — 25 questions to ask your vendor before signing the contract. Never miss an important detail.",
    h1: "Modular Kitchen Checklist: 25 Things to Verify Before Signing",
    excerpt: "Before you pay a rupee, run through this checklist. It covers everything from material quality to warranty terms and installation scope.",
    category: "planning",
    contentId: "modular-kitchen-checklist",
    publishedAt: "2026-07-16",
    updatedAt: "2026-07-16",
    readTime: "8 min read",
    relatedServiceLinks: [
      { label: "Modular Kitchen Delhi", href: "/modular-kitchen-delhi" },
      { label: "Free 3D Design", href: "/book" },
      { label: "How to Plan Kitchen", href: "/blog/how-to-plan-modular-kitchen" },
    ],
    relatedArticleSlugs: [
      "how-to-plan-modular-kitchen",
      "common-kitchen-renovation-mistakes",
      "modular-kitchen-warranty-guide",
      "modular-vs-carpenter-kitchen",
    ],
    status: "published",
    featuredImage: "https://hercules-cdn.com/file_rAsfdNyOjPSfpeWcQQ0zj6Fr",
  },
] as const;

/** Helper: get all published entries */
export function getPublishedKitchenBlogs(): readonly KitchenBlogEntry[] {
  return KITCHEN_BLOG_REGISTRY.filter((e) => e.status === "published");
}

/** Helper: get entries by category */
export function getKitchenBlogsByCategory(category: KitchenBlogEntry["category"]): readonly KitchenBlogEntry[] {
  return KITCHEN_BLOG_REGISTRY.filter((e) => e.status === "published" && e.category === category);
}

/** Helper: get a single entry by slug */
export function getKitchenBlogBySlug(slug: string): KitchenBlogEntry | undefined {
  return KITCHEN_BLOG_REGISTRY.find((e) => e.slug === slug);
}

/** Helper: get prev/next within same category (for navigation) */
export function getAdjacentKitchenBlogs(slug: string): {
  prev: KitchenBlogEntry | null;
  next: KitchenBlogEntry | null;
} {
  const entry = getKitchenBlogBySlug(slug);
  if (!entry) return { prev: null, next: null };
  const categoryPosts = getKitchenBlogsByCategory(entry.category);
  const idx = categoryPosts.findIndex((e) => e.slug === slug);
  return {
    prev: idx > 0 ? categoryPosts[idx - 1] ?? null : null,
    next: idx < categoryPosts.length - 1 ? categoryPosts[idx + 1] ?? null : null,
  };
}
