/**
 * SERVICE_REGISTRY
 *
 * Single source of truth for all services supported by the registry-first
 * programmatic SEO engine.
 *
 * Rules:
 * - Plain serialisable data only
 * - id is stable and never changes
 * - Adding a new service: add one entry here, no other structural changes needed
 */

import type { ServiceEntry } from "./types.ts";

export const SERVICE_REGISTRY: readonly ServiceEntry[] = [
  {
    id: "svc_sofa_repair",
    slug: "sofa-repair",
    name: "Sofa Repair",
    description: "Professional sofa repair including foam replacement, spring repair, fabric and leather reupholstery, and frame repair at home.",
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "sofa repair",
      "sofa repair near me",
      "sofa repair at home",
      "sofa foam replacement",
      "sofa spring repair",
      "sofa reupholstery",
    ],
    seo: {
      titleModifier: "Same-Day Sofa Repair at Home",
      metaKeywords: ["foam replacement", "spring repair"],
      synonyms: ["sofa reupholstery", "couch repair"],
      commercialTerms: ["sofa repair cost", "sofa repair price"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides same-day doorstep service, {keyword1}, {keyword2}, transparent pricing and a 6-month warranty. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
  {
    id: "svc_recliner_repair",
    slug: "recliner-repair",
    name: "Recliner Repair",
    description: "Specialist recliner repair covering motor replacement, mechanism repair, leather restoration, and foam replacement for all recliner brands.",
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "recliner repair",
      "recliner repair near me",
      "recliner motor repair",
      "recliner mechanism repair",
      "electric recliner repair",
      "recliner repair at home",
    ],
    seo: {
      titleModifier: "Electric & Manual Recliner Specialists",
      metaKeywords: ["motor repair", "mechanism repair"],
      synonyms: ["electric recliner repair", "recliner mechanism fix"],
      commercialTerms: ["recliner repair cost", "recliner repair price"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides same-day doorstep service, {keyword1}, {keyword2}, transparent pricing and a 6-month warranty. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
  {
    id: "svc_furniture_repair",
    slug: "furniture-repair",
    name: "Furniture Repair",
    description: "Comprehensive furniture repair covering sofas, recliners, wooden furniture, wardrobes, beds, and antique pieces at home.",
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "furniture repair",
      "furniture repair near me",
      "furniture repair at home",
      "wooden furniture repair",
      "sofa repair",
      "recliner repair",
    ],
    seo: {
      titleModifier: "All Furniture Repaired at Home",
      metaKeywords: ["wooden furniture repair", "sofa repair"],
      synonyms: ["home furniture repair", "carpenter service"],
      commercialTerms: ["furniture repair cost", "furniture repair price"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides same-day doorstep service, {keyword1}, {keyword2}, transparent pricing and a 6-month warranty. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
  {
    id: "svc_sofa_upholstery",
    slug: "sofa-upholstery",
    name: "Sofa Upholstery",
    description: "Full sofa reupholstery service with 300+ fabric and leather options, foam replacement, and spring repair at home.",
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "sofa upholstery",
      "sofa reupholstery",
      "sofa upholstery near me",
      "sofa fabric change",
      "sofa cover change",
      "sofa foam replacement",
    ],
    seo: {
      titleModifier: "Premium Fabric & Leather Reupholstery",
      metaKeywords: ["fabric change", "foam replacement"],
      synonyms: ["sofa fabric change", "sofa cover change"],
      commercialTerms: ["sofa upholstery cost", "sofa reupholstery price"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides same-day doorstep service, {keyword1}, {keyword2}, transparent pricing and a 6-month warranty. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
  {
    id: "svc_office_chair_repair",
    slug: "office-chair-repair",
    name: "Office Chair Repair",
    description: "Professional office chair repair for businesses, startups and co-working spaces. Gas lift, hydraulic, casters, mesh, armrest and executive chair restoration with GST billing and AMC contracts.",
    contentProfile: "office-chair-corporate",
    capabilities: {
      audience: { residential: false, corporate: true },
      business: { amc: true, bulkRepair: true, gst: true, weekendService: true },
      logistics: { emergency: false, pickupDelivery: false, onsite: true },
      content: { heroCollection: "office-chair", industryAware: true, relationshipGraph: true },
    },
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "industries:v1",
      "quick-answers:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "office chair repair",
      "office chair repair near me",
      "office chair gas lift replacement",
      "office chair hydraulic repair",
      "office chair wheel replacement",
      "corporate chair repair",
      "bulk office chair repair",
      "office chair AMC",
    ],
    seo: {
      titleModifier: "Same-Day Corporate Chair Repair | GST Invoice",
      metaKeywords: ["gas lift replacement", "bulk office chair repair"],
      synonyms: ["corporate chair repair", "ergonomic chair repair"],
      commercialTerms: ["office chair repair cost", "office chair repair price", "office chair AMC"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides on-site corporate chair repair — {keyword1}, {keyword2}, GST billing, AMC contracts. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
  {
    id: "svc_modular_kitchen",
    slug: "modular-kitchen",
    name: "Modular Kitchen",
    description: "Custom modular kitchen design, manufacturing and installation in Delhi NCR. All materials including acrylic, laminate, PU, membrane, veneer, PVC, glass and stainless steel.",
    modules: [
      "kitchen-hero:v1",
      "kitchen-locality-snapshot:v1",
      "kitchen-why-choose:v1",
      "kitchen-intro:v1",
      "kitchen-locality-stats:v1",
      "kitchen-layouts-grid:v1",
      "kitchen-materials-grid:v1",
      "kitchen-pricing:v1",
      "kitchen-comparison:v1",
      "kitchen-brands:v1",
      "kitchen-process:v1",
      "kitchen-reviews:v1",
      "kitchen-faq:v1",
      "kitchen-cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: false, // kitchen does not cross-link to repair services in Phase 1
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "modular kitchen",
      "modular kitchen Delhi",
      "modular kitchen near me",
      "modular kitchen design",
      "modular kitchen price",
      "modular kitchen installation",
    ],
    seo: {
      titleModifier: "Custom Design & Installation",
      metaKeywords: ["modular kitchen design", "modular kitchen price"],
      synonyms: ["modular kitchen installation", "kitchen renovation"],
      commercialTerms: ["modular kitchen cost", "modular kitchen price Delhi"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Looking for {serviceLower} in {locality}? {brand} offers custom modular kitchen design and installation — {keyword1}, {keyword2}, transparent pricing. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
    cityHubPattern: "/modular-kitchen-{city}",
  },
  {
    id: "svc_office_furniture_repair",
    slug: "office-furniture-repair",
    name: "Office Furniture Repair",
    description: "Professional office furniture repair for businesses — desks, workstations, conference tables, reception desks, cabinets, partitions and executive furniture. On-site service with GST billing and AMC contracts.",
    contentProfile: "office-furniture-corporate",
    capabilities: {
      audience: { residential: false, corporate: true },
      business: { amc: true, bulkRepair: true, gst: true, weekendService: true },
      logistics: { emergency: false, pickupDelivery: false, onsite: true },
      content: { heroCollection: "office-chair", industryAware: true, relationshipGraph: true },
    },
    modules: [
      "hero:v1",
      "intro:v1",
      "servicehub:v1",
      "near-me:v1",
      "pricing:v1",
      "repair-types:v1",
      "process:v1",
      "why-choose:v1",
      "services-grid:v1",
      "brands:v1",
      "material-options:v1",
      "repair-times:v1",
      "industries:v1",
      "quick-answers:v1",
      "service-coverage:v1",
      "nearby:v1",
      "faq:v1",
      "testimonials:v1",
      "comparison:v1",
      "topical-authority:v1",
      "blog-links:v1",
      "cta:v1",
      "pyramid-links:v1",
    ],
    internalLinkStrategy: {
      nearby: true,
      sameService: true,
      siblingServices: true,
      parentCluster: true,
      cityHub: true,
    },
    keywords: [
      "office furniture repair",
      "office furniture repair near me",
      "office desk repair",
      "workstation repair",
      "conference table repair",
      "reception desk repair",
      "corporate furniture repair",
      "office cabinet repair",
    ],
    seo: {
      titleModifier: "Same-Day Corporate Furniture Repair | GST Invoice",
      metaKeywords: ["office desk repair", "workstation repair"],
      synonyms: ["corporate furniture repair", "commercial furniture repair"],
      commercialTerms: ["office furniture repair cost", "office furniture repair price", "office furniture AMC"],
      titleTemplate: "{service} in {locality}, {city} | {titleModifier} | {brand}",
      metaTemplate: "Need {serviceLower} in {locality}? {brand} provides on-site corporate furniture repair — {keyword1}, {keyword2}, GST billing, AMC contracts. Call {displayPhone}.",
    },
    features: {
      luxurySection: false,
      beforeAfterGallery: false,
      reviews: true,
      pricingCalculator: false,
      aiSummary: false,
    },
  },
];