/**
 * Content Engine — Public API
 *
 * Export surface for consumers of the content engine. Only these exports
 * are considered stable public API.
 */

export { buildPageSections } from "./pipeline.ts";
export { auditPageSections } from "./seo-audit.ts";
export type { SeoAuditResult } from "./seo-audit.ts";

// Section data types
export type {
  SectionId,
  SectionData,
  PageSections,
  PageSectionData,
  HeroProps,
  HeroSectionData,
  IntroProps,
  IntroSectionData,
  ProcessProps,
  ProcessStep,
  ProcessSectionData,
  PricingProps,
  PricingItemData,
  PricingCostFactor,
  PricingSectionData,
  RepairTypesProps,
  RepairTypesSectionData,
  BrandsProps,
  BrandsSectionData,
  FaqProps,
  FaqSectionData,
  NearbyProps,
  NearbySectionData,
  NearMeProps,
  NearMeSectionData,
  PyramidLink,
  PyramidLinksProps,
  PyramidLinksSectionData,
  ServiceHubProps,
  ServiceHubSectionData,
  CtaProps,
  CtaSectionData,
  WhyChooseItem,
  WhyChooseProps,
  WhyChooseSectionData,
  ComparisonRow,
  ComparisonProps,
  ComparisonSectionData,
  TestimonialItem,
  TestimonialsProps,
  TestimonialsSectionData,
  TopicalAuthorityLink,
  TopicalAuthorityProps,
  TopicalAuthoritySectionData,
  BlogLinkItem,
  BlogLinksProps,
  BlogLinksSectionData,
  ServicesGridItem,
  ServicesGridProps,
  ServicesGridSectionData,
  MaterialGroup,
  MaterialOptionsProps,
  MaterialOptionsSectionData,
  RepairTimeItem,
  RepairTimesProps,
  RepairTimesSectionData,
  CoverageItem,
  ServiceCoverageProps,
  ServiceCoverageSectionData,
  KitchenHeroProps,
  KitchenHeroSectionData,
  KitchenIntroProps,
  KitchenIntroSectionData,
  KitchenLayoutItem,
  KitchenLayoutsGridProps,
  KitchenLayoutsGridSectionData,
  KitchenMaterialItem,
  KitchenMaterialsGridProps,
  KitchenMaterialsGridSectionData,
  KitchenPricingRow,
  KitchenPricingProps,
  KitchenPricingSectionData,
  KitchenProcessStep,
  KitchenProcessProps,
  KitchenProcessSectionData,
  KitchenFaqProps,
  KitchenFaqSectionData,
  KitchenCtaProps,
  KitchenCtaSectionData,
  KitchenWhyChooseCard,
  KitchenWhyChooseProps,
  KitchenWhyChooseSectionData,
  KitchenReviewItem,
  KitchenReviewsProps,
  KitchenReviewsSectionData,
  KitchenComparisonOption,
  KitchenComparisonRow,
  KitchenComparisonProps,
  KitchenComparisonSectionData,
  KitchenBrandCard,
  KitchenBrandsProps,
  KitchenBrandsSectionData,
  LocalityProfile,
  FaqProfileKey,
  LayoutSlug,
  MaterialSlug,
  BudgetRange,
  InstallationWindow,
  HeroVariant,
  PricingContext,
  KitchenLocalitySnapshotItem,
  KitchenLocalitySnapshotProps,
  KitchenLocalitySnapshotSectionData,
  KitchenLocalityStatsProps,
  KitchenLocalityStatsSectionData,
} from "./types.ts";

export type { PageContext } from "./content-uniqueness.ts";
