/**
 * Testimonials pool — FurniRevive
 *
 * Authentic, broadly applicable reviews.
 * Never fake locality-specific testimonials.
 * Rotate deterministically across pages using hashCode.
 */

import type { TestimonialItem } from "./types.ts";

export const TESTIMONIALS_POOL: TestimonialItem[] = [
  {
    name: "Priya Sharma",
    location: "Delhi",
    rating: 5,
    text: "Technician arrived within 2 hours. Fixed our sagging L-shaped sofa — foam replaced and frame tightened. Looks and feels like new. Very professional.",
    service: "Sofa Repair",
    datePublished: "2024-10-12",
  },
  {
    name: "Rohit Verma",
    location: "Delhi NCR",
    rating: 5,
    text: "Recliner motor had stopped working for 3 months. They diagnosed it in 20 minutes, replaced the motor on the same visit. Excellent service.",
    service: "Recliner Repair",
    datePublished: "2024-11-03",
  },
  {
    name: "Anita Kapoor",
    location: "Delhi",
    rating: 5,
    text: "Got the sofa reupholstered with a new fabric. They brought swatches to my home, I chose on the spot. Work was done in 1.5 days, very neat finish.",
    service: "Sofa Upholstery",
    datePublished: "2024-09-28",
  },
  {
    name: "Suresh Gupta",
    location: "Delhi",
    rating: 5,
    text: "Dining chairs and a wooden cabinet repaired in a single visit. The carpenter was skilled and honest about what needed repair vs what was fine. Transparent pricing.",
    service: "Furniture Repair",
    datePublished: "2024-12-01",
  },
  {
    name: "Meena Joshi",
    location: "Delhi NCR",
    rating: 5,
    text: "Free inspection first — they told me exactly what was wrong and the cost before starting. No hidden charges. Sofa spring and foam fixed same day.",
    service: "Sofa Repair",
    datePublished: "2024-10-20",
  },
  {
    name: "Vikram Singh",
    location: "Delhi",
    rating: 5,
    text: "My leather recliner was peeling badly. They repaired and polished the leather — looks much better. 6-month warranty gives peace of mind. Highly recommend.",
    service: "Recliner Repair",
    datePublished: "2024-11-18",
  },
  {
    name: "Kavita Nair",
    location: "Delhi",
    rating: 5,
    text: "Changed fabric on 3-seater and 2-seater both. They matched the color perfectly to my room. Doorstep service, no pickup needed. Very satisfied.",
    service: "Sofa Upholstery",
    datePublished: "2025-01-05",
  },
  {
    name: "Arun Malhotra",
    location: "Delhi NCR",
    rating: 5,
    text: "Sofa frame was cracked at the leg joint. Fixed it completely, foam replaced too. Technician was courteous and careful with the flooring. Will use again.",
    service: "Sofa Repair",
    datePublished: "2024-12-14",
  },
  {
    name: "Deepa Krishnan",
    location: "Delhi",
    rating: 4,
    text: "Good service overall. Recliner mechanism repaired. Took slightly longer than quoted but the quality of repair is excellent and the warranty covers it.",
    service: "Recliner Repair",
    datePublished: "2024-11-29",
  },
  {
    name: "Rajesh Yadav",
    location: "Delhi NCR",
    rating: 5,
    text: "Wardrobes, bed frame, and a dining table all fixed in one day by two technicians. Very efficient. Would recommend FurniRevive for all furniture repairs.",
    service: "Furniture Repair",
    datePublished: "2025-01-20",
  },
  {
    name: "Sunita Arora",
    location: "Delhi",
    rating: 5,
    text: "Old sofa had torn arms and sunk cushions. They replaced the foam and stitched the arms back. Now it's as good as a new sofa for a fraction of the price.",
    service: "Sofa Repair",
    datePublished: "2024-10-05",
  },
  {
    name: "Manish Bhatia",
    location: "Delhi NCR",
    rating: 5,
    text: "Electric recliner wasn't reclining. They replaced the actuator motor on the spot. Quick, clean, no mess. The technician even tested it multiple times before leaving.",
    service: "Recliner Repair",
    datePublished: "2025-02-10",
  },
  {
    name: "Rajat Mehra",
    location: "Cyber City, Gurgaon",
    rating: 5,
    text: "Had 35 office chairs with sinking gas lifts. FurniRevive sent two technicians to our Cyber City office and fixed all of them in one day. GST invoice raised same evening. Excellent bulk service.",
    service: "Office Chair Repair",
    datePublished: "2025-03-08",
  },
  {
    name: "Nisha Aggarwal",
    location: "Nehru Place, Delhi",
    rating: 5,
    text: "Our executive leather chairs were scuffed and the armrests had torn foam. Repaired on-site at our Nehru Place office within 3 hours. Professional team, no disruption to work.",
    service: "Office Chair Repair",
    datePublished: "2025-02-14",
  },
  {
    name: "Sanjay Khanna",
    location: "Film City, Noida",
    rating: 5,
    text: "Production studio chairs take a beating. FurniRevive repaired 20 chairs in one visit — caster wheels, gas lifts, and armrests. They carry all parts. Booked via WhatsApp and they were here next morning.",
    service: "Office Chair Repair",
    datePublished: "2025-04-01",
  },
  {
    name: "Pooja Tiwari",
    location: "Noida Sector 62",
    rating: 5,
    text: "Signed an AMC for our 50-chair office. Quarterly inspections keep everything running. When a hydraulic cylinder failed between visits, they responded in under 2 hours. Worth every rupee.",
    service: "Office Chair Repair",
    datePublished: "2025-03-22",
  },
  {
    name: "Amit Saxena",
    location: "Udyog Vihar, Gurgaon",
    rating: 5,
    text: "Mesh back panel on 12 ergonomic chairs had started sagging. All replaced on-site. Technician explained what caused it and how to maintain them. Very knowledgeable. GST invoice within 24 hours.",
    service: "Office Chair Repair",
    datePublished: "2025-01-30",
  },
  {
    name: "Kavya Reddy",
    location: "Jasola, Delhi",
    rating: 5,
    text: "Free inspection first — they identified which chairs needed repair and which were fine. No upselling. Fixed 8 chairs on the spot. Transparent pricing, proper tax invoice. Will use FurniRevive for all our office maintenance.",
    service: "Office Chair Repair",
    datePublished: "2025-02-28",
  },
  {
    name: "Mohit Chadha",
    location: "Aerocity, Delhi",
    rating: 5,
    text: "Luxury executive chairs in our boardroom had peeling leather on armrests. Repaired and re-padded to match original. Looks brand new. Quick turnaround, completely on-site. Highly recommend.",
    service: "Office Chair Repair",
    datePublished: "2025-04-10",
  },
  {
    name: "Prerna Verma",
    location: "Electronic City, Noida",
    rating: 5,
    text: "Our BPO has 120 chairs. FurniRevive handles our quarterly maintenance under AMC. Response time is excellent, bulk pricing is fair, and they always bring adequate stock. Saved us significant capex on new chairs.",
    service: "Office Chair Repair",
    datePublished: "2025-03-15",
  },
  {
    name: "Vikram Mehta",
    location: "Connaught Place, Delhi",
    rating: 5,
    text: "Our conference table had deep scratches and a wobbly leg. FurniRevive repaired and polished it on-site — looks brand new. No need to buy a replacement. GST invoice received same day.",
    service: "Office Furniture Repair",
    datePublished: "2025-04-18",
  },
  {
    name: "Ananya Desai",
    location: "Sector 44, Gurgaon",
    rating: 5,
    text: "Reception desk veneer was peeling and the counter had water damage. Technician restored it completely in one visit. Very professional, minimal disruption to our front office operations.",
    service: "Office Furniture Repair",
    datePublished: "2025-05-02",
  },
  {
    name: "Rakesh Tandon",
    location: "Noida Sector 18",
    rating: 5,
    text: "Had 25 modular workstations with broken keyboard trays and loose panels. FurniRevive fixed all of them in a single day. Bulk pricing was very reasonable. Procurement Head, XYZ Corp.",
    service: "Office Furniture Repair",
    datePublished: "2025-04-25",
  },
  {
    name: "Shalini Kapoor",
    location: "Jasola, Delhi",
    rating: 5,
    text: "Office cabinets had stuck drawers and broken locks. Technician replaced all hardware and realigned the frames. Quick turnaround, proper invoice. Office Manager, ABC Ltd.",
    service: "Office Furniture Repair",
    datePublished: "2025-05-10",
  },
  {
    name: "Arjun Sethi",
    location: "DLF Phase 3, Gurgaon",
    rating: 5,
    text: "Executive desks in our MD's cabin and CFO's office had scratched surfaces and wobbly joints. Repaired on-site without moving anything. Quality work, would recommend for any corporate office. Facilities Head, TechNova Solutions.",
    service: "Office Furniture Repair",
    datePublished: "2025-05-15",
  },
  {
    name: "Megha Sharma",
    location: "Okhla Industrial Area, Delhi",
    rating: 5,
    text: "Signed an AMC for our entire office furniture — desks, tables, and storage units. Quarterly inspections have kept everything in top shape. Response time for urgent repairs is under 2 hours. Admin Manager, GlobalServe Pvt Ltd.",
    service: "Office Furniture Repair",
    datePublished: "2025-05-20",
  },
];
