/**
 * Hero Image Registry — FurniRevive SEO
 * v1 public contract — all exported types are frozen.
 * Future breaking changes ship as v2.
 *
 * Architecture rules:
 * - Keyed by stable ID (e.g. "hero-sofa-001")
 * - ID must also be stored as the `id` field inside the record
 * - Data only — no generated strings, no alt text, no captions (those live in hero-image-engine.ts)
 * - HERO_MATCH_WEIGHTS is the single source of truth for all scoring constants
 * - HeroScene metadata is for library management only — not consumed by the Hero Engine
 *
 * Matching logic lives in hero-image-engine.ts.
 * SeoServiceKey is derived from service-config.ts.
 */

import type { SeoServiceKey } from "./service-config.ts";

// ─── Core enumerations ───────────────────────────────────────────────────────

export type HeroStyle =
  | "modern"
  | "luxury"
  | "traditional"
  | "minimal"
  | "contemporary";

export type HeroRoomType =
  | "living-room"
  | "office"
  | "bedroom"
  | "lobby";

export type HeroOrientation =
  | "landscape"
  | "portrait"
  | "square";

// ─── Scene metadata ──────────────────────────────────────────────────────────

export type HeroScene = {
  windowPlacement: "left" | "right" | "behind" | "hidden";
  furniturePosition: "left" | "center" | "right";
  flooring: "wood" | "herringbone" | "marble" | "parquet";
  coffeeTable: "modern" | "round" | "rectangular" | "none";
  plantType: "tall" | "small" | "hanging" | "none";
  wallTreatment: "plain" | "texture" | "art" | "none";
};

// ─── Coverage reporting ──────────────────────────────────────────────────────

export type CoverageReport = {
  [K in keyof HeroScene]: Record<string, number>;
};

// ─── Validation ──────────────────────────────────────────────────────────────

export type ValidationCode =
  | "DUPLICATE_ID"
  | "DUPLICATE_FILE_ID"
  | "DUPLICATE_URL"
  | "MISSING_FIELD"
  | "INVALID_SCENE_VALUE"
  | "INVALID_DIMENSIONS"
  | "INVALID_VERSION"
  | "INVALID_STATUS"
  | "INVALID_PRIORITY";

export type ValidationIssue = {
  severity: "error" | "warning";
  code: ValidationCode;
  heroId?: string;
  message: string;
};

export type ValidationResult = {
  valid: boolean;
  errors: ValidationIssue[];
  warnings: ValidationIssue[];
};

// ─── Hero image record ───────────────────────────────────────────────────────

export type HeroImageRecord = {
  // ── Identity ────────────────────────────────────────────────────────────────
  /** Stable ID — also stored as the registry key */
  id: string;
  /** Hercules CDN file ID (without URL prefix) e.g. "file_abc123" */
  fileId: string;
  /** Permanent Hercules CDN URL e.g. "https://hercules-cdn.com/file_abc123" */
  url: string;

  // ── Image metadata ──────────────────────────────────────────────────────────
  /** Actual pixel width of the generated image */
  width: number;
  /** Actual pixel height of the generated image */
  height: number;
  /** Increments on replacement — starts at 1 */
  version: number;
  /** ISO date string e.g. "2026-07-18" */
  createdAt: string;
  status: "approved" | "pending-replacement";

  // ── Hero Engine selection ───────────────────────────────────────────────────
  services: SeoServiceKey[];
  /** e.g. "sofa" | "recliner" | "chair" | "sectional" | "armchair" */
  furnitureType: string;
  colors: string[];
  style: HeroStyle;
  roomType: HeroRoomType;
  cityKeys: string[];
  /** Exact locality slugs for highest-priority matching */
  localitySlugs: string[];
  isPremium: boolean;
  orientation: HeroOrientation;
  /** Tie-breaker within same score — lower = higher priority */
  priority: number;
  /** Free-text tags for future filtering e.g. ["fabric", "3-seater", "l-shape"] */
  tags?: string[];

  // ── Scene metadata (library management only — not used by Hero Engine) ──────
  scene: HeroScene;
};

// ─── Scoring weights (single source of truth) ─────────────────────────────────

export const HERO_MATCH_WEIGHTS = {
  locality: 50,
  city: 30,
  service: 25,
  premium: 20,
  style: 10,
  furniture: 10,
} as const;

// ─── Registry ─────────────────────────────────────────────────────────────────

export const HERO_IMAGE_REGISTRY: Record<string, HeroImageRecord> = {
  "hero-001": {
    // Identity
    id: "hero-001",
    fileId: "file_8T0Sia8eEy84c89hCH42o2pT",
    url: "https://hercules-cdn.com/file_8T0Sia8eEy84c89hCH42o2pT",
    // Image metadata
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    // Hero Engine selection
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["grey", "light-grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 1,
    tags: ["fabric", "3-seater", "performance-fabric", "golden-master"],
    // Scene metadata
    scene: {
      windowPlacement: "left",
      furniturePosition: "center",
      flooring: "wood",
      coffeeTable: "none",
      plantType: "small",
      wallTreatment: "plain",
    },
  },
  "hero-002": {
    // Identity
    id: "hero-002",
    fileId: "file_r3TLOe767PyrLLyDgssn6CLp",
    url: "https://hercules-cdn.com/file_r3TLOe767PyrLLyDgssn6CLp",
    // Image metadata
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    // Hero Engine selection
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["beige", "warm-beige"],
    style: "traditional",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 2,
    tags: ["linen", "3-seater", "warm-tones", "morning-light"],
    // Scene metadata
    scene: {
      windowPlacement: "right",
      furniturePosition: "center",
      flooring: "herringbone",
      coffeeTable: "none",
      plantType: "small",
      wallTreatment: "art",
    },
  },
  "hero-003": {
    // Identity
    id: "hero-003",
    fileId: "file_mwiVcnJu94eX0OBI2Aw449dh",
    url: "https://hercules-cdn.com/file_mwiVcnJu94eX0OBI2Aw449dh",
    // Image metadata
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    // Hero Engine selection
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["charcoal", "dark-grey"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 3,
    tags: ["microfiber", "3-seater", "tufted", "backlit"],
    // Scene metadata
    scene: {
      windowPlacement: "behind",
      furniturePosition: "left",
      flooring: "parquet",
      coffeeTable: "round",
      plantType: "none",
      wallTreatment: "plain",
    },
  },
  "hero-004": {
    // Identity
    id: "hero-004",
    fileId: "file_fi5GCY8nIPTHKUcO5ZemMeSw",
    url: "https://hercules-cdn.com/file_fi5GCY8nIPTHKUcO5ZemMeSw",
    // Image metadata
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    // Hero Engine selection
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["navy", "deep-blue"],
    style: "luxury",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: true,
    orientation: "landscape",
    priority: 4,
    tags: ["velvet", "3-seater", "marble-floor", "ambient-lighting"],
    // Scene metadata
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "right",
      flooring: "marble",
      coffeeTable: "rectangular",
      plantType: "tall",
      wallTreatment: "texture",
    },
  },
  "hero-005": {
    // Identity
    id: "hero-005",
    fileId: "file_ZPlUw0Ncrg3gU2FIBIrFM2wP",
    url: "https://hercules-cdn.com/file_ZPlUw0Ncrg3gU2FIBIrFM2wP",
    // Image metadata
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    // Hero Engine selection
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["cream", "ivory", "off-white"],
    style: "minimal",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 5,
    tags: ["boucle", "3-seater", "airy", "bright"],
    // Scene metadata
    scene: {
      windowPlacement: "left",
      furniturePosition: "center",
      flooring: "wood",
      coffeeTable: "modern",
      plantType: "hanging",
      wallTreatment: "plain",
    },
  },
  "hero-006": {
    id: "hero-006",
    fileId: "file_iXkb4nv5Rvy7HFRQEqlr8yjn",
    url: "https://hercules-cdn.com/file_iXkb4nv5Rvy7HFRQEqlr8yjn",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["sand", "tan"],
    style: "traditional",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 6,
    tags: ["suede-look", "3-seater", "warm-earthy", "right-window"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "right",
      flooring: "herringbone",
      coffeeTable: "rectangular",
      plantType: "tall",
      wallTreatment: "art",
    },
  },
  "hero-007": {
    id: "hero-007",
    fileId: "file_h50r74FBo4vk9WBP3vADMSTg",
    url: "https://hercules-cdn.com/file_h50r74FBo4vk9WBP3vADMSTg",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["grey", "stone-grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 7,
    tags: ["fabric", "l-shaped", "sectional", "backlit", "open-plan"],
    scene: {
      windowPlacement: "behind",
      furniturePosition: "left",
      flooring: "parquet",
      coffeeTable: "round",
      plantType: "small",
      wallTreatment: "plain",
    },
  },
  "hero-008": {
    id: "hero-008",
    fileId: "file_AZZ7NCkVm7ww9Rg15YQR8Hxe",
    url: "https://hercules-cdn.com/file_AZZ7NCkVm7ww9Rg15YQR8Hxe",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["beige", "warm-beige"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 8,
    tags: ["performance-fabric", "l-shaped", "sectional", "ambient-lighting"],
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "right",
      flooring: "parquet",
      coffeeTable: "none",
      plantType: "hanging",
      wallTreatment: "texture",
    },
  },
  "hero-009": {
    id: "hero-009",
    fileId: "file_CXYZClWznTqS6k9DpGhhfQ0O",
    url: "https://hercules-cdn.com/file_CXYZClWznTqS6k9DpGhhfQ0O",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["charcoal", "dark-grey"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 9,
    tags: ["microfiber", "l-shaped", "sectional", "right-window", "herringbone"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "right",
      flooring: "herringbone",
      coffeeTable: "modern",
      plantType: "none",
      wallTreatment: "art",
    },
  },
  "hero-010": {
    id: "hero-010",
    fileId: "file_JMBMH9RZS7zNggSI5DB1aXN6",
    url: "https://hercules-cdn.com/file_JMBMH9RZS7zNggSI5DB1aXN6",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["stone-grey", "grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 10,
    tags: ["performance-fabric", "u-shaped", "modular", "sectional", "left-window"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "center",
      flooring: "parquet",
      coffeeTable: "round",
      plantType: "tall",
      wallTreatment: "texture",
    },
  },
  "hero-011": {
    id: "hero-011",
    fileId: "file_PeDceYWnzWF50RV44SkAiuGV",
    url: "https://hercules-cdn.com/file_PeDceYWnzWF50RV44SkAiuGV",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["ivory", "white"],
    style: "minimal",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 1,
    tags: ["u-shaped", "sectional", "marble-floor", "backlit", "minimal"],
    scene: {
      windowPlacement: "behind",
      furniturePosition: "center",
      flooring: "marble",
      coffeeTable: "none",
      plantType: "none",
      wallTreatment: "plain",
    },
  },
  "hero-012": {
    id: "hero-012",
    fileId: "file_kM72gxLoWMXXlFGiuY8WtL7e",
    url: "https://hercules-cdn.com/file_kM72gxLoWMXXlFGiuY8WtL7e",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["dusty-pink", "pink"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 2,
    tags: ["velvet", "2-seater", "compact", "right-window"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "left",
      flooring: "herringbone",
      coffeeTable: "rectangular",
      plantType: "none",
      wallTreatment: "plain",
    },
  },
  "hero-013": {
    id: "hero-013",
    fileId: "file_q8iwoSTcJ9pNJfc4T3lJ26oQ",
    url: "https://hercules-cdn.com/file_q8iwoSTcJ9pNJfc4T3lJ26oQ",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa",
    colors: ["tan", "caramel"],
    style: "minimal",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 3,
    tags: ["leather", "2-seater", "compact", "marble-floor", "ambient"],
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "right",
      flooring: "marble",
      coffeeTable: "round",
      plantType: "hanging",
      wallTreatment: "plain",
    },
  },
  "hero-014": {
    id: "hero-014",
    fileId: "file_CB4sp0PLZqP8fsLBM9YLoVWe",
    url: "https://hercules-cdn.com/file_CB4sp0PLZqP8fsLBM9YLoVWe",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 4,
    tags: ["fabric", "sofa-cum-bed", "guest-room", "left-window"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "left",
      flooring: "parquet",
      coffeeTable: "none",
      plantType: "small",
      wallTreatment: "plain",
    },
  },
  "hero-015": {
    id: "hero-015",
    fileId: "file_WkjkRoldRdUcC7YBsB2fUf5D",
    url: "https://hercules-cdn.com/file_WkjkRoldRdUcC7YBsB2fUf5D",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["beige", "warm-beige"],
    style: "modern",
    roomType: "bedroom",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 5,
    tags: ["microfiber", "sofa-cum-bed", "guest-room", "right-window"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "center",
      flooring: "wood",
      coffeeTable: "rectangular",
      plantType: "tall",
      wallTreatment: "art",
    },
  },
  "hero-016": {
    id: "hero-016",
    fileId: "file_7iC0MuM3Q40dcGRQ1BMd1txL",
    url: "https://hercules-cdn.com/file_7iC0MuM3Q40dcGRQ1BMd1txL",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["teal"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 6,
    tags: ["velvet", "curved", "round-arms", "teal", "accent-wall"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "right",
      flooring: "parquet",
      coffeeTable: "none",
      plantType: "none",
      wallTreatment: "texture",
    },
  },
  "hero-017": {
    id: "hero-017",
    fileId: "file_xuttkRALt8CRaKC1KArcxNpX",
    url: "https://hercules-cdn.com/file_xuttkRALt8CRaKC1KArcxNpX",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["blush", "pink"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 7,
    tags: ["fabric", "curved", "blush", "marble-floor", "backlit"],
    scene: {
      windowPlacement: "behind",
      furniturePosition: "center",
      flooring: "marble",
      coffeeTable: "round",
      plantType: "tall",
      wallTreatment: "plain",
    },
  },
  "hero-018": {
    id: "hero-018",
    fileId: "file_fmFu2XloSLvsizN4UP7dlYkP",
    url: "https://hercules-cdn.com/file_fmFu2XloSLvsizN4UP7dlYkP",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["olive", "green"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 8,
    tags: ["performance-fabric", "modular", "olive", "ambient", "herringbone"],
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "left",
      flooring: "herringbone",
      coffeeTable: "modern",
      plantType: "hanging",
      wallTreatment: "art",
    },
  },
  "hero-019": {
    id: "hero-019",
    fileId: "file_KBx8BPWYqqo20zWisahYMmsS",
    url: "https://hercules-cdn.com/file_KBx8BPWYqqo20zWisahYMmsS",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa",
    colors: ["graphite", "dark-grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 9,
    tags: ["fabric", "modular", "graphite", "right-window", "greenery"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "right",
      flooring: "wood",
      coffeeTable: "rectangular",
      plantType: "small",
      wallTreatment: "plain",
    },
  },
  "hero-020": {
    id: "hero-020",
    fileId: "file_OiaWp9je5TEk9zEfXrMFrhZ3",
    url: "https://hercules-cdn.com/file_OiaWp9je5TEk9zEfXrMFrhZ3",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa",
    colors: ["tan", "caramel"],
    style: "traditional",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 10,
    tags: ["leather", "chesterfield", "tufted", "tan", "herringbone"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "center",
      flooring: "herringbone",
      coffeeTable: "none",
      plantType: "tall",
      wallTreatment: "plain",
    },
  },
  "hero-021": {
    id: "hero-021",
    fileId: "file_2c8bbpkuu9qh7mm9w7sbecpE",
    url: "https://hercules-cdn.com/file_2c8bbpkuu9qh7mm9w7sbecpE",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["brown"],
    style: "traditional",
    roomType: "office",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 1,
    tags: ["leather", "single", "manual", "study", "bookshelf"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "center",
      flooring: "wood",
      coffeeTable: "none",
      plantType: "small",
      wallTreatment: "plain",
    },
  },
  "hero-022": {
    id: "hero-022",
    fileId: "file_ub0pWPST2CGWHI5oeuriRwot",
    url: "https://hercules-cdn.com/file_ub0pWPST2CGWHI5oeuriRwot",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 2,
    tags: ["fabric", "2-seater", "home-theatre", "ambient", "parquet"],
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "right",
      flooring: "parquet",
      coffeeTable: "none",
      plantType: "none",
      wallTreatment: "plain",
    },
  },
  "hero-023": {
    id: "hero-023",
    fileId: "file_ZLNLI6MDQ4ghQjASGH3dBaX5",
    url: "https://hercules-cdn.com/file_ZLNLI6MDQ4ghQjASGH3dBaX5",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner",
    colors: ["black"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 3,
    tags: ["leather", "power", "extended", "right-window", "herringbone"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "left",
      flooring: "herringbone",
      coffeeTable: "rectangular",
      plantType: "tall",
      wallTreatment: "plain",
    },
  },
  "hero-024": {
    id: "hero-024",
    fileId: "file_wZmJAOb8LGQoqpS2oLS2SuE6",
    url: "https://hercules-cdn.com/file_wZmJAOb8LGQoqpS2oLS2SuE6",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner",
    colors: ["caramel", "tan"],
    style: "traditional",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 4,
    tags: ["leather", "3-seater", "backlit", "marble", "round-table"],
    scene: {
      windowPlacement: "behind",
      furniturePosition: "center",
      flooring: "marble",
      coffeeTable: "round",
      plantType: "hanging",
      wallTreatment: "plain",
    },
  },
  "hero-025": {
    id: "hero-025",
    fileId: "file_LOHAKGqtU1iWl0Py1MTUfn3g",
    url: "https://hercules-cdn.com/file_LOHAKGqtU1iWl0Py1MTUfn3g",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["cream", "ivory"],
    style: "minimal",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 5,
    tags: ["boucle", "armchair", "reading-nook", "left-window", "art"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "right",
      flooring: "wood",
      coffeeTable: "none",
      plantType: "small",
      wallTreatment: "art",
    },
  },
  "hero-026": {
    id: "hero-026",
    fileId: "file_6mQVVHWzhLGFBUtlMo427ddI",
    url: "https://hercules-cdn.com/file_6mQVVHWzhLGFBUtlMo427ddI",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner",
    colors: ["espresso", "dark-brown"],
    style: "luxury",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 6,
    tags: ["leather", "3-seater", "media-room", "ambient", "herringbone"],
    scene: {
      windowPlacement: "hidden",
      furniturePosition: "left",
      flooring: "herringbone",
      coffeeTable: "none",
      plantType: "none",
      wallTreatment: "texture",
    },
  },
  "hero-027": {
    id: "hero-027",
    fileId: "file_aVs15jYD5zLvHeYxUm1KJI78",
    url: "https://hercules-cdn.com/file_aVs15jYD5zLvHeYxUm1KJI78",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["cognac", "tan"],
    style: "traditional",
    roomType: "office",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 7,
    tags: ["suede-look", "single", "library", "right-window", "books"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "right",
      flooring: "wood",
      coffeeTable: "none",
      plantType: "tall",
      wallTreatment: "art",
    },
  },
  "hero-028": {
    id: "hero-028",
    fileId: "file_Xle4Vjxln6X4DpXZnCy0Eh6Y",
    url: "https://hercules-cdn.com/file_Xle4Vjxln6X4DpXZnCy0Eh6Y",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["charcoal"],
    style: "contemporary",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 8,
    tags: ["performance-fabric", "power", "backlit", "parquet", "hanging-plant"],
    scene: {
      windowPlacement: "behind",
      furniturePosition: "center",
      flooring: "parquet",
      coffeeTable: "rectangular",
      plantType: "hanging",
      wallTreatment: "plain",
    },
  },
  "hero-029": {
    id: "hero-029",
    fileId: "file_5TofBFq0ySIYgCKJ9kmfN2pA",
    url: "https://hercules-cdn.com/file_5TofBFq0ySIYgCKJ9kmfN2pA",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["navy", "blue"],
    style: "modern",
    roomType: "office",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 9,
    tags: ["fabric", "single", "home-office", "left-window", "marble"],
    scene: {
      windowPlacement: "left",
      furniturePosition: "left",
      flooring: "marble",
      coffeeTable: "round",
      plantType: "small",
      wallTreatment: "texture",
    },
  },
  "hero-030": {
    id: "hero-030",
    fileId: "file_fGcxhq64pVdDdng3O6NFBxga",
    url: "https://hercules-cdn.com/file_fGcxhq64pVdDdng3O6NFBxga",
    width: 1792,
    height: 1024,
    version: 1,
    createdAt: "2026-07-18",
    status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner",
    colors: ["stone-grey"],
    style: "modern",
    roomType: "living-room",
    cityKeys: [],
    localitySlugs: [],
    isPremium: false,
    orientation: "landscape",
    priority: 10,
    tags: ["microfiber", "2-seater", "manual", "right-window", "herringbone"],
    scene: {
      windowPlacement: "right",
      furniturePosition: "right",
      flooring: "herringbone",
      coffeeTable: "none",
      plantType: "tall",
      wallTreatment: "plain",
    },
  },
  "hero-031": {
    id: "hero-031",
    fileId: "file_SkQRYzIVvyqVJZeutqrjLNvq",
    url: "https://hercules-cdn.com/file_SkQRYzIVvyqVJZeutqrjLNvq",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner", colors: ["wine-red", "burgundy"], style: "luxury",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 1,
    tags: ["leather", "single", "den", "amber-lighting", "wood-shelving"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "small", wallTreatment: "plain" },
  },
  "hero-032": {
    id: "hero-032",
    fileId: "file_rTT31wfskKXSyO7ZFElOrvBj",
    url: "https://hercules-cdn.com/file_rTT31wfskKXSyO7ZFElOrvBj",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["beige", "light-beige"], style: "modern",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 2,
    tags: ["fabric", "3-seater", "backlit", "parquet", "green-view"],
    scene: { windowPlacement: "behind", furniturePosition: "left", flooring: "parquet", coffeeTable: "rectangular", plantType: "hanging", wallTreatment: "art" },
  },
  "hero-033": {
    id: "hero-033",
    fileId: "file_aBp3FCt5ONomYAQCbGGstiTe",
    url: "https://hercules-cdn.com/file_aBp3FCt5ONomYAQCbGGstiTe",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["white", "off-white"], style: "minimal",
    roomType: "bedroom", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 3,
    tags: ["performance-fabric", "electric", "left-window", "marble", "pastel"],
    scene: { windowPlacement: "left", furniturePosition: "right", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "texture" },
  },
  "hero-034": {
    id: "hero-034",
    fileId: "file_ZtkYJF9gTW5jeNOoFgHNeHPg",
    url: "https://hercules-cdn.com/file_ZtkYJF9gTW5jeNOoFgHNeHPg",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner", colors: ["chocolate", "dark-brown"], style: "traditional",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 4,
    tags: ["leather", "3+1-set", "ambient", "herringbone", "persian-rug"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "herringbone", coffeeTable: "round", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-035": {
    id: "hero-035",
    fileId: "file_cZaDEmeWmhXwbcwKnOJ4yWUl",
    url: "https://hercules-cdn.com/file_cZaDEmeWmhXwbcwKnOJ4yWUl",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["grey", "soft-grey"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 5,
    tags: ["fabric", "modular", "right-window", "wood", "panoramic"],
    scene: { windowPlacement: "right", furniturePosition: "right", flooring: "wood", coffeeTable: "modern", plantType: "small", wallTreatment: "texture" },
  },
  "hero-036": {
    id: "hero-036",
    fileId: "file_QzTVclKVHG8tn8GWdCl51CpC",
    url: "https://hercules-cdn.com/file_QzTVclKVHG8tn8GWdCl51CpC",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair"],
    furnitureType: "chair", colors: ["black"], style: "modern",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 1,
    tags: ["mesh", "executive", "home-office", "backlit", "wood"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "small", wallTreatment: "plain" },
  },
  "hero-037": {
    id: "hero-037",
    fileId: "file_dLYGoeGofdS8ywrcQ2EaBpKr",
    url: "https://hercules-cdn.com/file_dLYGoeGofdS8ywrcQ2EaBpKr",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "leather-sofa-repair"],
    furnitureType: "chair", colors: ["brown"], style: "traditional",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 2,
    tags: ["leather", "high-back", "executive", "left-window", "herringbone"],
    scene: { windowPlacement: "left", furniturePosition: "right", flooring: "herringbone", coffeeTable: "none", plantType: "none", wallTreatment: "art" },
  },
  "hero-038": {
    id: "hero-038",
    fileId: "file_2e1C8FiW90dJjziZQtXy1RwA",
    url: "https://hercules-cdn.com/file_2e1C8FiW90dJjziZQtXy1RwA",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair"],
    furnitureType: "chair", colors: ["grey"], style: "modern",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 3,
    tags: ["ergonomic", "fabric", "right-window", "parquet", "natural-light"],
    scene: { windowPlacement: "right", furniturePosition: "left", flooring: "parquet", coffeeTable: "none", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-039": {
    id: "hero-039",
    fileId: "file_GirDwqB6tx5XzI0HIBiLx93Y",
    url: "https://hercules-cdn.com/file_GirDwqB6tx5XzI0HIBiLx93Y",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["navy", "deep-blue"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 4,
    tags: ["velvet", "armchair", "ambient", "marble", "hanging-plant"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "hanging", wallTreatment: "texture" },
  },
  "hero-040": {
    id: "hero-040",
    fileId: "file_ZchACyqhPEH9S0dDDdyImv98",
    url: "https://hercules-cdn.com/file_ZchACyqhPEH9S0dDDdyImv98",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "leather-sofa-repair"],
    furnitureType: "chair", colors: ["cream", "ivory"], style: "traditional",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 5,
    tags: ["leather", "wingback", "left-window", "herringbone", "art"],
    scene: { windowPlacement: "left", furniturePosition: "right", flooring: "herringbone", coffeeTable: "round", plantType: "small", wallTreatment: "art" },
  },
  "hero-041": {
    id: "hero-041",
    fileId: "file_9x9gVc5CxGLPfqodZgjUtrvE",
    url: "https://hercules-cdn.com/file_9x9gVc5CxGLPfqodZgjUtrvE",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "leather-sofa-repair"],
    furnitureType: "chair", colors: ["caramel", "tan"], style: "modern",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 6,
    tags: ["leather", "visitor", "pair", "backlit", "parquet"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "parquet", coffeeTable: "none", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-042": {
    id: "hero-042",
    fileId: "file_pCao0kYxEGl4kcskgf08gkpB",
    url: "https://hercules-cdn.com/file_pCao0kYxEGl4kcskgf08gkpB",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["teal"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 7,
    tags: ["velvet", "accent", "right-window", "wood", "geometric-rug"],
    scene: { windowPlacement: "right", furniturePosition: "left", flooring: "wood", coffeeTable: "none", plantType: "small", wallTreatment: "plain" },
  },
  "hero-043": {
    id: "hero-043",
    fileId: "file_10gk0fSRtdRF6aZr0JIjAN6E",
    url: "https://hercules-cdn.com/file_10gk0fSRtdRF6aZr0JIjAN6E",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["grey"], style: "modern",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 8,
    tags: ["fabric", "dining", "single", "ambient", "marble"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "texture" },
  },
  "hero-044": {
    id: "hero-044",
    fileId: "file_VnyaYGRgCJba3TuBJYhh6NhX",
    url: "https://hercules-cdn.com/file_VnyaYGRgCJba3TuBJYhh6NhX",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["light-grey", "grey"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 9,
    tags: ["fabric", "dining", "set-of-4", "left-window", "herringbone"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "herringbone", coffeeTable: "none", plantType: "hanging", wallTreatment: "plain" },
  },
  "hero-045": {
    id: "hero-045",
    fileId: "file_sf3kODJq3FrGS5UOXR2wC2jn",
    url: "https://hercules-cdn.com/file_sf3kODJq3FrGS5UOXR2wC2jn",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "leather-sofa-repair"],
    furnitureType: "chair", colors: ["black"], style: "minimal",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 10,
    tags: ["leather", "lounge", "ottoman", "right-window", "wood"],
    scene: { windowPlacement: "right", furniturePosition: "right", flooring: "wood", coffeeTable: "none", plantType: "small", wallTreatment: "plain" },
  },
  "hero-046": {
    id: "hero-046",
    fileId: "file_Ea0LS6AaKmNVLA3PugTXLCii",
    url: "https://hercules-cdn.com/file_Ea0LS6AaKmNVLA3PugTXLCii",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["emerald", "green"], style: "luxury",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 1,
    tags: ["velvet", "accent", "backlit", "parquet", "gold-lamp"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "parquet", coffeeTable: "none", plantType: "tall", wallTreatment: "texture" },
  },
  "hero-047": {
    id: "hero-047",
    fileId: "file_cM93pR1fu4dF3r9FjqRuWvND",
    url: "https://hercules-cdn.com/file_cM93pR1fu4dF3r9FjqRuWvND",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["natural", "beige"], style: "minimal",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 2,
    tags: ["rattan", "cushioned", "left-window", "marble", "hanging-plant"],
    scene: { windowPlacement: "left", furniturePosition: "left", flooring: "marble", coffeeTable: "none", plantType: "hanging", wallTreatment: "plain" },
  },
  "hero-048": {
    id: "hero-048",
    fileId: "file_77VGqaUhrLswtGPGb6ceFoK4",
    url: "https://hercules-cdn.com/file_77VGqaUhrLswtGPGb6ceFoK4",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "leather-sofa-repair"],
    furnitureType: "chair", colors: ["tan", "saddle"], style: "traditional",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 3,
    tags: ["leather", "club", "ambient", "herringbone", "art"],
    scene: { windowPlacement: "hidden", furniturePosition: "right", flooring: "herringbone", coffeeTable: "round", plantType: "small", wallTreatment: "art" },
  },
  "hero-049": {
    id: "hero-049",
    fileId: "file_fsqEZPHJBH4zlHNnoazK4RWx",
    url: "https://hercules-cdn.com/file_fsqEZPHJBH4zlHNnoazK4RWx",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair"],
    furnitureType: "chair", colors: ["mid-grey", "grey"], style: "modern",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 4,
    tags: ["microfiber", "ergonomic", "right-window", "parquet", "minimal"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "parquet", coffeeTable: "none", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-050": {
    id: "hero-050",
    fileId: "file_P7r1rPNf0LFPoa5WvbJONI54",
    url: "https://hercules-cdn.com/file_P7r1rPNf0LFPoa5WvbJONI54",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["chair-repair", "sofa-upholstery"],
    furnitureType: "chair", colors: ["white", "off-white"], style: "minimal",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 5,
    tags: ["suede-look", "scandinavian", "backlit", "wood", "blonde-wood"],
    scene: { windowPlacement: "behind", furniturePosition: "left", flooring: "wood", coffeeTable: "rectangular", plantType: "none", wallTreatment: "plain" },
  },
  "hero-051": {
    id: "hero-051",
    fileId: "file_q68NKkpKaQIm0xlvYOu6OTgJ",
    url: "https://hercules-cdn.com/file_q68NKkpKaQIm0xlvYOu6OTgJ",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["cognac", "tan"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["leather", "4-seater", "villa", "marble", "chandelier", "right-window"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "marble", coffeeTable: "rectangular", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-052": {
    id: "hero-052",
    fileId: "file_wtszk4hPe7Qh7BzjcIQVp0s1",
    url: "https://hercules-cdn.com/file_wtszk4hPe7Qh7BzjcIQVp0s1",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["ivory", "white"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 2,
    tags: ["leather", "italian-style", "penthouse", "marble", "backlit", "floor-to-ceiling"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "marble", coffeeTable: "rectangular", plantType: "none", wallTreatment: "plain" },
  },
  "hero-053": {
    id: "hero-053",
    fileId: "file_VGMrGpJlq79KJMKIUsNLw0kO",
    url: "https://hercules-cdn.com/file_VGMrGpJlq79KJMKIUsNLw0kO",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["charcoal", "black"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 3,
    tags: ["leather", "modular", "sectional", "highrise", "left-window", "dusk"],
    scene: { windowPlacement: "left", furniturePosition: "left", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "texture" },
  },
  "hero-054": {
    id: "hero-054",
    fileId: "file_2qt7Eu4Z5c0qWy0uPYCzcaQw",
    url: "https://hercules-cdn.com/file_2qt7Eu4Z5c0qWy0uPYCzcaQw",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["champagne", "gold"], style: "luxury",
    roomType: "bedroom", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 4,
    tags: ["velvet", "chaise-longue", "bedroom", "right-window", "silk-curtains"],
    scene: { windowPlacement: "right", furniturePosition: "right", flooring: "marble", coffeeTable: "none", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-055": {
    id: "hero-055",
    fileId: "file_jKHaxMqKPMI475WREKEeZJLC",
    url: "https://hercules-cdn.com/file_jKHaxMqKPMI475WREKEeZJLC",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["dark-chocolate", "brown"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 5,
    tags: ["leather", "chesterfield", "tufted", "old-money", "herringbone", "persian-rug"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "herringbone", coffeeTable: "rectangular", plantType: "small", wallTreatment: "art" },
  },
  "hero-056": {
    id: "hero-056",
    fileId: "file_Ul7zpNPIsqAVOmZLo2IcTIeK",
    url: "https://hercules-cdn.com/file_Ul7zpNPIsqAVOmZLo2IcTIeK",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa", colors: ["white", "off-white"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 6,
    tags: ["boucle", "3-seater", "penthouse", "backlit", "marble", "architectural"],
    scene: { windowPlacement: "behind", furniturePosition: "left", flooring: "marble", coffeeTable: "none", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-057": {
    id: "hero-057",
    fileId: "file_CoA0Lup5B0vuasHWi9rTh6iN",
    url: "https://hercules-cdn.com/file_CoA0Lup5B0vuasHWi9rTh6iN",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner", colors: ["cognac", "tan"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 7,
    tags: ["leather", "cinema-room", "ambient", "parquet", "recessed-lighting"],
    scene: { windowPlacement: "hidden", furniturePosition: "right", flooring: "parquet", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-058": {
    id: "hero-058",
    fileId: "file_pPmAy6fSZvMqwks8nRh2XP0Z",
    url: "https://hercules-cdn.com/file_pPmAy6fSZvMqwks8nRh2XP0Z",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["sage-green", "green"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 8,
    tags: ["velvet", "l-shaped", "sectional", "villa", "left-window", "french-doors"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "tall", wallTreatment: "art" },
  },
  "hero-059": {
    id: "hero-059",
    fileId: "file_uSEdNVRAvzr5HSFVdYwMK7tr",
    url: "https://hercules-cdn.com/file_uSEdNVRAvzr5HSFVdYwMK7tr",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair"],
    furnitureType: "sofa", colors: ["ash-grey", "grey"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 9,
    tags: ["fabric", "curved", "right-window", "travertine", "arched-mirror"],
    scene: { windowPlacement: "right", furniturePosition: "right", flooring: "marble", coffeeTable: "none", plantType: "hanging", wallTreatment: "texture" },
  },
  "hero-060": {
    id: "hero-060",
    fileId: "file_Yw0Pa5jzI1kARXDUDEp7Fbg8",
    url: "https://hercules-cdn.com/file_Yw0Pa5jzI1kARXDUDEp7Fbg8",
    width: 1792, height: 1024, version: 1, createdAt: "2026-07-18", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["navy", "deep-blue"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 10,
    tags: ["leather", "tufted", "colonial", "herringbone", "persian-rug", "carved-wood"],
    scene: { windowPlacement: "hidden", furniturePosition: "left", flooring: "herringbone", coffeeTable: "rectangular", plantType: "small", wallTreatment: "art" },
  },

  // ─── Batch 2 — Blog/media images added 2026-07-19 ────────────────────────────

  "hero-061": {
    id: "hero-061",
    fileId: "file_JJzkab1agHD9pAgMCzPG74ax",
    url: "https://hercules-cdn.com/file_JJzkab1agHD9pAgMCzPG74ax",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["dark-brown", "cream"], style: "luxury",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["leather", "chesterfield", "before-after", "dark-walls", "chandelier", "arched-window"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "herringbone", coffeeTable: "rectangular", plantType: "none", wallTreatment: "texture" },
  },
  "hero-062": {
    id: "hero-062",
    fileId: "file_Cl3spMPq6hJUnCzxy5pbqBsm",
    url: "https://hercules-cdn.com/file_Cl3spMPq6hJUnCzxy5pbqBsm",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["light-grey", "white"], style: "luxury",
    roomType: "living-room", cityKeys: ["faridabad"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["multi-sofa", "grand-hall", "chandelier", "sectional", "marble"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "none", wallTreatment: "plain" },
  },
  "hero-063": {
    id: "hero-063",
    fileId: "file_IGrm79PJwER9x3jSXoIWcwuk",
    url: "https://hercules-cdn.com/file_IGrm79PJwER9x3jSXoIWcwuk",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["cognac", "tan"], style: "traditional",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 2,
    tags: ["leather", "chesterfield", "tufted", "traditional", "persian-rug", "lamps"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "herringbone", coffeeTable: "rectangular", plantType: "small", wallTreatment: "art" },
  },
  "hero-064": {
    id: "hero-064",
    fileId: "file_NS0bfzOw5h4VilQh3awWi6lc",
    url: "https://hercules-cdn.com/file_NS0bfzOw5h4VilQh3awWi6lc",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["cream", "beige"], style: "traditional",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 3,
    tags: ["before-after", "cream", "traditional", "fireplace", "carved-wood"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "tall", wallTreatment: "art" },
  },
  "hero-065": {
    id: "hero-065",
    fileId: "file_5txLhJ4dD5FKDTXAUarwvlwQ",
    url: "https://hercules-cdn.com/file_5txLhJ4dD5FKDTXAUarwvlwQ",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["off-white", "white"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 4,
    tags: ["before-after", "white", "elegant", "lamps", "cushions"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "art" },
  },
  "hero-066": {
    id: "hero-066",
    fileId: "file_XrBPXfnRQ1A7uYsXOPZI0tKw",
    url: "https://hercules-cdn.com/file_XrBPXfnRQ1A7uYsXOPZI0tKw",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["gold", "ivory"], style: "luxury",
    roomType: "lobby", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["royal", "palace", "ornate", "gold", "maharaja", "carved-wood", "arch"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "marble", coffeeTable: "rectangular", plantType: "none", wallTreatment: "texture" },
  },
  "hero-067": {
    id: "hero-067",
    fileId: "file_40SwfwTRz8DU7A3t1PbpBmxj",
    url: "https://hercules-cdn.com/file_40SwfwTRz8DU7A3t1PbpBmxj",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["grey", "charcoal"], style: "modern",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["modern", "sectional", "gurgaon", "marble", "high-ceiling"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-068": {
    id: "hero-068",
    fileId: "file_3m7EdCY6UUxLdEP9RTSev1fU",
    url: "https://hercules-cdn.com/file_3m7EdCY6UUxLdEP9RTSev1fU",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["beige", "cream"], style: "luxury",
    roomType: "living-room", cityKeys: ["noida"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["noida", "luxury-apartment", "floor-to-ceiling-windows", "sectional"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "none", wallTreatment: "plain" },
  },
  "hero-069": {
    id: "hero-069",
    fileId: "file_cT74DbgoXUJt1gCWjlw2blAB",
    url: "https://hercules-cdn.com/file_cT74DbgoXUJt1gCWjlw2blAB",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["brown", "tan"], style: "contemporary",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 5,
    tags: ["leather", "sectional", "l-shape", "doorstep", "repair", "gurgaon"],
    scene: { windowPlacement: "right", furniturePosition: "left", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-070": {
    id: "hero-070",
    fileId: "file_Z9t45Z1szaCwf6Us95GzB5oL",
    url: "https://hercules-cdn.com/file_Z9t45Z1szaCwf6Us95GzB5oL",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair"],
    furnitureType: "sofa", colors: ["dark-brown", "cream"], style: "luxury",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 5,
    tags: ["leather", "before-after", "tufted", "restoration"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "herringbone", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-071": {
    id: "hero-071",
    fileId: "file_VwHzoXXw5H3L4bloDerXp2dZ",
    url: "https://hercules-cdn.com/file_VwHzoXXw5H3L4bloDerXp2dZ",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["caramel", "brown"], style: "luxury",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 6,
    tags: ["leather", "before-after", "restoration", "elegant", "gurgaon"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-072": {
    id: "hero-072",
    fileId: "file_O3JWv8YovYJ75lw9N4odcMlZ",
    url: "https://hercules-cdn.com/file_O3JWv8YovYJ75lw9N4odcMlZ",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["grey", "white"], style: "modern",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 7,
    tags: ["modern", "delhi-ncr", "living-room", "open-plan"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "rectangular", plantType: "small", wallTreatment: "plain" },
  },
  "hero-073": {
    id: "hero-073",
    fileId: "file_YwXFDYrvYhd9FnmCv6utDskR",
    url: "https://hercules-cdn.com/file_YwXFDYrvYhd9FnmCv6utDskR",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["beige", "off-white"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 8,
    tags: ["before-after", "delhi-ncr", "restoration"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-074": {
    id: "hero-074",
    fileId: "file_GWUmibnXKoXcGwP0FMRPitiE",
    url: "https://hercules-cdn.com/file_GWUmibnXKoXcGwP0FMRPitiE",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["beige", "gold"], style: "luxury",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: ["south-delhi"], isPremium: true,
    orientation: "landscape", priority: 2,
    tags: ["south-delhi", "luxury", "living-room", "ornate"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "tall", wallTreatment: "art" },
  },
  "hero-075": {
    id: "hero-075",
    fileId: "file_nTSwQR1bNBE05yjXv0Ya0h2X",
    url: "https://hercules-cdn.com/file_nTSwQR1bNBE05yjXv0Ya0h2X",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["white", "cream"], style: "traditional",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 9,
    tags: ["classic", "traditional", "lamps", "curtains"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "rectangular", plantType: "none", wallTreatment: "art" },
  },
  "hero-076": {
    id: "hero-076",
    fileId: "file_uEQ8jcORHSpRb8CO6UzRBwlx",
    url: "https://hercules-cdn.com/file_uEQ8jcORHSpRb8CO6UzRBwlx",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["grey", "taupe"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 10,
    tags: ["delhi-ncr", "living-room", "contemporary"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "wood", coffeeTable: "round", plantType: "small", wallTreatment: "plain" },
  },
  "hero-077": {
    id: "hero-077",
    fileId: "file_Nd5ZeFlvHnd3XnRa11RJN5Z5",
    url: "https://hercules-cdn.com/file_Nd5ZeFlvHnd3XnRa11RJN5Z5",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["light-grey", "silver"], style: "modern",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 11,
    tags: ["upholstery", "modern", "fabric", "restoration", "gurgaon"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "round", plantType: "none", wallTreatment: "plain" },
  },
  "hero-078": {
    id: "hero-078",
    fileId: "file_IiGfKpQ2rE4FObhtsF5wEyHg",
    url: "https://hercules-cdn.com/file_IiGfKpQ2rE4FObhtsF5wEyHg",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "leather-sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["dark-brown", "tan"], style: "contemporary",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 12,
    tags: ["leather", "upholstery", "professional", "service", "gurgaon"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-079": {
    id: "hero-079",
    fileId: "file_CBwTEd8UXpddDX4Pbu6aBTr2",
    url: "https://hercules-cdn.com/file_CBwTEd8UXpddDX4Pbu6aBTr2",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["white", "off-white"], style: "modern",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 11,
    tags: ["north-delhi", "upholstery", "modern", "bright"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "round", plantType: "none", wallTreatment: "plain" },
  },
  "hero-080": {
    id: "hero-080",
    fileId: "file_GpqPYHXLzYfN3wIa7Em68Fev",
    url: "https://hercules-cdn.com/file_GpqPYHXLzYfN3wIa7Em68Fev",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["grey", "charcoal"], style: "modern",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 12,
    tags: ["delhi-ncr", "modern", "interior"],
    scene: { windowPlacement: "behind", furniturePosition: "left", flooring: "wood", coffeeTable: "rectangular", plantType: "small", wallTreatment: "plain" },
  },
  "hero-081": {
    id: "hero-081",
    fileId: "file_GdgG3QZMVf97ct6v9kASEwD6",
    url: "https://hercules-cdn.com/file_GdgG3QZMVf97ct6v9kASEwD6",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "furniture-repair"],
    furnitureType: "sofa", colors: ["beige", "white"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 13,
    tags: ["delhi-ncr", "professional", "restoration"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "marble", coffeeTable: "round", plantType: "tall", wallTreatment: "plain" },
  },
  "hero-082": {
    id: "hero-082",
    fileId: "file_NFuKszVOy6fBj9feCJ7t2faQ",
    url: "https://hercules-cdn.com/file_NFuKszVOy6fBj9feCJ7t2faQ",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["cream", "beige"], style: "luxury",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 7,
    tags: ["before-after", "luxury", "restoration", "gurgaon"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "art" },
  },
  "hero-083": {
    id: "hero-083",
    fileId: "file_5lQi6nQtshkaW9FDhDauw7r8",
    url: "https://hercules-cdn.com/file_5lQi6nQtshkaW9FDhDauw7r8",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["blue", "navy"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 14,
    tags: ["blue", "before-after", "delhi-ncr", "fabric"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "rectangular", plantType: "none", wallTreatment: "plain" },
  },
  "hero-084": {
    id: "hero-084",
    fileId: "file_0Eat8jS7HyIOMR1T7k8bVBS8",
    url: "https://hercules-cdn.com/file_0Eat8jS7HyIOMR1T7k8bVBS8",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["white", "cream"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 15,
    tags: ["upholstery", "professional", "delhi"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "small", wallTreatment: "plain" },
  },
  "hero-085": {
    id: "hero-085",
    fileId: "file_Hy69QRG6PQGaDw5leGlh5asW",
    url: "https://hercules-cdn.com/file_Hy69QRG6PQGaDw5leGlh5asW",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["sofa-repair", "sofa-upholstery"],
    furnitureType: "sofa", colors: ["beige", "cream"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 16,
    tags: ["before-after", "upholstery", "delhi-ncr"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },

  // ─── Recliner images ──────────────────────────────────────────────────────────

  // Generated 2026-07-19: Gurgaon-specific recliner images
  "hero-089": {
    id: "hero-089",
    fileId: "file_O66qmqrFrv90Ul62lnMFItVi",
    url: "https://hercules-cdn.com/file_O66qmqrFrv90Ul62lnMFItVi",
    width: 1792, height: 1008, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["charcoal", "dark-grey"], style: "modern",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["home-theater", "recliner", "gurgaon", "highrise", "city-view", "ambient-lighting", "marble"],
    scene: { windowPlacement: "behind", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-090": {
    id: "hero-090",
    fileId: "file_7ZzUbCcY67CoTJGJ6S12WUix",
    url: "https://hercules-cdn.com/file_7ZzUbCcY67CoTJGJ6S12WUix",
    width: 1792, height: 1008, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair", "leather-sofa-repair"],
    furnitureType: "recliner", colors: ["cognac", "tan"], style: "contemporary",
    roomType: "living-room", cityKeys: ["gurgaon"], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 2,
    tags: ["leather", "recliner", "gurgaon", "power-recliner", "luxury-apartment", "daylight"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "marble", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-091": {
    id: "hero-091",
    fileId: "file_rY70UH3Pr9XJlZe4z41xeM4C",
    url: "https://hercules-cdn.com/file_rY70UH3Pr9XJlZe4z41xeM4C",
    width: 1792, height: 1008, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair", "sofa-repair"],
    furnitureType: "recliner", colors: ["brown", "beige"], style: "contemporary",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 4,
    tags: ["recliner", "before-after", "fabric", "restoration", "repair"],
    scene: { windowPlacement: "left", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },

  "hero-086": {
    id: "hero-086",
    fileId: "file_zn7uVlgNIEC7Pb3NlD58ujR5",
    url: "https://hercules-cdn.com/file_zn7uVlgNIEC7Pb3NlD58ujR5",
    width: 1400, height: 933, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["dark-grey", "charcoal"], style: "modern",
    roomType: "living-room", cityKeys: [], localitySlugs: [], isPremium: true,
    orientation: "landscape", priority: 1,
    tags: ["home-theater", "recliner", "seating", "ambient-lighting", "cinema"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-087": {
    id: "hero-087",
    fileId: "file_Wf0mo2ViSrP0cT3iw8kwww0J",
    url: "https://hercules-cdn.com/file_Wf0mo2ViSrP0cT3iw8kwww0J",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair", "sofa-repair"],
    furnitureType: "recliner", colors: ["brown", "tan"], style: "contemporary",
    roomType: "living-room", cityKeys: ["delhi"], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 2,
    tags: ["recliner", "before-after", "repair", "delhi-ncr"],
    scene: { windowPlacement: "right", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
  "hero-088": {
    id: "hero-088",
    fileId: "file_RswmmEMLoAHmiRATLUp1thCG",
    url: "https://hercules-cdn.com/file_RswmmEMLoAHmiRATLUp1thCG",
    width: 1400, height: 700, version: 1, createdAt: "2026-07-19", status: "approved",
    services: ["recliner-repair"],
    furnitureType: "recliner", colors: ["black", "dark-grey"], style: "modern",
    roomType: "office", cityKeys: [], localitySlugs: [], isPremium: false,
    orientation: "landscape", priority: 3,
    tags: ["recliner", "gaming-chair", "before-after", "restoration"],
    scene: { windowPlacement: "hidden", furniturePosition: "center", flooring: "wood", coffeeTable: "none", plantType: "none", wallTreatment: "plain" },
  },
};
