import { BRAND_NAME, PHONE_DISPLAY } from "./seo-constants.ts";
import type { BlogPost } from "./blog-data.ts";

export const furnitureRestorationChecklist: BlogPost = {
  slug: "furniture-restoration-checklist",
  title:
    "Furniture Restoration Checklist: What to Know Before Hiring a Professional | FurniRevive",
  metaDescription:
    "Complete furniture restoration checklist for homeowners. Pre-assessment, damage classification, budget prep, scope definition, logistics, handover verification, and a printable master checklist — before you hire.",
  h1: "Furniture Restoration Checklist: What to Know Before Hiring a Professional",
  imageAlt:
    "furniture restoration checklist pre-hiring preparation guide for homeowners",
  publishedDate: "2026-06-16",
  updatedDate: "2026-06-16",
  author: "FurniRevive Team",
  readTime: "13 min read",
  category: "Restoration Guide",
  featuredImage: "https://hercules-cdn.com/file_CcIexqH0AhmsHtcqbU15UWro",
  excerpt:
    "Before a restorer sets foot in your home, there is a lot you can do to protect yourself and get better results. This complete furniture restoration checklist walks you through pre-assessment, damage classification, budget preparation, scope definition, logistics, handover verification, and the ongoing care commitment — so you hire with clarity and confidence.",
  keywords: [
    "furniture restoration checklist",
    "pre-hiring furniture restoration checklist",
    "what to know before hiring furniture restorer",
    "furniture restoration preparation guide",
    "furniture damage assessment checklist",
    "furniture restoration budget guide",
    "furniture restoration scope checklist",
    "furniture restoration handover checklist",
    "restoration readiness score",
    "furniture restoration Delhi NCR",
  ],
  content: [
    {
      body: [
        `Most homeowners hire a furniture restorer the same way they hire a plumber — they call someone when something breaks and hope for the best. That approach works reasonably well for commodity repairs, but furniture restoration is different. A skilled restorer working from clear information delivers a fundamentally better result than the same restorer working from vague instructions and an unprepared client. The difference in outcome can be dramatic.`,
        `This furniture restoration checklist is built around one idea: the more preparation you bring to the hiring conversation, the better the restoration you receive. It walks through every phase — from the moment you first notice your furniture needs attention to the documentation you file after the restorer hands the piece back. Use it section by section or jump to the phase most relevant to your current situation.`,
        `For a broader understanding of what a professional restoration project looks like end to end, see our <a href="/blog/complete-furniture-restoration-process">complete furniture restoration process guide</a>. For an overview of everything restoration involves, see the <a href="/blog/ultimate-furniture-restoration-guide">ultimate furniture restoration guide</a>. When you are ready to evaluate specific companies, the <a href="/blog/how-to-choose-furniture-restoration-company">how to choose a furniture restoration company guide</a> covers that in depth.`,
      ],
    },
    {
      heading: "Phase 1: Pre-Assessment Checklist — Document Before the Restorer Arrives",
      body: [
        `The restorer who arrives at your home will form their own assessment, but a homeowner who arrives at that conversation with organised documentation consistently receives more accurate quotes, clearer timelines, and fewer surprises mid-project. This phase takes 20–30 minutes and pays back many times over.`,
        `**Photograph every angle of the piece.** Take photographs in natural daylight — not artificial indoor light, which conceals colour inconsistencies, surface scratches, and upholstery texture problems. Photograph the front, both sides, the back, the top, and the underside or bottom. Get close-up shots of every area of concern. If the piece opens (drawers, doors, fold-down surfaces), photograph those open and closed. A good photo set is 15–25 images for a typical sofa or cabinet.`,
        `**Document the known history of the piece.** When did you acquire it? Was it purchased new or second-hand? Do you know the original manufacturer, brand, or craftsman? Where was it made (India, Italy, Scandinavia, the UK)? The country of origin matters because restoration materials, joinery techniques, and finishing conventions differ significantly between furniture-making traditions. An Italian sofa upholstered with a European foam system requires different materials and approach than Indian handmade furniture from Jodhpur.`,
        `**Record all previous repairs you know about.** If the piece has been polished, reupholstered, restained, or structurally repaired before, document that. Previous repairs affect how a restorer approaches the current job — they may need to remove or work around existing interventions. Undisclosed prior repairs that the restorer discovers mid-project can change the quote and the timeline.`,
        `**Note original purchase details if you have them.** Invoice or receipt (price, retailer, date), fabric or material specification from original purchase, any care documentation that came with the piece. If you no longer have these documents, recall what you can and note it. Original purchase price is particularly relevant — it establishes the baseline for cost-versus-replacement decisions.`,
        `**List the specific problems as you observe them.** Describe in your own words what is wrong, where it is wrong, and when you first noticed it. "The left rear leg has been loose for about six months and now wobbles noticeably" is more useful than "the legs are broken." Specificity helps the restorer prioritise their inspection and reduces the chance of something being missed.`,
        `**Checklist summary — Pre-Assessment:**`,
        `☐ 15–25 photographs taken in natural daylight (all angles, all problem areas)`,
        `☐ Known acquisition date and source documented`,
        `☐ Country of origin and manufacturer noted (if known)`,
        `☐ Previous repairs listed (what was done, approximately when, by whom)`,
        `☐ Original purchase details recorded or recalled`,
        `☐ Problem areas described in your own words, with location and approximate timeline`,
      ],
    },
    {
      heading: "Phase 2: Damage Classification Checklist — Communicate Accurately",
      body: [
        `Restoration professionals classify damage into four broad categories. Understanding this classification helps you communicate more precisely — which results in more accurate quotes and avoids the situation where a restorer quotes for surface work and then discovers structural damage mid-project that was never discussed.`,
        `**Structural damage** involves the load-bearing components of the piece. For sofas and chairs, this means the frame — the wooden or metal skeleton that everything else attaches to. Structural problems include loose or broken joints, cracked or snapped frame members, warped wood from water exposure, and metal frame fatigue in imported or reclining furniture. Structural repairs require disassembly, which adds time and cost. To check: push gently on each corner and the centre of the seat. Any rocking or movement beyond minor flex indicates structural looseness.`,
        `**Surface damage** is confined to the exterior finish of solid wood or painted components. It includes scratches, dents, water rings, fading from sunlight, peeling varnish, oxidised polish, and discolouration. Surface damage does not affect structural integrity but is often the most visually prominent category. To check: run your fingertips across all finished wood surfaces in different lighting conditions.`,
        `**Biological damage** includes termite infestation, mould or mildew from water or humidity exposure, and odour from pet activity or sustained moisture. Biological damage often requires treatment before restoration work begins — pest control intervention for termites, antifungal treatment for mould — and may affect whether certain parts of the piece can be retained or must be replaced. To check: press firmly on wooden surfaces for softness or hollow sound, look for fine sawdust, and smell the piece at close range in different areas.`,
        `**Upholstery damage** covers fabric, leather, foam, springs, and all soft components. Sub-categories within upholstery damage are: surface (tears, stains, fading), foam (compression, crumbling, loss of support), spring (broken, displaced, or sagging springs), and structure (straps, webbing, or base boards that support the upholstery system). Upholstery damage is usually visible, but foam and spring problems require physical testing — sit on the piece and assess where it sinks, feels hard, or feels uneven.`,
        `**Checklist summary — Damage Classification:**`,
        `☐ Structural: Check all joints and frame members for movement, cracks, or softness`,
        `☐ Surface: Inspect all finished surfaces in natural light for scratches, water marks, fading, peeling`,
        `☐ Biological: Check for sawdust, hollow sound, soft spots, visible mould, or persistent odour`,
        `☐ Upholstery — Surface: Document all tears, stains, peeling (especially leatherette), and fading`,
        `☐ Upholstery — Internal: Sit-test all seats and note where sinking, hardness, or unevenness occurs`,
        `☐ List which damage categories apply to your piece (some pieces will have multiple)`,
      ],
    },
    {
      heading: "Phase 3: Budget Preparation Checklist — Estimate Before Getting Quotes",
      body: [
        `Arriving at a quote conversation without any budget orientation puts you at a disadvantage. You cannot evaluate whether a quote is reasonable if you have no sense of what is normal. The following ranges are based on Delhi NCR pricing as of 2026 and cover the most common restoration scopes. They are ranges, not fixed prices — actual cost depends on piece size, materials chosen, and the extent of damage.`,
        `**Surface refinishing (wood polish, stain, and clear coat):** ₹2,000–₹8,000 for a typical dining table or cabinet. Antique or hand-carved pieces cost more due to the care required around carved details.`,
        `**Structural repair (frame joints, broken members):** ₹2,000–₹10,000 depending on the number of failed joints and whether any structural members need replacement. Severe structural failure — where the frame must be substantially reconstructed — can reach ₹15,000–₹25,000 for large pieces.`,
        `**Full foam replacement (sofa or chair):** ₹999–₹2,500 per cushion for 32D foam. A 3-seater sofa with 6 cushions runs ₹4,000–₹8,000 for foam alone.`,
        `**Fabric upholstery (material + labour):** ₹3,000–₹8,000 per seat for cotton and polyester blends. ₹5,000–₹10,000 per seat for leatherette. ₹12,000–₹25,000 per seat for genuine leather.`,
        `**Complete restoration (structural + surface + upholstery):** ₹12,000–₹35,000 for a standard 3-seater sofa. ₹20,000–₹60,000 for larger pieces or premium materials.`,
        `**Biological treatment (before restoration work begins):** ₹3,000–₹8,000 for anti-termite treatment of a piece with active infestation. Mould remediation adds ₹1,500–₹4,000.`,
        `**Budget preparation checklist:**`,
        `☐ Identify the damage categories present (from Phase 2) and look up the relevant cost ranges above`,
        `☐ Set a maximum budget before calling for quotes — this prevents scope creep under pressure`,
        `☐ Determine your minimum acceptable outcome: cosmetic only, or full restoration including structure`,
        `☐ Factor in the cost of doing nothing — furniture that continues to deteriorate costs more to restore later`,
        `☐ Compare your budget against replacement cost for the same piece type and quality`,
        `☐ If biological damage is present, budget for pre-treatment as a separate line item`,
      ],
    },
    {
      heading: "Phase 4: Scope Definition Checklist — Answer Before Agreeing to Anything",
      body: [
        `Scope creep — where a restoration project expands beyond what was originally discussed — is the most common source of disputes between homeowners and restorers. The cause is almost always the same: the scope was never clearly defined before work began. Answer these questions for yourself before agreeing to any scope of work.`,
        `**Full restoration vs partial restoration.** Are you looking to return the piece to its original condition across all dimensions — structure, surface, and upholstery — or only address the most pressing problem? Partial restorations are a legitimate choice when budget is constrained, but they require explicit documentation to prevent the restorer from assuming a fuller scope.`,
        `**Original finish vs updated finish.** For wooden pieces: do you want the piece returned to its original colour and finish type, or are you open to a different stain, a different sheen level, or even a painted finish? Both are valid, but they have different cost implications and different reversibility. Changing a finish is permanent. If there is any chance you might want to restore to original later — particularly for antique or inherited pieces — keep the finish unchanged.`,
        `**Original fabric vs new fabric selection.** For upholstered pieces: do you want to retain the existing fabric and only repair damage, or replace the fabric entirely? If replacing: have you chosen the new fabric, or do you need to see samples? Who bears the cost if the first fabric choice does not look right on the actual piece?`,
        `**Retain existing foam vs replace.** Foam that is structurally sound (firm, spring-back within 1 second) may not need replacing even if fabric is being changed. Ask the restorer to assess foam condition separately and confirm whether they are pricing to replace or retain.`,
        `**Which components are in scope and which are not.** For a sofa: does the scope include the frame, the springs, the foam, the fabric, the legs, the piping, and the arm caps? Or only some of these? Every component that is in scope should be listed explicitly in writing.`,
        `**Scope definition checklist:**`,
        `☐ Full or partial restoration — documented in writing`,
        `☐ Finish decision — original or updated — confirmed before work begins`,
        `☐ Fabric decision — retain or replace — if replace, fabric selected before work starts`,
        `☐ Foam assessment — retain or replace — based on physical assessment, not assumption`,
        `☐ Complete list of components in scope — legs, springs, piping, arm caps, base, frame joints, etc.`,
        `☐ Exclusions listed — what is explicitly not in scope`,
      ],
    },
    {
      heading: "Phase 5: Logistics Checklist — In-Home vs Workshop, Access, and Timeline",
      body: [
        `The logistics of a restoration project are often underestimated. Poor logistics planning causes delays, damage to other furniture, and situations where the restorer cannot access what they need to do the job properly.`,
        `**In-home service vs workshop service.** Surface polishing, minor upholstery repairs, and foam replacement can usually be done at your home. Full structural repairs, complete reupholstery, and finishing work almost always produce better results in a dedicated workshop where the restorer has proper tools, adequate lighting, and controlled conditions. Ask the restorer whether your project is better suited to in-home or workshop service — and if they say in-home for a complex structural job, treat that as a concern.`,
        `**Access requirements for in-home work.** If the restorer is working at your home: Is there a clear path from the entrance to the piece? Can the piece be moved to a space with better lighting? Is there access to a power outlet? For large pieces like wardrobes or beds, can the restorer access all sides? Clear a 1.5-metre working radius around the piece before the restorer arrives.`,
        `**Protection of adjacent furniture and flooring.** Polishing and finishing work produces dust, fumes, and occasionally liquid finishes that migrate beyond the immediate work area. Before in-home work begins: remove decorative items from adjacent surfaces, cover nearby furniture with sheets, and protect flooring with drop cloths. If the restorer brings their own protection materials, confirm this in advance.`,
        `**Timeline planning.** Surface polishing: 1–2 days. Foam replacement: same day or next day. Fabric reupholstery: 2–4 days for fabric, 3–5 days for leather. Full structural + surface + upholstery restoration: 5–14 days depending on piece complexity and material availability. If the piece is being transported to a workshop, add 1 day each for collection and delivery. Ask for a start date and a completion date — not a vague "a few days."`,
        `**If the piece is going to a workshop.** Get written confirmation of the workshop address, a photo or video of the piece before it leaves your home, and a documented condition report signed by both parties. This protects you if there is any dispute about damage that occurs during transport.`,
        `**Logistics checklist:**`,
        `☐ Confirmed: in-home vs workshop service for this scope of work`,
        `☐ Access path cleared, 1.5m working radius around piece cleared`,
        `☐ Adjacent furniture and flooring protection planned`,
        `☐ Start date and completion date agreed and documented`,
        `☐ If going to workshop: workshop address, pre-transport photos, condition report signed`,
        `☐ Collection and delivery logistics confirmed (who, when, how)`,
      ],
    },
    {
      heading: "Phase 6: Post-Restoration Handover Checklist — Verify Before the Restorer Leaves",
      body: [
        `The handover moment — when the restorer presents the completed piece — is the most important quality control checkpoint you have. Once the restorer has left your home and accepted payment, your leverage for corrections drops sharply. Do not accept the piece without running through this checklist.`,
        `**Visual inspection in natural light.** Move the piece to the best-lit area of your home, or open blinds and curtains fully. Inspect every surface for: finish evenness (no blotches, drips, brush marks, or sheen variation), colour consistency across the full piece, upholstery tension (smooth and even across all panels with no diagonal wrinkles), seam alignment (seams running straight and evenly spaced), piping (straight, firm, and continuous), and leg or base alignment (piece sits level on a flat floor).`,
        `**Physical function test.** For sofas and chairs: sit on every seat position and lean into every backrest. Springs should be even with no hard spots or protrusions. Foam should feel consistent across all cushions. For reclining pieces: test the full recline mechanism. For pieces with drawers or doors: open and close every drawer and door and check that they operate smoothly and close flush.`,
        `**Structural integrity check.** Push gently on the frame from all sides and check that no movement has developed. A properly repaired joint should feel solid.`,
        `**Material documentation to request.** Ask the restorer for: the foam density and brand used (if foam was replaced), the fabric name, weight, and supplier (if fabric was replaced), the finish product name (stain colour reference, polish or lacquer brand) if the piece was refinished, and any hardware (hinges, castors, handles) that were replaced including brand and specification. This documentation is invaluable if you need to match materials for a future repair.`,
        `**Warranty documentation.** A professional restoration service provides a written warranty. The standard in Delhi NCR is 6 months on labour and materials. Confirm the warranty start date, what it covers, what voids it, and how to make a claim. ${BRAND_NAME} provides a 6-month warranty on all restoration work.`,
        `**Handover checklist:**`,
        `☐ Visual inspection in natural light — all surfaces, upholstery, seams, piping`,
        `☐ Physical function test — sit, lean, recline, open drawers, close doors`,
        `☐ Structural integrity check — push test on all frame sides`,
        `☐ Material documentation received — foam density, fabric spec, finish product reference`,
        `☐ Warranty document received — in writing, covering start date and scope`,
        `☐ Payment made only after all items above are confirmed`,
      ],
    },
    {
      heading: "Phase 7: Maintenance Commitment Checklist — What You Are Committing To",
      body: [
        `A restoration investment is only protected if you commit to ongoing maintenance. The deterioration rate of restored furniture depends almost entirely on how it is cared for in the months and years after handover.`,
        `**Fabric upholstery maintenance.** Vacuum upholstered surfaces every 2–3 weeks using a soft brush attachment. Wipe spills immediately with a dry cloth — do not rub, blot. For fabric, use a mild fabric cleaner or diluted mild soap on stains. Avoid prolonged exposure to direct sunlight, which fades fabric colour within 6–12 months in Delhi. Rotate cushion covers every 6 months if they are reversible to even wear.`,
        `**Wood surface maintenance.** Apply furniture wax or quality wood polish every 3–6 months. Avoid placing hot cups or dishes directly on wooden surfaces — use coasters. Clean with a barely damp cloth, never a wet cloth. In Delhi's monsoon season (July–September), use a dehumidifier in the room if relative humidity regularly exceeds 70%. For teak or sheesham, apply teak oil once a year.`,
        `**Leather and leatherette maintenance.** For genuine leather: apply leather conditioner every 3–4 months and a leather protector every 6 months. Wipe clean with a dry cloth. Keep out of direct sunlight and away from heat sources. For leatherette: wipe spills immediately. Use only mild soap and water for cleaning — solvent-based cleaners cause peeling.`,
        `**Structural maintenance.** Check and tighten any exposed bolts or screws every 6 months. If you notice any joint beginning to loosen, address it immediately — a re-glued loose joint costs ₹300–₹800. An ignored loose joint that fails structurally costs ₹2,000–₹8,000 to repair.`,
        `**Maintenance commitment checklist:**`,
        `☐ Upholstery vacuum schedule: every 2–3 weeks`,
        `☐ Wood polish schedule: every 3–6 months`,
        `☐ Leather conditioning schedule: every 3–4 months (if applicable)`,
        `☐ Bolt and joint check schedule: every 6 months`,
        `☐ Spill response protocol: immediate blotting, never rubbing`,
        `☐ Sunlight and heat protection measures: coasters, blinds, curtain positioning confirmed`,
        `☐ Anti-termite treatment: annually for wood pieces in ground-floor or older properties`,
      ],
    },
    {
      heading: "Master Checklist: Printable Reference by Phase",
      body: [
        `Use this consolidated checklist as a printable reference. Print it, work through each phase, and tick items off as you complete them.`,
        `**BEFORE — Pre-Assessment and Preparation**`,
        `☐ Photograph all angles in natural light (15–25 images)`,
        `☐ Document piece history: acquisition, origin, manufacturer`,
        `☐ List all known previous repairs`,
        `☐ Record original purchase details`,
        `☐ Describe problem areas in writing with location and timeline`,
        `☐ Classify damage type: structural / surface / biological / upholstery`,
        `☐ Set maximum budget before calling for quotes`,
        `☐ Define scope: full or partial, finish preference, fabric decision, foam assessment`,
        `☐ Plan logistics: in-home vs workshop, access, adjacent furniture protection`,
        `**DURING — While Work Is In Progress**`,
        `☐ If piece leaves home: photograph before transport and obtain signed condition report`,
        `☐ Confirm mid-project that scope and timeline are on track`,
        `☐ Review any scope changes in writing before approving them`,
        `☐ Do not make final payment until the handover checklist is complete`,
        `**AT HANDOVER — When the Restorer Returns the Piece**`,
        `☐ Visual inspection in natural light: finish, upholstery, seams, piping, legs`,
        `☐ Physical function test: sit, lean, recline, open drawers, close doors`,
        `☐ Structural push test on all frame sides`,
        `☐ Collect material documentation: foam density, fabric spec, finish reference`,
        `☐ Collect written warranty document`,
        `☐ Confirm payment only after all items above are satisfied`,
        `**ONGOING — Post-Restoration Care**`,
        `☐ Upholstery vacuum every 2–3 weeks`,
        `☐ Wood polish every 3–6 months`,
        `☐ Leather conditioning every 3–4 months (if applicable)`,
        `☐ Bolt and joint inspection every 6 months`,
        `☐ Record restoration in home maintenance log (see Phase 6)`,
        `☐ Anti-termite annual treatment (wood pieces, ground floor or older properties)`,
      ],
    },
    {
      heading: "Restoration Readiness Score — Are You Ready to Hire?",
      body: [
        `Before you pick up the phone or send a WhatsApp enquiry, rate yourself on five dimensions. Each dimension is scored 0–2. Total your score and read the interpretation below.`,
        `**Dimension 1 — Documentation.** Have you completed the pre-assessment checklist? (0 = no photos, no notes / 1 = photos taken, some notes / 2 = photos in natural light, full written description, history documented)`,
        `**Dimension 2 — Damage Classification.** Do you know what category or categories of damage the piece has? (0 = "something is wrong" / 1 = can identify structural vs upholstery vs surface / 2 = have tested physically and can describe each damage area specifically)`,
        `**Dimension 3 — Budget Orientation.** Have you estimated a realistic budget range before getting quotes? (0 = no idea / 1 = have reviewed cost ranges and have a rough figure / 2 = have set a firm maximum budget and have compared it against replacement cost)`,
        `**Dimension 4 — Scope Clarity.** Can you describe exactly what you want done and what you do not want done? (0 = "just fix it" / 1 = know whether full or partial restoration, have a fabric/finish preference / 2 = have answered all Phase 4 scope questions with specific answers)`,
        `**Dimension 5 — Logistics Readiness.** Are logistics prepared for the restorer's visit? (0 = have not thought about it / 1 = know whether in-home or workshop is preferred / 2 = access cleared, protection planned, dates in mind, transport plan if needed)`,
        `**Score interpretation:**`,
        `0–3 — Not ready. Complete phases 1–5 of this checklist before making any calls. Hiring now risks misaligned expectations, scope disputes, and budget surprises.`,
        `4–6 — Partially ready. You have the basics in place. Complete the checklist items you scored 0 on before committing to a quote. A partial preparation leads to a partial outcome.`,
        `7–8 — Ready to engage. You are well-prepared. Proceed with requesting quotes. Use the Phase 4 scope questions to structure your conversations with restorers.`,
        `9–10 — Fully prepared. You are in the top tier of informed clients. Share your documentation directly with restorers — your pre-assessment photos, damage classification, scope definition, and budget orientation will result in faster, more accurate quotes and a smoother project.`,
        `To get a professional assessment of your furniture from ${BRAND_NAME}, send photos and your written description to ${PHONE_DISPLAY}. Our team will review your documentation and provide a structured quote for the scope you define.`,
      ],
    },
    {
      heading: "How Pre-Hiring Preparation Improves Your Restoration Outcome",
      body: [
        `The pattern we see repeatedly at ${BRAND_NAME} is that clients who arrive with clear documentation and defined scope receive noticeably better outcomes — not because the craftsmen work harder for prepared clients, but because clarity eliminates the guesswork that causes most project problems.`,
        `A restorer working from precise information can: select the right materials before arriving, price accurately (reducing the chance of mid-project cost additions), plan the correct sequence of work, and focus 100% of their time on craftsmanship rather than figuring out what you want.`,
        `Conversely, vague instructions force the restorer to make assumptions. Those assumptions may not match your expectations. When the piece comes back and it does not look the way you imagined — even if the work is technically correct — the result is frustration, disputes, and sometimes an expensive redo.`,
        `The 30 minutes you spend on this checklist before hiring is the highest-return investment you can make in your restoration project.`,
        `For guidance on evaluating the specific companies you are considering, see our <a href="/blog/how-to-choose-furniture-restoration-company">furniture restoration company evaluation guide</a>. To understand what your restoration will involve step by step, read the <a href="/blog/complete-furniture-restoration-process">complete furniture restoration process</a>. For the comprehensive overview of everything this field involves, the <a href="/blog/ultimate-furniture-restoration-guide">ultimate furniture restoration guide</a> is the best starting point. For local service in Delhi NCR, visit our <a href="/furniture-repair-delhi">furniture repair Delhi</a> page or call us at ${PHONE_DISPLAY}.`,
      ],
    },
  ],
  faqs: [
    {
      question: "What should I document before a furniture restorer arrives?",
      answer:
        "Photograph the piece from all angles in natural daylight (15–25 images), document the piece's origin and acquisition history, list all known previous repairs, describe each problem area in writing with its location and when you first noticed it. This documentation enables accurate quoting and eliminates mid-project surprises.",
    },
    {
      question: "How do I know if my furniture has structural damage before getting a quote?",
      answer:
        "Push gently on each corner and the centre of the seat or top surface. Any rocking, flex, or movement beyond minor give indicates loose joints or frame damage. Also press firmly on all wooden surfaces — soft spots or a hollow sound suggests biological damage (termite or moisture). Structural damage requires the restorer to disassemble the piece and affects both cost and timeline.",
    },
    {
      question: "What is a realistic budget for furniture restoration in Delhi NCR?",
      answer:
        "Surface refinishing (polish and clear coat): ₹2,000–₹8,000. Structural repair: ₹2,000–₹15,000. Full foam replacement for a 3-seater: ₹4,000–₹8,000. Fabric reupholstery: ₹3,000–₹8,000 per seat. Complete restoration (structural + surface + upholstery) for a 3-seater sofa: ₹12,000–₹35,000. Premium materials increase costs proportionally.",
    },
    {
      question: "Should I get the scope of work defined before agreeing to restoration?",
      answer:
        "Yes — always. Scope creep is the most common cause of disputes in furniture restoration. Before agreeing to any work, confirm in writing: full vs partial restoration, finish preference, fabric selection, whether foam is being retained or replaced, and a complete list of all components in scope. Any item not explicitly listed is outside the scope.",
    },
    {
      question: "When should furniture go to a workshop versus be restored at home?",
      answer:
        "Surface polishing, minor upholstery patch repairs, and foam replacement can usually be done at home. Full structural repairs, complete reupholstery, and finishing work produce better results in a workshop where the restorer has proper tools, controlled conditions, and adequate space. If a restorer quotes for complex structural work at home, treat that as a concern.",
    },
    {
      question: "What should I check when the restorer returns my furniture?",
      answer:
        "Inspect in natural light for finish evenness, upholstery tension (no diagonal wrinkles), seam alignment, and piping straightness. Sit on every seat and test every mechanism. Push the frame from all sides. Collect material documentation (foam density, fabric spec, finish reference). Do not make final payment until all items pass inspection and you have the written warranty document.",
    },
    {
      question: "What documentation should I ask for after restoration is complete?",
      answer:
        "Request: foam density and brand (if replaced), fabric name, weight, and supplier (if replaced), finish product name and stain colour reference (if refinished), any replaced hardware specifications, and a written warranty document covering start date, scope, and claims process. This documentation protects you if future matching or warranty repairs are needed.",
    },
    {
      question: "What ongoing maintenance does restored furniture require?",
      answer:
        "Upholstered surfaces: vacuum every 2–3 weeks, blot spills immediately, keep away from direct sunlight. Wood surfaces: polish every 3–6 months, use coasters, wipe with a barely damp cloth. Leather: condition every 3–4 months. All pieces: check and tighten joints every 6 months. Ground-floor or older properties: annual anti-termite treatment for wooden furniture.",
    },
    {
      question: "How do I know if I am ready to hire a furniture restorer?",
      answer:
        "Use the Restoration Readiness Score: rate yourself 0–2 on Documentation, Damage Classification, Budget Orientation, Scope Clarity, and Logistics Readiness. A score of 7–10 means you are ready to engage restorers. Below 7, complete the preparation phases you scored lowest on before making calls. Prepared clients receive better quotes, clearer timelines, and fewer mid-project surprises.",
    },
    {
      question: "How do I classify damage on my furniture so I can communicate it to a restorer?",
      answer:
        "Use the four-category system: Structural (frame, joints — check by pushing on corners for movement), Surface (finish, scratches, water marks — check by running fingertips across wood in good light), Biological (termite, mould — check for sawdust, hollow sound, soft spots, odour), Upholstery (fabric tears, foam compression, spring problems — check visually and by sit-testing all seat positions). List which categories apply before calling for quotes.",
    },
  ],
  relatedPosts: [
    "ultimate-furniture-restoration-guide",
    "how-to-choose-furniture-restoration-company",
    "complete-furniture-restoration-process",
    "furniture-restoration-mistakes",
    "is-furniture-restoration-worth-it",
  ],
  relatedServicePages: [
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Wooden Furniture Restoration Delhi", href: "/wooden-furniture-restoration-delhi" },
    { label: "Luxury Furniture Restoration Delhi", href: "/luxury-furniture-restoration-delhi" },
    { label: "Sofa Repair Delhi", href: "/sofa-repair-delhi" },
  ],
};
