import type { SeoPageData } from "@/lib/seo-constants.ts";
import { buildRelatedPages } from "@/lib/seo-pages/core-links.ts";

const furnitureRepairTilakNagar: SeoPageData = {
  slug: "furniture-repair-tilak-nagar",
  title: "Furniture Repair in Tilak Nagar Delhi – FurniRevive | Sofa, Wooden & Wardrobe Repair",
  metaDescription: "Expert furniture repair in Tilak Nagar, West Delhi. Sofa foam, wooden furniture, wardrobe, dining sets & recliners. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Tilak Nagar – All Home Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Tilak Nagar — sofas, wardrobes, dining sets, recliners & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Tilak Nagar) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Tilak Nagar) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Tilak Nagar, West Delhi. Sofa foam replacement from ₹999, wooden furniture polishing from ₹800, wardrobe repair from ₹599, and recliner repair from ₹1,500. All work done at your home with a 6-month warranty.",
  intro: [
    "Tilak Nagar is a densely residential West Delhi locality with a mix of DDA housing, plotted colonies and newer apartment blocks. Homes here contain a wide variety of furniture — older sheesham sets, market-purchased sofas, modular wardrobes, and increasingly, electric recliners and imported accent pieces. When furniture in a Tilak Nagar home needs repair, FurniRevive provides complete home-visit service covering every category.",
    "We handle all furniture repair in Tilak Nagar: sofa foam replacement, spring repair, full reupholstery, wooden furniture polishing and joint repair, wardrobe hinge and runner replacement, dining set restoration, and recliner mechanism servicing — all in a single visit to your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers Tilak Nagar as one of its primary zones.",
    "For pricing context before you call, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "All Furniture Types — One Visit", description: "Sofas, wooden furniture, wardrobes, dining sets, recliners, beds — we repair everything in a single booking. You get a single transparent quote covering all items." },
    { title: "Home Visit Across Tilak Nagar", description: "We come to your address — DDA flat, housing society, or independent floor — with all tools and materials. No transport, no disruption." },
    { title: "Transparent Pricing", description: "Furniture repair from ₹599, sofa foam from ₹999/cushion, full reupholstery from ₹3,000/seat, polishing from ₹800. Written quote before work starts." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Tilak Nagar address and the furniture pieces that need attention. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Complex jobs may require a brief workshop transit confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Tilak Nagar — all types in one booking",
    "Home visit service — no transport required",
    "Transparent written quote before work starts",
    "Sofa foam replacement from ₹999 per cushion",
    "Wooden furniture polishing from ₹800",
    "Wardrobe hinge and runner repair from ₹599",
    "Recliner mechanism repair from ₹1,500",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Tilak Nagar",
      body: [
        "Tilak Nagar homes contain a typical West Delhi furniture mix — solid Indian-made sofas, sheesham wardrobes, dining sets from the Kirti Nagar market, and increasingly, electric recliners in the main drawing room. Our repair service covers all of these. For sofas, we replace foam, repair springs, and carry out full reupholstery in 40+ fabric options. For wooden furniture, we repair joints, replace hardware, and restore finishes using French polish, lacquer, or Danish oil. Wardrobes get hinge replacements, door realignment, and drawer runner repair. Recliners get mechanism and motor servicing. Our <a href='/sofa-repair-west-delhi'>West Delhi sofa repair</a> and <a href='/recliner-repair-west-delhi'>West Delhi recliner repair</a> pages cover these services in detail.",
        "Tilak Nagar's proximity to the Kirti Nagar furniture market means residents are well-informed about furniture quality and pricing. Our repair costs are consistently competitive with market-rate informal labour — but with trained craftsmen, written quotes, and a 6-month warranty. One booking covers multiple items at your address, making a FurniRevive visit the most efficient way to address all furniture needs at once.",
      ],
    },
  ],
  faqs: [
    { question: "What furniture types do you repair in Tilak Nagar?", answer: "We repair all home furniture: sofas, wooden furniture, wardrobes, dining sets, recliners, beds, chairs, and storage units. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Tilak Nagar?", answer: "Furniture repair from ₹599, sofa foam from ₹999/cushion, reupholstery from ₹3,000/seat, polishing from ₹800, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "Do you offer home visits in Tilak Nagar?", answer: "Yes. We repair at your home — DDA flat, society flat, or independent floor. No transport needed." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-tilak-nagar", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Tilak Nagar", href: "/sofa-repair-tilak-nagar" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Furniture Repair Kirti Nagar", href: "/furniture-repair-kirti-nagar" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair tilak nagar", "sofa repair tilak nagar", "wardrobe repair tilak nagar", "wooden furniture repair tilak nagar", "furniture repair west delhi"],
};

const furnitureRepairRajouriGarden: SeoPageData = {
  slug: "furniture-repair-rajouri-garden",
  title: "Furniture Repair in Rajouri Garden Delhi – FurniRevive | Sofa, Leather & Recliner Repair",
  metaDescription: "Expert furniture repair in Rajouri Garden, West Delhi. Leather sofas, imported recliners, wooden furniture & wardrobes. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Rajouri Garden – Premium & Designer Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Rajouri Garden — leather sofas, imported recliners, designer wardrobes & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Rajouri Garden) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Rajouri Garden) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Rajouri Garden, West Delhi. Leather sofa repair from ₹1,200, recliner mechanism repair from ₹1,500, wooden furniture polishing from ₹800, wardrobe repair from ₹599. All work done at your home with a 6-month warranty.",
  intro: [
    "Rajouri Garden is one of West Delhi's most prominent residential and commercial addresses, situated near Ring Road and the Pacific Mall catchment. Independent floors here frequently contain imported and designer furniture — Italian leather sofas, European recliner sets, lacquered wardrobes, and solid wood dining tables sourced from the adjacent Kirti Nagar furniture market. When premium furniture in a Rajouri Garden home needs repair, FurniRevive's trained craftsmen provide the expertise required.",
    "We handle all furniture repair in Rajouri Garden: leather and fabric sofa repair, foam replacement, full reupholstery, recliner mechanism and motor servicing, wooden furniture polishing and joint restoration, wardrobe hinge and runner replacement, and dining set refinishing — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> places Rajouri Garden among its priority coverage zones.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Expertise With Premium & Imported Furniture", description: "Our craftsmen are experienced with Italian leather, European recliner mechanisms, lacquered surfaces, and imported hardware — the furniture types common in Rajouri Garden." },
    { title: "Home Visit to Your Floor or Apartment", description: "We come to your Rajouri Garden address with all tools and materials. No transport risk for your premium pieces." },
    { title: "Transparent Pricing", description: "Leather sofa repair from ₹1,200, recliner repair from ₹1,500, polishing from ₹800, wardrobe repair from ₹599. Written quote before work starts." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Rajouri Garden address and furniture details. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces — including any imported or designer items — and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Complex jobs may require a brief workshop transit confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Rajouri Garden — all types in one booking",
    "Expertise with leather, imported, and designer furniture",
    "Home visit service — no transport risk for premium pieces",
    "Transparent written quote before work starts",
    "Leather sofa repair from ₹1,200",
    "Recliner mechanism and motor repair from ₹1,500",
    "Wooden furniture polishing from ₹800",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Rajouri Garden",
      body: [
        "Rajouri Garden's independent floors and housing societies contain a high concentration of premium furniture. Leather sofas — Italian and domestic — are common and require specialist leather cleaning, conditioning, and colour restoration that standard upholstery repair shops cannot provide. Imported electric recliners need technicians familiar with European and Chinese mechanism components. Our <a href='/sofa-repair-rajouri-garden'>Rajouri Garden sofa repair</a> and <a href='/recliner-repair-rajouri-garden'>Rajouri Garden recliner repair</a> pages detail these services.",
        "Being adjacent to the Kirti Nagar furniture market, Rajouri Garden residents have easy access to quality furniture — and informed expectations about repair quality and pricing. FurniRevive matches that expectation: trained craftsmen, original or equivalent-grade materials, and a 6-month written warranty on every job. One booking can cover all furniture at your address, making it the most efficient way to restore your home's full complement of furniture.",
      ],
    },
  ],
  faqs: [
    { question: "Do you repair leather sofas in Rajouri Garden?", answer: "Yes. We repair leather sofas — Italian and domestic — including leather cleaning, conditioning, colour restoration, foam replacement, and full reupholstery in leather or premium fabric." },
    { question: "Can you service imported recliners in Rajouri Garden?", answer: "Yes. Our technicians are trained on European and Chinese recliner mechanisms and motors common in imported recliners found in Rajouri Garden homes." },
    { question: "How much does furniture repair cost in Rajouri Garden?", answer: "Leather sofa repair from ₹1,200, recliner repair from ₹1,500, polishing from ₹800, wardrobe repair from ₹599. Written quote after free on-site inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-rajouri-garden", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Rajouri Garden", href: "/sofa-repair-rajouri-garden" },
    { label: "Recliner Repair Rajouri Garden", href: "/recliner-repair-rajouri-garden" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair rajouri garden", "sofa repair rajouri garden", "recliner repair rajouri garden", "leather sofa repair rajouri garden", "furniture repair west delhi"],
};

const furnitureRepairPaschimVihar: SeoPageData = {
  slug: "furniture-repair-paschim-vihar",
  title: "Furniture Repair in Paschim Vihar Delhi – FurniRevive | Sofa, Recliner & Wardrobe Repair",
  metaDescription: "Expert furniture repair in Paschim Vihar, West Delhi. Sofa foam, electric recliners, wooden furniture & wardrobes. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Paschim Vihar – All Home Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Paschim Vihar — sofas, electric recliners, wardrobes & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Paschim Vihar) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Paschim Vihar) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Paschim Vihar, West Delhi. Sofa foam replacement from ₹999, recliner repair from ₹1,500, wooden furniture polishing from ₹800, wardrobe repair from ₹599. All work done at your home with a 6-month warranty.",
  intro: [
    "Paschim Vihar is one of West Delhi's most rapidly developing localities, with newer apartment buildings, housing societies, and builder floors replacing older plotted housing at pace. The growing resident base has a high rate of premium furniture ownership — modular wardrobes, fabric and leather sectional sofas, and electric recliners are now standard in many Paschim Vihar homes. FurniRevive's home-visit repair service is built for exactly this locality.",
    "We handle all furniture repair in Paschim Vihar: sofa foam and spring replacement, full reupholstery, electric recliner mechanism and motor servicing, wooden furniture polishing and joint repair, wardrobe hinge and runner replacement, and dining set restoration — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers Paschim Vihar as a growing priority zone.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Electric Recliner Expertise", description: "Paschim Vihar's newer homes commonly feature electric recliners. Our technicians are trained on all major recliner mechanism and motor types — domestic and imported." },
    { title: "Home Visit Across Paschim Vihar", description: "We come to your apartment, housing society, or builder floor with all tools and materials. No transport required." },
    { title: "Transparent Pricing", description: "Furniture repair from ₹599, sofa foam from ₹999/cushion, recliner repair from ₹1,500, polishing from ₹800. Written quote before work starts." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Paschim Vihar address and furniture details. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Complex jobs may require a brief workshop transit confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Paschim Vihar — all types in one booking",
    "Electric recliner mechanism and motor repair from ₹1,500",
    "Home visit service — no transport required",
    "Transparent written quote before work starts",
    "Sofa foam replacement from ₹999 per cushion",
    "Wooden furniture polishing from ₹800",
    "Wardrobe hinge and runner repair from ₹599",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Paschim Vihar",
      body: [
        "Paschim Vihar's newer residential developments have driven a significant increase in premium furniture ownership across the locality. Residents increasingly own electric recliners — single-motor and dual-motor models from brands like La-Z-Boy, Durian, and various imported options — alongside modular wardrobes and fabric sectional sofas. Our <a href='/sofa-repair-paschim-vihar'>Paschim Vihar sofa repair</a> and <a href='/recliner-repair-paschim-vihar'>Paschim Vihar recliner repair</a> services address the most common repair needs in the locality.",
        "For sofas, we replace foam and springs, repair frames, and carry out full reupholstery in 40+ fabric and leather options. For wooden furniture, we restore joints, replace hardware, and refinish surfaces. Wardrobes get hinge replacements, door realignment, and drawer runner repair. Electric recliners receive thorough mechanism inspection, motor testing, and component-level repair where possible before replacement. One booking covers all items at your Paschim Vihar address.",
      ],
    },
  ],
  faqs: [
    { question: "Do you repair electric recliners in Paschim Vihar?", answer: "Yes. We repair all electric recliner types — single-motor, dual-motor, USB-charging models — covering mechanism inspection, motor testing, and component repair or replacement." },
    { question: "What furniture types do you repair in Paschim Vihar?", answer: "We repair all home furniture: sofas, recliners, wooden furniture, wardrobes, dining sets, beds, and storage units. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Paschim Vihar?", answer: "Furniture repair from ₹599, sofa foam from ₹999/cushion, recliner repair from ₹1,500, polishing from ₹800. Written quote after free inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-paschim-vihar", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Paschim Vihar", href: "/sofa-repair-paschim-vihar" },
    { label: "Recliner Repair Paschim Vihar", href: "/recliner-repair-paschim-vihar" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair paschim vihar", "sofa repair paschim vihar", "recliner repair paschim vihar", "wardrobe repair paschim vihar", "furniture repair west delhi"],
};

const furnitureRepairPunjabiBagh: SeoPageData = {
  slug: "furniture-repair-punjabi-bagh",
  title: "Furniture Repair in Punjabi Bagh Delhi – FurniRevive | Luxury, Antique & Designer Furniture",
  metaDescription: "Expert furniture repair in Punjabi Bagh, West Delhi. Italian leather sofas, European wardrobes, antiques & designer furniture. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Punjabi Bagh – Luxury & Designer Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs premium furniture in Punjabi Bagh — Italian leather sofas, European wardrobes, antiques, imported recliners & bespoke pieces. Home visit. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Punjabi Bagh) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Punjabi Bagh) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Punjabi Bagh, West Delhi. Italian leather sofa repair from ₹1,500, antique furniture restoration from ₹2,000, European wardrobe repair from ₹800, recliner repair from ₹1,500. All work done at your home with a 6-month warranty.",
  intro: [
    "Punjabi Bagh is one of West Delhi's most affluent residential addresses, home to large independent houses with high-value furniture collections. Homes here contain Italian leather sofas, European designer wardrobes, antique teak and sheesham pieces, imported electric recliners, and bespoke dining sets — furniture that requires craftsmen with the expertise and materials to restore them correctly. FurniRevive specialises in exactly this category.",
    "We handle all furniture repair in Punjabi Bagh: Italian and domestic leather sofa repair and reupholstery, antique furniture restoration, European wardrobe hinge and mechanism repair, imported recliner servicing, and premium wooden furniture polishing and joint restoration — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> treats Punjabi Bagh as one of its premium service zones.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Expertise With Luxury & Antique Furniture", description: "Our craftsmen have specific training in Italian leather, antique wood restoration, European wardrobe mechanisms, and high-end imported recliners — the furniture types common in Punjabi Bagh." },
    { title: "Home Visit to Your Independent House", description: "We come to your Punjabi Bagh address with all specialist tools and materials. No transport risk for your high-value pieces." },
    { title: "Premium Materials Matched to Your Furniture", description: "We source premium leather, matching wood finishes, and European-grade hardware to ensure repairs match the original quality of your furniture." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Punjabi Bagh address and furniture details. We confirm an appointment with a senior craftsman same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our senior technician inspects all pieces — including antiques and imported items — and provides a fully itemised written quote with material specifications before work begins." },
    { step: "Repair at Your Home With Premium Materials", description: "Most repairs are completed at your address. Antique restoration or complex reupholstery may require workshop work confirmed in advance with full transport care." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Luxury and antique furniture expertise in Punjabi Bagh",
    "Italian leather sofa repair and colour restoration",
    "Antique teak and sheesham furniture restoration",
    "European wardrobe mechanism and hinge repair",
    "Imported recliner mechanism and motor servicing",
    "Premium materials matched to original furniture quality",
    "Home visit service — no transport risk for high-value pieces",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Punjabi Bagh",
      body: [
        "Punjabi Bagh homes house some of the finest residential furniture collections in West Delhi. Italian leather sofas — Natuzzi, Nicoletti, and bespoke imports — require specialist leather technicians for colour matching, conditioning, and structural repair. Antique sheesham and teak pieces need craftsmen trained in traditional joinery and period-appropriate finishing. European wardrobes and storage systems use proprietary hinge and runner hardware that generic repair shops cannot source or install correctly. Our <a href='/sofa-repair-punjabi-bagh'>Punjabi Bagh sofa repair</a> and <a href='/recliner-repair-punjabi-bagh'>Punjabi Bagh recliner repair</a> services are calibrated to this standard.",
        "We approach every Punjabi Bagh job with the care that high-value furniture demands. Our technicians carry premium leather dyes, matching wood stains and lacquers, European-grade hinge and runner hardware, and high-density foam grades to match your original specifications. Written quotes detail every material and step. The 6-month warranty reflects our confidence in the quality of every repair we complete.",
      ],
    },
  ],
  faqs: [
    { question: "Do you repair antique furniture in Punjabi Bagh?", answer: "Yes. We restore antique teak and sheesham furniture — joint repair, traditional joinery, period-appropriate finishing, and hardware replacement where required." },
    { question: "Can you repair Italian leather sofas in Punjabi Bagh?", answer: "Yes. We repair Italian leather sofas including Natuzzi and other imports — leather cleaning, conditioning, colour restoration, foam replacement, and structural repair." },
    { question: "How much does luxury furniture repair cost in Punjabi Bagh?", answer: "Italian leather sofa repair from ₹1,500, antique restoration from ₹2,000, European wardrobe repair from ₹800, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-punjabi-bagh", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Punjabi Bagh", href: "/sofa-repair-punjabi-bagh" },
    { label: "Recliner Repair Punjabi Bagh", href: "/recliner-repair-punjabi-bagh" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair punjabi bagh", "sofa repair punjabi bagh", "antique furniture repair punjabi bagh", "leather sofa repair punjabi bagh", "furniture repair west delhi"],
};

const furnitureRepairSubhashNagar: SeoPageData = {
  slug: "furniture-repair-subhash-nagar",
  title: "Furniture Repair in Subhash Nagar Delhi – FurniRevive | Sofa, Wooden & Wardrobe Repair",
  metaDescription: "Expert furniture repair in Subhash Nagar, West Delhi. Sofa foam, wooden furniture, wardrobes & dining sets. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Subhash Nagar – All Home Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Subhash Nagar — sofas, wardrobes, dining sets, recliners & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Subhash Nagar) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Subhash Nagar) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Subhash Nagar, West Delhi. Sofa foam replacement from ₹999, wooden furniture polishing from ₹800, wardrobe repair from ₹599, and recliner repair from ₹1,500. All work done at your home with a 6-month warranty.",
  intro: [
    "Subhash Nagar is a compact, densely residential West Delhi locality with a mix of apartments and older plotted houses along its main lanes and quieter inner streets. Homes here predominantly contain mid-range Indian-made furniture — fabric sofas, sheesham or engineered wood wardrobes, dining sets, and standard beds — all of which experience regular wear and need periodic maintenance and repair. FurniRevive provides complete home-visit furniture repair across Subhash Nagar.",
    "We handle all furniture repair in Subhash Nagar: sofa foam and spring replacement, full reupholstery, wooden furniture polishing and joint repair, wardrobe hinge and runner replacement, dining set restoration, and recliner mechanism servicing — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers Subhash Nagar comprehensively.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Practical, Affordable Repairs for Indian-Made Furniture", description: "We specialise in the fabric sofas, sheesham wardrobes, and standard dining sets common in Subhash Nagar homes — with competitive pricing and no hidden costs." },
    { title: "Home Visit Across Subhash Nagar", description: "We come to your apartment or plotted house with all tools and materials. No transport, no disruption." },
    { title: "Transparent Pricing", description: "Furniture repair from ₹599, sofa foam from ₹999/cushion, full reupholstery from ₹3,000/seat, polishing from ₹800. Written quote before work starts." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Subhash Nagar address and furniture details. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Complex jobs may require a brief workshop transit confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Subhash Nagar — all types in one booking",
    "Competitive pricing for standard Indian-made furniture",
    "Home visit service — no transport required",
    "Transparent written quote before work starts",
    "Sofa foam replacement from ₹999 per cushion",
    "Wooden furniture polishing from ₹800",
    "Wardrobe hinge and runner repair from ₹599",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Subhash Nagar",
      body: [
        "Subhash Nagar's residential mix of apartments and older plotted houses contains a typical range of mid-range Indian-made furniture. Fabric sofas with sagging foam and worn fabric, sheesham or engineered-wood wardrobes with broken hinges or stuck drawers, and dining chairs with loose joints are among the most common repair requests we receive from this locality. Our service addresses all of these efficiently in a single home visit.",
        "For sofas, we replace foam in all grades, repair springs, and carry out full reupholstery in 40+ fabric options at competitive pricing. For wooden furniture, we repair joints, replace door and drawer hardware, and restore finishes. Wardrobes get hinge replacements, door realignment, and runner repair. Our <a href='/sofa-repair-subhash-nagar'>Subhash Nagar sofa repair</a> and <a href='/recliner-repair-subhash-nagar'>Subhash Nagar recliner repair</a> pages detail the most common services for this locality.",
      ],
    },
  ],
  faqs: [
    { question: "What furniture types do you repair in Subhash Nagar?", answer: "We repair all home furniture: sofas, wooden furniture, wardrobes, dining sets, recliners, beds, chairs, and storage units. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Subhash Nagar?", answer: "Furniture repair from ₹599, sofa foam from ₹999/cushion, reupholstery from ₹3,000/seat, polishing from ₹800, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "Do you offer home visits in Subhash Nagar?", answer: "Yes. We repair at your home — apartment or plotted house. No transport needed." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-subhash-nagar", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Subhash Nagar", href: "/sofa-repair-subhash-nagar" },
    { label: "Recliner Repair Subhash Nagar", href: "/recliner-repair-subhash-nagar" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair subhash nagar", "sofa repair subhash nagar", "wardrobe repair subhash nagar", "wooden furniture repair subhash nagar", "furniture repair west delhi"],
};

const furnitureRepairTagoreGarden: SeoPageData = {
  slug: "furniture-repair-tagore-garden",
  title: "Furniture Repair in Tagore Garden Delhi – FurniRevive | Sofa, Teak & Wardrobe Repair",
  metaDescription: "Expert furniture repair in Tagore Garden, West Delhi. Teak antiques, market sofas, wooden furniture & wardrobes. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Tagore Garden – All Home Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Tagore Garden — teak antiques, sofas, wardrobes, recliners & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Tagore Garden) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Tagore Garden) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Tagore Garden, West Delhi. Sofa foam replacement from ₹999, teak furniture restoration from ₹1,200, wardrobe repair from ₹599, and recliner repair from ₹1,500. All work done at your home with a 6-month warranty.",
  intro: [
    "Tagore Garden sits immediately adjacent to the Kirti Nagar furniture market, making it one of West Delhi's most furniture-aware localities. Homes here range from older plotted houses with solid teak and sheesham antique furniture to newer builder floors with contemporary market purchases. The result is a wide furniture range — from century-old teak almirahs and dining suites to standard fabric sofas and modular wardrobes — all of which FurniRevive is equipped to repair.",
    "We handle all furniture repair in Tagore Garden: antique teak and sheesham restoration, sofa foam and spring replacement, full reupholstery, wardrobe hinge and runner repair, recliner mechanism servicing, and dining set refinishing — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers Tagore Garden as one of its primary zones.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Antique and Contemporary Expertise", description: "From century-old teak almirahs to standard market sofas, our craftsmen have the range to handle every furniture type found in Tagore Garden homes." },
    { title: "Adjacent to Kirti Nagar — Informed Pricing", description: "Tagore Garden residents know furniture pricing well. Our costs are transparent and competitive, with a written quote before any work begins." },
    { title: "Home Visit Across Tagore Garden", description: "We come to your plotted house or builder floor with all tools and materials. No transport, no disruption." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Tagore Garden address and furniture details. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces — including antiques — and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Antique restoration may require brief workshop work confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Tagore Garden — all types in one booking",
    "Antique teak and sheesham furniture restoration",
    "Standard sofa foam and spring replacement from ₹999",
    "Home visit service — no transport required",
    "Transparent written quote before work starts",
    "Wardrobe hinge and runner repair from ₹599",
    "Recliner mechanism repair from ₹1,500",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Tagore Garden",
      body: [
        "Tagore Garden's proximity to the Kirti Nagar furniture market has historically made it a locality where residents buy quality furniture and hold it for generations. Older plotted houses contain solid teak almirahs, period dining suites, and traditional settees — pieces that warrant expert restoration rather than replacement. Newer builder floors add contemporary sofas and modular wardrobes to the locality's furniture mix. Our craftsmen cover the full range.",
        "For antique teak and sheesham pieces, we repair loose joints using traditional mortise-and-tenon joinery where possible, source period-appropriate hardware, and restore finishes using French polish or appropriate period-matched lacquers. For contemporary sofas, we replace foam and springs, repair frames, and carry out full reupholstery. Our <a href='/sofa-repair-tagore-garden'>Tagore Garden sofa repair</a> and <a href='/recliner-repair-tagore-garden'>Tagore Garden recliner repair</a> pages cover the most common modern repair services.",
      ],
    },
  ],
  faqs: [
    { question: "Do you restore antique furniture in Tagore Garden?", answer: "Yes. We restore antique teak and sheesham furniture — joint repair, traditional joinery, French polish restoration, and period-appropriate hardware replacement." },
    { question: "What furniture types do you repair in Tagore Garden?", answer: "We repair all home furniture: antiques, sofas, wooden furniture, wardrobes, dining sets, recliners, beds, and storage units. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Tagore Garden?", answer: "Furniture repair from ₹599, sofa foam from ₹999/cushion, teak restoration from ₹1,200, wardrobe repair from ₹599, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-tagore-garden", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Tagore Garden", href: "/sofa-repair-tagore-garden" },
    { label: "Recliner Repair Tagore Garden", href: "/recliner-repair-tagore-garden" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair tagore garden", "sofa repair tagore garden", "antique furniture repair tagore garden", "wooden furniture repair tagore garden", "furniture repair west delhi"],
};

const furnitureRepairDelhiCantt: SeoPageData = {
  slug: "furniture-repair-delhi-cantt",
  title: "Furniture Repair in Delhi Cantt – FurniRevive | Sofa, Antique & Wooden Furniture Repair",
  metaDescription: "Expert furniture repair in Delhi Cantonment. Military family housing, bungalows, antique furniture & quality originals. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Delhi Cantt – Quality & Antique Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Delhi Cantonment — quality original pieces, antiques, sofas, wardrobes & recliners. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Delhi Cantt) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Delhi Cantt) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Delhi Cantt. Antique furniture restoration from ₹1,200, sofa foam replacement from ₹999, wooden furniture polishing from ₹800, wardrobe repair from ₹599. All work done at your home with a 6-month warranty.",
  intro: [
    "Delhi Cantonment is a distinctive residential area combining military family quarters, civilian housing, and older bungalows — many of which contain quality original furniture accumulated over decades of service postings. From solid teak and rosewood pieces acquired in the 1960s and 70s to government-issue furniture maintained through generations, Delhi Cantt homes hold furniture collections that deserve expert care rather than replacement. Some residences also contain genuine antiques and inherited pieces of significant value.",
    "We handle all furniture repair in Delhi Cantt: antique teak and rosewood restoration, sofa foam and spring replacement, full reupholstery, wooden furniture polishing and joint repair, wardrobe hinge and runner replacement, and recliner mechanism servicing — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers the cantonment area with specific sensitivity to its unique furniture requirements.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Expertise With Quality Original and Antique Pieces", description: "Our craftsmen understand the construction of solid teak, rosewood, and sheesham furniture from the mid-20th century — the types common in Delhi Cantt homes." },
    { title: "Respectful Handling of Inherited and Valued Pieces", description: "We approach every job with the care that furniture of personal, historical, or monetary value deserves. Detailed assessment and written quote before any work begins." },
    { title: "Home Visit to Your Quarter or Bungalow", description: "We come to your Delhi Cantt address — quarter, civilian flat, or bungalow — with all tools and materials. No transport risk." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Delhi Cantt address and furniture details. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our senior technician inspects all pieces — including antiques and inherited items — and provides a fully itemised written quote before any work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed at your address. Antique or complex restoration may require brief workshop work confirmed in advance with full transport care." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Antique teak and rosewood furniture restoration expertise",
    "Careful handling of inherited and valued pieces",
    "Home visit to military quarters, civilian flats, and bungalows",
    "Sofa foam replacement from ₹999 per cushion",
    "Wooden furniture polishing and joint repair from ₹800",
    "Wardrobe hinge and runner repair from ₹599",
    "Recliner mechanism repair from ₹1,500",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Delhi Cantonment",
      body: [
        "Delhi Cantonment's housing stock — built over many decades for officers, other ranks, and civilian staff — contains furniture that reflects the quality standards of its era. Solid teak almirahs, rosewood sideboards, substantial dining suites, and divan beds are common in older quarters and bungalows. These pieces were made to last and deserve restoration by craftsmen who understand their construction. Our approach to Delhi Cantt jobs prioritises reversible repairs, period-appropriate finishes, and original joinery techniques where possible.",
        "For antique and quality original pieces, we carry matching wood stains, French polish materials, traditional joinery hardware, and high-grade leather and fabric for reupholstery. For contemporary additions — newer sofas, modular wardrobes, electric recliners — we apply the same standards: written quote, quality materials, and 6-month warranty. Our <a href='/sofa-repair-delhi-cantt'>Delhi Cantt sofa repair</a> and <a href='/recliner-repair-delhi-cantt'>Delhi Cantt recliner repair</a> pages cover the most common modern repair needs.",
      ],
    },
  ],
  faqs: [
    { question: "Do you repair antique furniture in Delhi Cantt?", answer: "Yes. We restore antique teak, rosewood, and sheesham furniture — joint repair, French polish restoration, period-appropriate hardware, and reversible techniques where possible." },
    { question: "What furniture types do you repair in Delhi Cantt?", answer: "We repair all home furniture: antiques, sofas, wooden furniture, wardrobes, dining sets, recliners, and beds. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Delhi Cantt?", answer: "Antique restoration from ₹1,200, sofa foam from ₹999/cushion, polishing from ₹800, wardrobe repair from ₹599, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-delhi-cantt", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Delhi Cantt", href: "/sofa-repair-delhi-cantt" },
    { label: "Recliner Repair Delhi Cantt", href: "/recliner-repair-delhi-cantt" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair delhi cantt", "sofa repair delhi cantt", "antique furniture repair delhi cantt", "wooden furniture repair delhi cantt", "furniture repair west delhi"],
};

const furnitureRepairUttamNagar: SeoPageData = {
  slug: "furniture-repair-uttam-nagar",
  title: "Furniture Repair in Uttam Nagar Delhi – FurniRevive | Sofa, Wooden & Wardrobe Repair",
  metaDescription: "Expert furniture repair in Uttam Nagar, West Delhi. Sofa foam, wooden furniture, wardrobes & dining sets. Home visit from ₹599. 6-month warranty. Call FurniRevive.",
  h1: "Furniture Repair in Uttam Nagar – All Home Furniture Restored at Your Door",
  heroSubtitle: "FurniRevive repairs all furniture in Uttam Nagar — sofas, wardrobes, dining sets, recliners & wooden furniture. Home visit. Transparent pricing. 6-month warranty.",
  showcaseImage: {
    heading: "Premium Sofa Repair — Expert Service at Your West Delhi Home",
    imageUrl: "https://hercules-cdn.com/file_E4RyzbNs65laSB9mK3GXEsnp",
    altText: "Professional sofa repair technician working on a light grey premium fabric sofa in a luxury West Delhi (Uttam Nagar) home — FurniRevive",
    caption: "Furniture Repair in West Delhi (Uttam Nagar) | Premium upholstery & foam service | Home visit | FurniRevive",
  },
  quickAnswer: "FurniRevive provides complete furniture repair in Uttam Nagar, West Delhi. Sofa foam replacement from ₹999, wooden furniture polishing from ₹800, wardrobe repair from ₹599, and recliner repair from ₹1,500. All work done at your home with a 6-month warranty.",
  intro: [
    "Uttam Nagar is one of Delhi's busiest and most densely populated residential markets, with a high concentration of furniture shops near the metro station and throughout the colony's main roads. DDA colonies dominate the housing stock, alongside older plotted houses and joint-family homes with large, multi-set sofa arrangements. Residents here are price-aware and well-informed — they know what repairs should cost and expect transparent, honest service.",
    "We handle all furniture repair in Uttam Nagar: sofa foam and spring replacement for large joint-family sets, full reupholstery in 40+ fabric options, wooden furniture polishing and joint repair, wardrobe hinge and runner replacement, dining set restoration, and recliner mechanism servicing — all at your address. Our <a href='/furniture-repair-west-delhi'>West Delhi furniture repair service</a> covers Uttam Nagar as one of its highest-demand zones.",
    "For pricing context, see our <a href='/sofa-repair-cost-delhi'>sofa repair cost guide</a>. To book, call or WhatsApp +91 92179 99355.",
  ],
  whyChoose: [
    { title: "Transparent Pricing for Price-Aware Residents", description: "Uttam Nagar residents know furniture pricing. Our costs are transparent and itemised — written quote before work starts, no hidden charges, no revisions at the end." },
    { title: "Joint-Family Sofa Expertise", description: "Large L-shaped and multi-piece sofa sets common in Uttam Nagar joint-family homes are our speciality — full foam replacement, spring repair, and reupholstery." },
    { title: "Home Visit Across Uttam Nagar", description: "We come to your DDA flat, plotted house, or independent floor with all tools and materials. No transport required." },
    { title: "6-Month Warranty", description: "All repairs carry a 6-month workmanship warranty with digital certificate via WhatsApp." },
  ],
  process: [
    { step: "Call or WhatsApp to Book", description: "Contact FurniRevive at +91 92179 99355 with your Uttam Nagar address and the furniture pieces that need attention. We confirm an appointment same day or next morning." },
    { step: "On-Site Assessment and Written Quote", description: "Our technician inspects all pieces and provides a fully itemised written quote before work begins." },
    { step: "Repair at Your Home", description: "Most repairs are completed in a single home visit. Complex jobs may require a brief workshop transit confirmed in advance." },
    { step: "Handover With 6-Month Warranty", description: "You inspect every repaired piece. Your digital warranty certificate arrives via WhatsApp before the technician leaves." },
  ],
  benefits: [
    "Complete furniture repair in Uttam Nagar — all types in one booking",
    "Transparent written pricing — no surprises",
    "Large joint-family sofa set repair and reupholstery",
    "Home visit to DDA flats, plotted houses, and independent floors",
    "Sofa foam replacement from ₹999 per cushion",
    "Wooden furniture polishing from ₹800",
    "Wardrobe hinge and runner repair from ₹599",
    "6-month workmanship warranty on all repairs",
  ],
  contentSections: [
    {
      heading: "Furniture Repair Services in Uttam Nagar",
      body: [
        "Uttam Nagar's DDA colonies and joint-family homes contain some of the largest sofa sets in West Delhi. Multi-piece arrangements — 3+2+1 sets and large L-shaped sectionals — with sagging foam, broken springs, and worn fabric are among the most common repair requests we receive from this locality. Our teams are experienced with large-set work: systematic foam replacement to consistent density across all cushions, spring retying or replacement, and reupholstery in matched fabric across all pieces. Our <a href='/sofa-repair-uttam-nagar'>Uttam Nagar sofa repair</a> page covers this in detail.",
        "Beyond sofas, Uttam Nagar homes contain wooden almirahs, sheesham dining sets, and standard wardrobes from the many local furniture markets. We repair all of these in the same home visit: joint repair and polishing for wooden pieces, hinge and runner replacement for wardrobes, and mechanism and motor servicing for any recliners in the home. Uttam Nagar residents are well-placed to compare pricing — our written quotes hold firm and are consistently competitive with local workshop rates.",
      ],
    },
  ],
  faqs: [
    { question: "Do you repair large joint-family sofa sets in Uttam Nagar?", answer: "Yes. We specialise in large 3+2+1 and L-shaped sets common in Uttam Nagar homes — full foam replacement to consistent density, spring repair, and reupholstery across all pieces." },
    { question: "What furniture types do you repair in Uttam Nagar?", answer: "We repair all home furniture: sofas, wooden furniture, wardrobes, dining sets, recliners, beds, chairs, and storage units. One booking covers multiple pieces." },
    { question: "How much does furniture repair cost in Uttam Nagar?", answer: "Furniture repair from ₹599, sofa foam from ₹999/cushion, reupholstery from ₹3,000/seat, polishing from ₹800, recliner repair from ₹1,500. Written quote after free inspection." },
    { question: "What warranty do you provide?", answer: "All repairs carry a 6-month workmanship warranty. If any fault appears within six months, we return and fix it free of charge." },
  ],
  relatedPages: buildRelatedPages("furniture-repair-uttam-nagar", [
    { label: "Furniture Repair West Delhi", href: "/furniture-repair-west-delhi" },
    { label: "Sofa Repair Uttam Nagar", href: "/sofa-repair-uttam-nagar" },
    { label: "Furniture Repair Vikaspuri", href: "/furniture-repair-vikaspuri" },
    { label: "Sofa Repair West Delhi", href: "/sofa-repair-west-delhi" },
    { label: "Recliner Repair West Delhi", href: "/recliner-repair-west-delhi" },
    { label: "Furniture Repair Delhi", href: "/furniture-repair-delhi" },
    { label: "Areas We Serve", href: "/areas-we-serve" },
  ]),
  keywords: ["furniture repair uttam nagar", "sofa repair uttam nagar", "wardrobe repair uttam nagar", "wooden furniture repair uttam nagar", "furniture repair west delhi"],
};

export const WEST_DELHI_FURNITURE_LOCALITY_PAGES: SeoPageData[] = [
  furnitureRepairTilakNagar,
  furnitureRepairRajouriGarden,
  furnitureRepairPaschimVihar,
  furnitureRepairPunjabiBagh,
  furnitureRepairSubhashNagar,
  furnitureRepairTagoreGarden,
  furnitureRepairDelhiCantt,
  furnitureRepairUttamNagar,
];
