/**
 * Programmatic Sector Pages — FurniRevive SEO
 *
 * Minimal SeoPageData stubs for the 10 programmatic pipeline pages.
 * These register each page slug in ALL_SEO_PAGES so the sitemap generator,
 * internal linking, and getPageBySlug() can find them.
 *
 * Why stubs instead of full pipeline data:
 * The full pipeline (buildSeoPageData → create-seo-page.ts → page-composition-engine.ts
 * → location-graph.ts) imports ALL_SEO_PAGES from registry.ts at module load time,
 * creating a circular dependency when this file is spread into ALL_SEO_PAGES.
 * The page components call createSeoPage() themselves at render time and get
 * the full pipeline output (hero, FAQs, etc.) there.
 *
 * The registry only needs slug + title + metaDescription for lookups and sitemap.
 * All other fields are set to safe empty defaults.
 *
 * To add a new programmatic page:
 *   1. Create the page component in src/pages/services/programmatic/
 *   2. Add the locality to LocalitySlug union in repair-scenarios.ts
 *   3. Add an entry here (copy the pattern below)
 *   4. Add the Route in App.tsx
 *   5. Run: pnpm generate-sitemap
 */

import type { SeoPageData } from "@/lib/seo-constants.ts";

function stub(slug: string, title: string, h1: string): SeoPageData {
  return {
    slug,
    title,
    metaDescription: title,
    h1,
    heroSubtitle: "",
    intro: [],
    whyChoose: [],
    process: [],
    benefits: [],
    contentSections: [],
    relatedPages: [],
    faqs: [],
  } as unknown as SeoPageData;
}

export const PROGRAMMATIC_SECTOR_PAGES: SeoPageData[] = [
  stub("sofa-repair-new-gurgaon",         "Sofa Repair in New Gurgaon",    "Sofa Repair in New Gurgaon"),
  stub("sofa-repair-sector-49-gurgaon",   "Sofa Repair in Sector 49",      "Sofa Repair in Sector 49"),
  stub("sofa-repair-sector-50-gurgaon",   "Sofa Repair in Sector 50",      "Sofa Repair in Sector 50"),
  stub("sofa-repair-sector-56-gurgaon",   "Sofa Repair in Sector 56",      "Sofa Repair in Sector 56"),
  stub("sofa-repair-sector-57-gurgaon",   "Sofa Repair in Sector 57",      "Sofa Repair in Sector 57"),
  stub("sofa-repair-sector-58-gurgaon",   "Sofa Repair in Sector 58",      "Sofa Repair in Sector 58"),
  stub("sofa-repair-sector-65-gurgaon",   "Sofa Repair in Sector 65",      "Sofa Repair in Sector 65"),
  stub("sofa-repair-sector-67-gurgaon",        "Sofa Repair in Sector 67",           "Sofa Repair in Sector 67"),
  stub("sofa-repair-sector-70-gurgaon",        "Sofa Repair in Sector 70",           "Sofa Repair in Sector 70"),
  stub("sofa-repair-sector-71-gurgaon",        "Sofa Repair in Sector 71",           "Sofa Repair in Sector 71"),
  stub("recliner-repair-sector-67-gurgaon",    "Recliner Repair in Sector 67",       "Recliner Repair in Sector 67"),
  stub("recliner-repair-sector-70-gurgaon",    "Recliner Repair in Sector 70",       "Recliner Repair in Sector 70"),
  stub("recliner-repair-sector-71-gurgaon",    "Recliner Repair in Sector 71",       "Recliner Repair in Sector 71"),
  stub("furniture-repair-sector-67-gurgaon",   "Furniture Repair in Sector 67",      "Furniture Repair in Sector 67"),
  stub("furniture-repair-sector-70-gurgaon",   "Furniture Repair in Sector 70",      "Furniture Repair in Sector 70"),
  stub("furniture-repair-sector-71-gurgaon",   "Furniture Repair in Sector 71",      "Furniture Repair in Sector 71"),
  // Golf Course Extension + sectors 51, 59–64, 66, 68–69 — sofa, recliner, furniture
  stub("sofa-repair-golf-course-extension-gurgaon",      "Sofa Repair in Golf Course Extension",      "Sofa Repair in Golf Course Extension"),
  stub("sofa-repair-sector-51-gurgaon",                  "Sofa Repair in Sector 51",                  "Sofa Repair in Sector 51"),
  stub("sofa-repair-sector-59-gurgaon",                  "Sofa Repair in Sector 59",                  "Sofa Repair in Sector 59"),
  stub("sofa-repair-sector-60-gurgaon",                  "Sofa Repair in Sector 60",                  "Sofa Repair in Sector 60"),
  stub("sofa-repair-sector-61-gurgaon",                  "Sofa Repair in Sector 61",                  "Sofa Repair in Sector 61"),
  stub("sofa-repair-sector-62-gurgaon",                  "Sofa Repair in Sector 62",                  "Sofa Repair in Sector 62"),
  stub("sofa-repair-sector-63-gurgaon",                  "Sofa Repair in Sector 63",                  "Sofa Repair in Sector 63"),
  stub("sofa-repair-sector-64-gurgaon",                  "Sofa Repair in Sector 64",                  "Sofa Repair in Sector 64"),
  stub("sofa-repair-sector-66-gurgaon",                  "Sofa Repair in Sector 66",                  "Sofa Repair in Sector 66"),
  stub("sofa-repair-sector-68-gurgaon",                  "Sofa Repair in Sector 68",                  "Sofa Repair in Sector 68"),
  stub("sofa-repair-sector-69-gurgaon",                  "Sofa Repair in Sector 69",                  "Sofa Repair in Sector 69"),
  stub("recliner-repair-golf-course-extension-gurgaon",  "Recliner Repair in Golf Course Extension",  "Recliner Repair in Golf Course Extension"),
  stub("recliner-repair-sector-51-gurgaon",              "Recliner Repair in Sector 51",              "Recliner Repair in Sector 51"),
  stub("recliner-repair-sector-59-gurgaon",              "Recliner Repair in Sector 59",              "Recliner Repair in Sector 59"),
  stub("recliner-repair-sector-60-gurgaon",              "Recliner Repair in Sector 60",              "Recliner Repair in Sector 60"),
  stub("recliner-repair-sector-61-gurgaon",              "Recliner Repair in Sector 61",              "Recliner Repair in Sector 61"),
  stub("recliner-repair-sector-62-gurgaon",              "Recliner Repair in Sector 62",              "Recliner Repair in Sector 62"),
  stub("recliner-repair-sector-63-gurgaon",              "Recliner Repair in Sector 63",              "Recliner Repair in Sector 63"),
  stub("recliner-repair-sector-64-gurgaon",              "Recliner Repair in Sector 64",              "Recliner Repair in Sector 64"),
  stub("recliner-repair-sector-66-gurgaon",              "Recliner Repair in Sector 66",              "Recliner Repair in Sector 66"),
  stub("recliner-repair-sector-68-gurgaon",              "Recliner Repair in Sector 68",              "Recliner Repair in Sector 68"),
  stub("recliner-repair-sector-69-gurgaon",              "Recliner Repair in Sector 69",              "Recliner Repair in Sector 69"),
  stub("furniture-repair-golf-course-extension-gurgaon", "Furniture Repair in Golf Course Extension", "Furniture Repair in Golf Course Extension"),
  stub("furniture-repair-sector-51-gurgaon",             "Furniture Repair in Sector 51",             "Furniture Repair in Sector 51"),
  stub("furniture-repair-sector-59-gurgaon",             "Furniture Repair in Sector 59",             "Furniture Repair in Sector 59"),
  stub("furniture-repair-sector-60-gurgaon",             "Furniture Repair in Sector 60",             "Furniture Repair in Sector 60"),
  stub("furniture-repair-sector-61-gurgaon",             "Furniture Repair in Sector 61",             "Furniture Repair in Sector 61"),
  stub("furniture-repair-sector-62-gurgaon",             "Furniture Repair in Sector 62",             "Furniture Repair in Sector 62"),
  stub("furniture-repair-sector-63-gurgaon",             "Furniture Repair in Sector 63",             "Furniture Repair in Sector 63"),
  stub("furniture-repair-sector-64-gurgaon",             "Furniture Repair in Sector 64",             "Furniture Repair in Sector 64"),
  stub("furniture-repair-sector-66-gurgaon",             "Furniture Repair in Sector 66",             "Furniture Repair in Sector 66"),
  stub("furniture-repair-sector-68-gurgaon",             "Furniture Repair in Sector 68",             "Furniture Repair in Sector 68"),
  stub("furniture-repair-sector-69-gurgaon",             "Furniture Repair in Sector 69",             "Furniture Repair in Sector 69"),
  // Batch A — New Gurgaon, Sectors 72–81, Dwarka Expressway
  stub("sofa-repair-sector-72-gurgaon",                  "Sofa Repair in Sector 72",                  "Sofa Repair in Sector 72"),
  stub("sofa-repair-sector-73-gurgaon",                  "Sofa Repair in Sector 73",                  "Sofa Repair in Sector 73"),
  stub("sofa-repair-sector-74-gurgaon",                  "Sofa Repair in Sector 74",                  "Sofa Repair in Sector 74"),
  stub("sofa-repair-sector-75-gurgaon",                  "Sofa Repair in Sector 75",                  "Sofa Repair in Sector 75"),
  stub("sofa-repair-sector-76-gurgaon",                  "Sofa Repair in Sector 76",                  "Sofa Repair in Sector 76"),
  stub("sofa-repair-sector-77-gurgaon",                  "Sofa Repair in Sector 77",                  "Sofa Repair in Sector 77"),
  stub("sofa-repair-sector-78-gurgaon",                  "Sofa Repair in Sector 78",                  "Sofa Repair in Sector 78"),
  stub("sofa-repair-sector-79-gurgaon",                  "Sofa Repair in Sector 79",                  "Sofa Repair in Sector 79"),
  stub("sofa-repair-sector-80-gurgaon",                  "Sofa Repair in Sector 80",                  "Sofa Repair in Sector 80"),
  stub("sofa-repair-sector-81-gurgaon",                  "Sofa Repair in Sector 81",                  "Sofa Repair in Sector 81"),
  stub("sofa-repair-dwarka-expressway-gurgaon",          "Sofa Repair in Dwarka Expressway",          "Sofa Repair in Dwarka Expressway"),
  stub("recliner-repair-new-gurgaon",                    "Recliner Repair in New Gurgaon",            "Recliner Repair in New Gurgaon"),
  stub("recliner-repair-sector-72-gurgaon",              "Recliner Repair in Sector 72",              "Recliner Repair in Sector 72"),
  stub("recliner-repair-sector-73-gurgaon",              "Recliner Repair in Sector 73",              "Recliner Repair in Sector 73"),
  stub("recliner-repair-sector-74-gurgaon",              "Recliner Repair in Sector 74",              "Recliner Repair in Sector 74"),
  stub("recliner-repair-sector-75-gurgaon",              "Recliner Repair in Sector 75",              "Recliner Repair in Sector 75"),
  stub("recliner-repair-sector-76-gurgaon",              "Recliner Repair in Sector 76",              "Recliner Repair in Sector 76"),
  stub("recliner-repair-sector-77-gurgaon",              "Recliner Repair in Sector 77",              "Recliner Repair in Sector 77"),
  stub("recliner-repair-sector-78-gurgaon",              "Recliner Repair in Sector 78",              "Recliner Repair in Sector 78"),
  stub("recliner-repair-sector-79-gurgaon",              "Recliner Repair in Sector 79",              "Recliner Repair in Sector 79"),
  stub("recliner-repair-sector-80-gurgaon",              "Recliner Repair in Sector 80",              "Recliner Repair in Sector 80"),
  stub("recliner-repair-sector-81-gurgaon",              "Recliner Repair in Sector 81",              "Recliner Repair in Sector 81"),
  stub("recliner-repair-dwarka-expressway-gurgaon",      "Recliner Repair in Dwarka Expressway",      "Recliner Repair in Dwarka Expressway"),
  stub("furniture-repair-new-gurgaon",                   "Furniture Repair in New Gurgaon",           "Furniture Repair in New Gurgaon"),
  stub("furniture-repair-sector-72-gurgaon",             "Furniture Repair in Sector 72",             "Furniture Repair in Sector 72"),
  stub("furniture-repair-sector-73-gurgaon",             "Furniture Repair in Sector 73",             "Furniture Repair in Sector 73"),
  stub("furniture-repair-sector-74-gurgaon",             "Furniture Repair in Sector 74",             "Furniture Repair in Sector 74"),
  stub("furniture-repair-sector-75-gurgaon",             "Furniture Repair in Sector 75",             "Furniture Repair in Sector 75"),
  stub("furniture-repair-sector-76-gurgaon",             "Furniture Repair in Sector 76",             "Furniture Repair in Sector 76"),
  stub("furniture-repair-sector-77-gurgaon",             "Furniture Repair in Sector 77",             "Furniture Repair in Sector 77"),
  stub("furniture-repair-sector-78-gurgaon",             "Furniture Repair in Sector 78",             "Furniture Repair in Sector 78"),
  stub("furniture-repair-sector-79-gurgaon",             "Furniture Repair in Sector 79",             "Furniture Repair in Sector 79"),
  stub("furniture-repair-sector-80-gurgaon",             "Furniture Repair in Sector 80",             "Furniture Repair in Sector 80"),
  stub("furniture-repair-sector-81-gurgaon",             "Furniture Repair in Sector 81",             "Furniture Repair in Sector 81"),
  stub("furniture-repair-dwarka-expressway-gurgaon",     "Furniture Repair in Dwarka Expressway",     "Furniture Repair in Dwarka Expressway"),
  // Batch B — Sectors 82–90 + New Residential
  stub("sofa-repair-sector-82-gurgaon",                 "Sofa Repair in Sector 82",                  "Sofa Repair in Sector 82"),
  stub("sofa-repair-sector-82a-gurgaon",                "Sofa Repair in Sector 82A",                 "Sofa Repair in Sector 82A"),
  stub("sofa-repair-sector-83-gurgaon",                 "Sofa Repair in Sector 83",                  "Sofa Repair in Sector 83"),
  stub("sofa-repair-sector-84-gurgaon",                 "Sofa Repair in Sector 84",                  "Sofa Repair in Sector 84"),
  stub("sofa-repair-sector-85-gurgaon",                 "Sofa Repair in Sector 85",                  "Sofa Repair in Sector 85"),
  stub("sofa-repair-sector-86-gurgaon",                 "Sofa Repair in Sector 86",                  "Sofa Repair in Sector 86"),
  stub("sofa-repair-sector-87-gurgaon",                 "Sofa Repair in Sector 87",                  "Sofa Repair in Sector 87"),
  stub("sofa-repair-sector-88-gurgaon",                 "Sofa Repair in Sector 88",                  "Sofa Repair in Sector 88"),
  stub("sofa-repair-sector-89-gurgaon",                 "Sofa Repair in Sector 89",                  "Sofa Repair in Sector 89"),
  stub("sofa-repair-sector-90-gurgaon",                 "Sofa Repair in Sector 90",                  "Sofa Repair in Sector 90"),
  stub("sofa-repair-new-residential-gurgaon",           "Sofa Repair in New Residential Gurgaon",    "Sofa Repair in New Residential Gurgaon"),
  stub("recliner-repair-sector-82-gurgaon",             "Recliner Repair in Sector 82",              "Recliner Repair in Sector 82"),
  stub("recliner-repair-sector-82a-gurgaon",            "Recliner Repair in Sector 82A",             "Recliner Repair in Sector 82A"),
  stub("recliner-repair-sector-83-gurgaon",             "Recliner Repair in Sector 83",              "Recliner Repair in Sector 83"),
  stub("recliner-repair-sector-84-gurgaon",             "Recliner Repair in Sector 84",              "Recliner Repair in Sector 84"),
  stub("recliner-repair-sector-85-gurgaon",             "Recliner Repair in Sector 85",              "Recliner Repair in Sector 85"),
  stub("recliner-repair-sector-86-gurgaon",             "Recliner Repair in Sector 86",              "Recliner Repair in Sector 86"),
  stub("recliner-repair-sector-87-gurgaon",             "Recliner Repair in Sector 87",              "Recliner Repair in Sector 87"),
  stub("recliner-repair-sector-88-gurgaon",             "Recliner Repair in Sector 88",              "Recliner Repair in Sector 88"),
  stub("recliner-repair-sector-89-gurgaon",             "Recliner Repair in Sector 89",              "Recliner Repair in Sector 89"),
  stub("recliner-repair-sector-90-gurgaon",             "Recliner Repair in Sector 90",              "Recliner Repair in Sector 90"),
  stub("recliner-repair-new-residential-gurgaon",       "Recliner Repair in New Residential Gurgaon","Recliner Repair in New Residential Gurgaon"),
  stub("furniture-repair-sector-82-gurgaon",            "Furniture Repair in Sector 82",             "Furniture Repair in Sector 82"),
  stub("furniture-repair-sector-82a-gurgaon",           "Furniture Repair in Sector 82A",            "Furniture Repair in Sector 82A"),
  stub("furniture-repair-sector-83-gurgaon",            "Furniture Repair in Sector 83",             "Furniture Repair in Sector 83"),
  stub("furniture-repair-sector-84-gurgaon",            "Furniture Repair in Sector 84",             "Furniture Repair in Sector 84"),
  stub("furniture-repair-sector-85-gurgaon",            "Furniture Repair in Sector 85",             "Furniture Repair in Sector 85"),
  stub("furniture-repair-sector-86-gurgaon",            "Furniture Repair in Sector 86",             "Furniture Repair in Sector 86"),
  stub("furniture-repair-sector-87-gurgaon",            "Furniture Repair in Sector 87",             "Furniture Repair in Sector 87"),
  stub("furniture-repair-sector-88-gurgaon",            "Furniture Repair in Sector 88",             "Furniture Repair in Sector 88"),
  stub("furniture-repair-sector-89-gurgaon",            "Furniture Repair in Sector 89",             "Furniture Repair in Sector 89"),
  stub("furniture-repair-sector-90-gurgaon",            "Furniture Repair in Sector 90",             "Furniture Repair in Sector 90"),
  stub("furniture-repair-new-residential-gurgaon",      "Furniture Repair in New Residential Gurgaon","Furniture Repair in New Residential Gurgaon"),
  // Batch C — Sectors 91–111
  stub("sofa-repair-sector-91-gurgaon",                 "Sofa Repair in Sector 91",                  "Sofa Repair in Sector 91"),
  stub("sofa-repair-sector-92-gurgaon",                 "Sofa Repair in Sector 92",                  "Sofa Repair in Sector 92"),
  stub("sofa-repair-sector-93-gurgaon",                 "Sofa Repair in Sector 93",                  "Sofa Repair in Sector 93"),
  stub("sofa-repair-sector-95-gurgaon",                 "Sofa Repair in Sector 95",                  "Sofa Repair in Sector 95"),
  stub("sofa-repair-sector-99-gurgaon",                 "Sofa Repair in Sector 99",                  "Sofa Repair in Sector 99"),
  stub("sofa-repair-sector-102-gurgaon",                "Sofa Repair in Sector 102",                 "Sofa Repair in Sector 102"),
  stub("sofa-repair-sector-104-gurgaon",                "Sofa Repair in Sector 104",                 "Sofa Repair in Sector 104"),
  stub("sofa-repair-sector-109-gurgaon",                "Sofa Repair in Sector 109",                 "Sofa Repair in Sector 109"),
  stub("sofa-repair-sector-110-gurgaon",                "Sofa Repair in Sector 110",                 "Sofa Repair in Sector 110"),
  stub("sofa-repair-sector-111-gurgaon",                "Sofa Repair in Sector 111",                 "Sofa Repair in Sector 111"),
  stub("recliner-repair-sector-91-gurgaon",             "Recliner Repair in Sector 91",              "Recliner Repair in Sector 91"),
  stub("recliner-repair-sector-92-gurgaon",             "Recliner Repair in Sector 92",              "Recliner Repair in Sector 92"),
  stub("recliner-repair-sector-93-gurgaon",             "Recliner Repair in Sector 93",              "Recliner Repair in Sector 93"),
  stub("recliner-repair-sector-95-gurgaon",             "Recliner Repair in Sector 95",              "Recliner Repair in Sector 95"),
  stub("recliner-repair-sector-99-gurgaon",             "Recliner Repair in Sector 99",              "Recliner Repair in Sector 99"),
  stub("recliner-repair-sector-102-gurgaon",            "Recliner Repair in Sector 102",             "Recliner Repair in Sector 102"),
  stub("recliner-repair-sector-104-gurgaon",            "Recliner Repair in Sector 104",             "Recliner Repair in Sector 104"),
  stub("recliner-repair-sector-109-gurgaon",            "Recliner Repair in Sector 109",             "Recliner Repair in Sector 109"),
  stub("recliner-repair-sector-110-gurgaon",            "Recliner Repair in Sector 110",             "Recliner Repair in Sector 110"),
  stub("recliner-repair-sector-111-gurgaon",            "Recliner Repair in Sector 111",             "Recliner Repair in Sector 111"),
  stub("furniture-repair-sector-91-gurgaon",            "Furniture Repair in Sector 91",             "Furniture Repair in Sector 91"),
  stub("furniture-repair-sector-92-gurgaon",            "Furniture Repair in Sector 92",             "Furniture Repair in Sector 92"),
  stub("furniture-repair-sector-93-gurgaon",            "Furniture Repair in Sector 93",             "Furniture Repair in Sector 93"),
  stub("furniture-repair-sector-95-gurgaon",            "Furniture Repair in Sector 95",             "Furniture Repair in Sector 95"),
  stub("furniture-repair-sector-99-gurgaon",            "Furniture Repair in Sector 99",             "Furniture Repair in Sector 99"),
  stub("furniture-repair-sector-102-gurgaon",           "Furniture Repair in Sector 102",            "Furniture Repair in Sector 102"),
  stub("furniture-repair-sector-104-gurgaon",           "Furniture Repair in Sector 104",            "Furniture Repair in Sector 104"),
  stub("furniture-repair-sector-109-gurgaon",           "Furniture Repair in Sector 109",            "Furniture Repair in Sector 109"),
  stub("furniture-repair-sector-110-gurgaon",           "Furniture Repair in Sector 110",            "Furniture Repair in Sector 110"),
  stub("furniture-repair-sector-111-gurgaon",           "Furniture Repair in Sector 111",            "Furniture Repair in Sector 111"),
  // Batch D — Premium Townships
  stub("sofa-repair-vipul-world-gurgaon",               "Sofa Repair in Vipul World",                "Sofa Repair in Vipul World"),
  stub("sofa-repair-central-park-gurgaon",              "Sofa Repair in Central Park",               "Sofa Repair in Central Park"),
  stub("sofa-repair-tata-raisina-gurgaon",              "Sofa Repair in Tata Raisina Residency",     "Sofa Repair in Tata Raisina Residency"),
  stub("sofa-repair-emaar-palm-drive-gurgaon",          "Sofa Repair in Emaar Palm Drive",           "Sofa Repair in Emaar Palm Drive"),
  stub("sofa-repair-emaar-marbella-gurgaon",            "Sofa Repair in Emaar Marbella",             "Sofa Repair in Emaar Marbella"),
  stub("sofa-repair-orchid-petals-gurgaon",             "Sofa Repair in Orchid Petals",              "Sofa Repair in Orchid Petals"),
  stub("sofa-repair-bestech-park-view-gurgaon",         "Sofa Repair in Bestech Park View",          "Sofa Repair in Bestech Park View"),
  stub("sofa-repair-vatika-city-gurgaon",               "Sofa Repair in Vatika City",                "Sofa Repair in Vatika City"),
  stub("sofa-repair-richmond-park-gurgaon",             "Sofa Repair in Richmond Park",              "Sofa Repair in Richmond Park"),
  stub("sofa-repair-hamilton-court-gurgaon",            "Sofa Repair in Hamilton Court",             "Sofa Repair in Hamilton Court"),
  stub("recliner-repair-vipul-world-gurgaon",           "Recliner Repair in Vipul World",            "Recliner Repair in Vipul World"),
  stub("recliner-repair-central-park-gurgaon",          "Recliner Repair in Central Park",           "Recliner Repair in Central Park"),
  stub("recliner-repair-tata-raisina-gurgaon",          "Recliner Repair in Tata Raisina Residency", "Recliner Repair in Tata Raisina Residency"),
  stub("recliner-repair-emaar-palm-drive-gurgaon",      "Recliner Repair in Emaar Palm Drive",       "Recliner Repair in Emaar Palm Drive"),
  stub("recliner-repair-emaar-marbella-gurgaon",        "Recliner Repair in Emaar Marbella",         "Recliner Repair in Emaar Marbella"),
  stub("recliner-repair-orchid-petals-gurgaon",         "Recliner Repair in Orchid Petals",          "Recliner Repair in Orchid Petals"),
  stub("recliner-repair-bestech-park-view-gurgaon",     "Recliner Repair in Bestech Park View",      "Recliner Repair in Bestech Park View"),
  stub("recliner-repair-vatika-city-gurgaon",           "Recliner Repair in Vatika City",            "Recliner Repair in Vatika City"),
  stub("recliner-repair-richmond-park-gurgaon",         "Recliner Repair in Richmond Park",          "Recliner Repair in Richmond Park"),
  stub("recliner-repair-hamilton-court-gurgaon",        "Recliner Repair in Hamilton Court",         "Recliner Repair in Hamilton Court"),
  stub("furniture-repair-vipul-world-gurgaon",          "Furniture Repair in Vipul World",           "Furniture Repair in Vipul World"),
  stub("furniture-repair-central-park-gurgaon",         "Furniture Repair in Central Park",          "Furniture Repair in Central Park"),
  stub("furniture-repair-tata-raisina-gurgaon",         "Furniture Repair in Tata Raisina Residency","Furniture Repair in Tata Raisina Residency"),
  stub("furniture-repair-emaar-palm-drive-gurgaon",     "Furniture Repair in Emaar Palm Drive",      "Furniture Repair in Emaar Palm Drive"),
  stub("furniture-repair-emaar-marbella-gurgaon",       "Furniture Repair in Emaar Marbella",        "Furniture Repair in Emaar Marbella"),
  stub("furniture-repair-orchid-petals-gurgaon",        "Furniture Repair in Orchid Petals",         "Furniture Repair in Orchid Petals"),
  stub("furniture-repair-bestech-park-view-gurgaon",    "Furniture Repair in Bestech Park View",     "Furniture Repair in Bestech Park View"),
  stub("furniture-repair-vatika-city-gurgaon",          "Furniture Repair in Vatika City",           "Furniture Repair in Vatika City"),
  stub("furniture-repair-richmond-park-gurgaon",        "Furniture Repair in Richmond Park",         "Furniture Repair in Richmond Park"),
  stub("furniture-repair-hamilton-court-gurgaon",       "Furniture Repair in Hamilton Court",        "Furniture Repair in Hamilton Court"),
  // ── Upholstery — exemplar page (Milestone 123) ──
  stub("sofa-upholstery-sector-59-gurgaon",             "Sofa Upholstery in Sector 59, Gurgaon",     "Sofa Upholstery in Sector 59"),
  // ── Upholstery — full Gurgaon rollout ──
  stub("sofa-upholstery-new-gurgaon", "Sofa Upholstery in New Gurgaon, Gurgaon", "Sofa Upholstery in New Gurgaon"),
  stub("sofa-upholstery-sector-49-gurgaon", "Sofa Upholstery in Sector 49, Gurgaon", "Sofa Upholstery in Sector 49"),
  stub("sofa-upholstery-sector-50-gurgaon", "Sofa Upholstery in Sector 50, Gurgaon", "Sofa Upholstery in Sector 50"),
  stub("sofa-upholstery-sector-51-gurgaon", "Sofa Upholstery in Sector 51, Gurgaon", "Sofa Upholstery in Sector 51"),
  stub("sofa-upholstery-sector-56-gurgaon", "Sofa Upholstery in Sector 56, Gurgaon", "Sofa Upholstery in Sector 56"),
  stub("sofa-upholstery-sector-57-gurgaon", "Sofa Upholstery in Sector 57, Gurgaon", "Sofa Upholstery in Sector 57"),
  stub("sofa-upholstery-sector-58-gurgaon", "Sofa Upholstery in Sector 58, Gurgaon", "Sofa Upholstery in Sector 58"),
  stub("sofa-upholstery-sector-60-gurgaon", "Sofa Upholstery in Sector 60, Gurgaon", "Sofa Upholstery in Sector 60"),
  stub("sofa-upholstery-sector-61-gurgaon", "Sofa Upholstery in Sector 61, Gurgaon", "Sofa Upholstery in Sector 61"),
  stub("sofa-upholstery-sector-62-gurgaon", "Sofa Upholstery in Sector 62, Gurgaon", "Sofa Upholstery in Sector 62"),
  stub("sofa-upholstery-sector-63-gurgaon", "Sofa Upholstery in Sector 63, Gurgaon", "Sofa Upholstery in Sector 63"),
  stub("sofa-upholstery-sector-64-gurgaon", "Sofa Upholstery in Sector 64, Gurgaon", "Sofa Upholstery in Sector 64"),
  stub("sofa-upholstery-sector-65-gurgaon", "Sofa Upholstery in Sector 65, Gurgaon", "Sofa Upholstery in Sector 65"),
  stub("sofa-upholstery-sector-66-gurgaon", "Sofa Upholstery in Sector 66, Gurgaon", "Sofa Upholstery in Sector 66"),
  stub("sofa-upholstery-sector-67-gurgaon", "Sofa Upholstery in Sector 67, Gurgaon", "Sofa Upholstery in Sector 67"),
  stub("sofa-upholstery-sector-68-gurgaon", "Sofa Upholstery in Sector 68, Gurgaon", "Sofa Upholstery in Sector 68"),
  stub("sofa-upholstery-sector-69-gurgaon", "Sofa Upholstery in Sector 69, Gurgaon", "Sofa Upholstery in Sector 69"),
  stub("sofa-upholstery-sector-70-gurgaon", "Sofa Upholstery in Sector 70, Gurgaon", "Sofa Upholstery in Sector 70"),
  stub("sofa-upholstery-sector-71-gurgaon", "Sofa Upholstery in Sector 71, Gurgaon", "Sofa Upholstery in Sector 71"),
  stub("sofa-upholstery-sector-72-gurgaon", "Sofa Upholstery in Sector 72, Gurgaon", "Sofa Upholstery in Sector 72"),
  stub("sofa-upholstery-dwarka-expressway", "Sofa Upholstery on Dwarka Expressway, Gurgaon", "Sofa Upholstery on Dwarka Expressway"),
  stub("sofa-upholstery-golf-course-extension", "Sofa Upholstery in Golf Course Extension, Gurgaon", "Sofa Upholstery in Golf Course Extension"),
  stub("sofa-upholstery-dlf-phase-1", "Sofa Upholstery in DLF Phase 1, Gurgaon", "Sofa Upholstery in DLF Phase 1"),
  stub("sofa-upholstery-dlf-phase-2", "Sofa Upholstery in DLF Phase 2, Gurgaon", "Sofa Upholstery in DLF Phase 2"),
  stub("sofa-upholstery-dlf-phase-3", "Sofa Upholstery in DLF Phase 3, Gurgaon", "Sofa Upholstery in DLF Phase 3"),
  stub("sofa-upholstery-dlf-phase-4", "Sofa Upholstery in DLF Phase 4, Gurgaon", "Sofa Upholstery in DLF Phase 4"),
  stub("sofa-upholstery-dlf-phase-5", "Sofa Upholstery in DLF Phase 5, Gurgaon", "Sofa Upholstery in DLF Phase 5"),
  stub("sofa-upholstery-sushant-lok", "Sofa Upholstery in Sushant Lok, Gurgaon", "Sofa Upholstery in Sushant Lok"),
  stub("sofa-upholstery-sohna-road", "Sofa Upholstery on Sohna Road, Gurgaon", "Sofa Upholstery on Sohna Road"),
  stub("sofa-upholstery-nirvana-country", "Sofa Upholstery in Nirvana Country, Gurgaon", "Sofa Upholstery in Nirvana Country"),
  stub("sofa-upholstery-golf-course", "Sofa Upholstery on Golf Course Road, Gurgaon", "Sofa Upholstery on Golf Course Road"),
  stub("sofa-upholstery-south-city-1", "Sofa Upholstery in South City 1, Gurgaon", "Sofa Upholstery in South City 1"),
  stub("sofa-upholstery-south-city-2", "Sofa Upholstery in South City 2, Gurgaon", "Sofa Upholstery in South City 2"),
  stub("sofa-upholstery-palam-vihar", "Sofa Upholstery in Palam Vihar, Gurgaon", "Sofa Upholstery in Palam Vihar"),
  stub("sofa-upholstery-sector-40-gurgaon", "Sofa Upholstery in Sector 40, Gurgaon", "Sofa Upholstery in Sector 40"),
  stub("sofa-upholstery-sector-41-gurgaon", "Sofa Upholstery in Sector 41, Gurgaon", "Sofa Upholstery in Sector 41"),
  stub("sofa-upholstery-sector-44-gurgaon", "Sofa Upholstery in Sector 44, Gurgaon", "Sofa Upholstery in Sector 44"),
  stub("sofa-upholstery-sector-45-gurgaon", "Sofa Upholstery in Sector 45, Gurgaon", "Sofa Upholstery in Sector 45"),
  stub("sofa-upholstery-sector-46-gurgaon", "Sofa Upholstery in Sector 46, Gurgaon", "Sofa Upholstery in Sector 46"),
  stub("sofa-upholstery-sector-47-gurgaon", "Sofa Upholstery in Sector 47, Gurgaon", "Sofa Upholstery in Sector 47"),
  stub("sofa-upholstery-sector-48-gurgaon", "Sofa Upholstery in Sector 48, Gurgaon", "Sofa Upholstery in Sector 48"),
  stub("sofa-upholstery-sector-52-gurgaon", "Sofa Upholstery in Sector 52, Gurgaon", "Sofa Upholstery in Sector 52"),
  stub("sofa-upholstery-sector-53-gurgaon", "Sofa Upholstery in Sector 53, Gurgaon", "Sofa Upholstery in Sector 53"),
  stub("sofa-upholstery-sector-54-gurgaon", "Sofa Upholstery in Sector 54, Gurgaon", "Sofa Upholstery in Sector 54"),
  stub("sofa-upholstery-sector-55-gurgaon", "Sofa Upholstery in Sector 55, Gurgaon", "Sofa Upholstery in Sector 55"),
  stub("sofa-upholstery-malibu-towne", "Sofa Upholstery in Malibu Towne, Gurgaon", "Sofa Upholstery in Malibu Towne"),
  stub("sofa-upholstery-ardee-city", "Sofa Upholstery in Ardee City, Gurgaon", "Sofa Upholstery in Ardee City"),
  stub("sofa-upholstery-heritage-city-gurgaon", "Sofa Upholstery in Heritage City, Gurgaon", "Sofa Upholstery in Heritage City"),
  stub("sofa-upholstery-sector-82-gurgaon", "Sofa Upholstery in Sector 82, Gurgaon", "Sofa Upholstery in Sector 82"),
  stub("sofa-upholstery-sector-82a-gurgaon", "Sofa Upholstery in Sector 82A, Gurgaon", "Sofa Upholstery in Sector 82A"),
  stub("sofa-upholstery-sector-83-gurgaon", "Sofa Upholstery in Sector 83, Gurgaon", "Sofa Upholstery in Sector 83"),
  stub("sofa-upholstery-sector-84-gurgaon", "Sofa Upholstery in Sector 84, Gurgaon", "Sofa Upholstery in Sector 84"),
  stub("sofa-upholstery-sector-85-gurgaon", "Sofa Upholstery in Sector 85, Gurgaon", "Sofa Upholstery in Sector 85"),
  stub("sofa-upholstery-sector-86-gurgaon", "Sofa Upholstery in Sector 86, Gurgaon", "Sofa Upholstery in Sector 86"),
  stub("sofa-upholstery-sector-87-gurgaon", "Sofa Upholstery in Sector 87, Gurgaon", "Sofa Upholstery in Sector 87"),
  stub("sofa-upholstery-sector-88-gurgaon", "Sofa Upholstery in Sector 88, Gurgaon", "Sofa Upholstery in Sector 88"),
  stub("sofa-upholstery-sector-89-gurgaon", "Sofa Upholstery in Sector 89, Gurgaon", "Sofa Upholstery in Sector 89"),
  stub("sofa-upholstery-sector-90-gurgaon", "Sofa Upholstery in Sector 90, Gurgaon", "Sofa Upholstery in Sector 90"),
  stub("sofa-upholstery-sector-91-gurgaon", "Sofa Upholstery in Sector 91, Gurgaon", "Sofa Upholstery in Sector 91"),
  stub("sofa-upholstery-sector-92-gurgaon", "Sofa Upholstery in Sector 92, Gurgaon", "Sofa Upholstery in Sector 92"),
  stub("sofa-upholstery-sector-93-gurgaon", "Sofa Upholstery in Sector 93, Gurgaon", "Sofa Upholstery in Sector 93"),
  stub("sofa-upholstery-sector-95-gurgaon", "Sofa Upholstery in Sector 95, Gurgaon", "Sofa Upholstery in Sector 95"),
  stub("sofa-upholstery-sector-99-gurgaon", "Sofa Upholstery in Sector 99, Gurgaon", "Sofa Upholstery in Sector 99"),
  stub("sofa-upholstery-sector-102-gurgaon", "Sofa Upholstery in Sector 102, Gurgaon", "Sofa Upholstery in Sector 102"),
  stub("sofa-upholstery-sector-104-gurgaon", "Sofa Upholstery in Sector 104, Gurgaon", "Sofa Upholstery in Sector 104"),
  stub("sofa-upholstery-sector-109-gurgaon", "Sofa Upholstery in Sector 109, Gurgaon", "Sofa Upholstery in Sector 109"),
  stub("sofa-upholstery-sector-110-gurgaon", "Sofa Upholstery in Sector 110, Gurgaon", "Sofa Upholstery in Sector 110"),
  stub("sofa-upholstery-sector-111-gurgaon", "Sofa Upholstery in Sector 111, Gurgaon", "Sofa Upholstery in Sector 111"),
  stub("sofa-upholstery-vatika-city-gurgaon", "Sofa Upholstery in Vatika City, Gurgaon", "Sofa Upholstery in Vatika City"),
];
